Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-02, with the labels that each got.

#332 e2e tests: Add test-id var to all tests
  daisy_workflows/e2e_tests/2008r2_vmware_translate.wf.json
  daisy_workflows/e2e_tests/2012r2_vmware_translate.wf.json
  daisy_workflows/e2e_tests/attach_disks.wf.json
  daisy_workflows/e2e_tests/can_retrieve_sources.wf.json
  daisy_workflows/e2e_tests/centos_6_qcow2_translate.wf.json
  daisy_workflows/e2e_tests/centos_7_qcow2_translate.wf.json
  daisy_workflows/e2e_tests/copy_gcs_object.wf.json
  daisy_workflows/e2e_tests/create_disks.wf.json
  daisy_workflows/e2e_tests/create_images.wf.json
  daisy_workflows/e2e_tests/create_instances.wf.json
  daisy_workflows/e2e_tests/create_networks.wf.json
  daisy_workflows/e2e_tests/image_export.wf.json
  daisy_workflows/e2e_tests/image_import_and_translate_test.wf.json
  daisy_workflows/e2e_tests/image_import_test.wf.json
  daisy_workflows/e2e_tests/include_me.subwf.json
  daisy_workflows/e2e_tests/include_workflow.wf.json
  daisy_workflows/e2e_tests/ubuntu_1404_img_translate.wf.json
  daisy_workflows/e2e_tests/ubuntu_1604_vmware_translate.wf.json
  daisy_workflows/e2e_tests/wait_for_instance_signal.wf.json
Labels: size/M

#333 e2e tests: fix attach disks test script
  daisy_workflows/e2e_tests/scripts/test_devices.sh
Labels: size/XS

#334 fix Debian 9 translation workflow
  daisy_workflows/image_import/debian/translate_debian_9.wf.json
Labels: size/XS

#328 image_test: Add metadata-ssh tests
  daisy_workflows/image_test/linux_common/bootstrap.py
  daisy_workflows/image_test/linux_common/utils.py
  daisy_workflows/image_test/metadata-ssh-tester.py
  daisy_workflows/image_test/metadata-ssh.wf.json
Labels: size/L

#335 Workflows: add sleep to export startup script to ensure docker is fully running
  daisy_workflows/export/export_disk.sh
Labels: size/XS

#337 gce_image_publish: exit with non-0 on workflow creation error
  cli_tools/gce_image_publish/main.go
Labels: size/S

#338 gce_publish_tool: add string trimming functions to template
  cli_tools/gce_image_publish/main.go
  cli_tools/gce_image_publish/main_test.go
Labels: size/M

#339 Workflows: fix two sql server builds
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json
Labels: size/XS

#341 Try to reset DNS and DHCP in Ubuntu translate.
  daisy_workflows/image_import/ubuntu/translate.py
Labels: size/M

#344 gce_export: Set tar format to FormatGNU
  cli_tools/gce_export/main.go
Labels: size/S

#343 Update image_export test to create an image from the exported tar.
  daisy_workflows/e2e_tests/image_export.wf.json
Labels: size/L

#345 workflows: have export disk workflow take gce_export container path as var
  daisy_workflows/e2e_tests/image_export_latest.wf.json
  daisy_workflows/e2e_tests/image_export_release.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
  daisy_workflows/export/image_export.wf.json
Labels: size/M

#346 Wait for GCR to be online.
  daisy_workflows/export/export_disk.sh
Labels: size/XS
