Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-05, with the labels that each got.

#389 Daisy: Add GCSPath to DeleteResources step
  daisy/step_delete_resources.go
  daisy/step_delete_resources_test.go
  daisy/test_common_test.go
  docs/daisy-workflow-config-spec.md
Labels: size/L

#391 Increase export timeout to 90m.
  daisy_workflows/export/disk_export.wf.json
Labels: size/XS

#392 Workflows: Add windows 2012 translate workflow
  daisy_workflows/image_import/windows/bootstrap_2003.ps1
  daisy_workflows/image_import/windows/translate.ps1
  daisy_workflows/image_import/windows/translate_windows_2012.wf.json
Labels: size/M

#393 Daisy: Add ability to set default step timeout in workflow or command line
  cli_tools/daisy/main.go
  cli_tools/daisy/main_test.go
  cli_tools/gce_image_publish/main_test.go
  daisy/step_includeworkflow_test.go
  daisy/step_sub_workflow_test.go
  daisy/workflow.go
  daisy/workflow_test.go
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export/image_export.wf.json
  daisy_workflows/export/image_export_ext.wf.json
  docs/daisy-workflow-config-spec.md
Labels: size/M

#396 image_test: reorganize folder
  daisy_workflows/image_test/boot/boot.sh
  daisy_workflows/image_test/boot/boot.wf.json
  daisy_workflows/image_test/img_test.wf.json
  daisy_workflows/image_test/metadata-ssh/metadata-ssh-tester.py
  daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh-master-tester.py
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin_slave_tester.sh
  daisy_workflows/image_test/oslogin-ssh/oslogin_slave_tester_startup.sh
Labels: size/S

#395 Correctly print errors from translate so they show in the output string.
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_import/import_and_translate.wf.json
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_image.wf.json
  daisy_workflows/image_import/linux_common/bootstrap.py
  daisy_workflows/image_import/linux_common/utils.py
Labels: size/S

#394 Add diagnostics and inventory goospecs
  cli_tools/diagnostics/google-compute-engine-diagnostics.goospec
  cli_tools/gce_inventory_agent/google-compute-engine-inventory.goospec
  cli_tools/gce_inventory_agent/install.ps1
  cli_tools/gce_inventory_agent/uninstall.ps1
Labels: size/M

#399 Daisy: Use step timeout as default timeout for sub/include workflows
  daisy/step_includeworkflow.go
  daisy/step_includeworkflow_test.go
  daisy/step_sub_workflow.go
  daisy/step_sub_workflow_test.go
  daisy/workflow.go
Labels: size/M

#401 Change translation test to reference new google-network-daemon.
  daisy_workflows/e2e_tests/scripts/post_translate_test.sh
Labels: size/S

#403 Daisy: Log serial output to cloud logging
  daisy/logger.go
  daisy/step_attach_disks.go
  daisy/step_create_disks.go
  daisy/step_create_images.go
  daisy/step_create_instances.go
  daisy/step_create_instances_test.go
  daisy/step_create_networks.go
  daisy/step_delete_resources.go
  daisy/step_includeworkflow.go
  daisy/step_wait_for_instances_signal.go
  daisy/workflow.go
Labels: size/L

#405 Compute: Add SetInstanceMetadata function
  daisy/compute/compute.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
Labels: size/M

#409 Remove imported_disk var in 2016 translate workflow.
  daisy_workflows/image_import/windows/translate_windows_2016.wf.json
Labels: size/XS

#404 Add linux configuration integration tests
  daisy_workflows/image_test/configuration/centos.py
  daisy_workflows/image_test/configuration/configuration-test.py
  daisy_workflows/image_test/configuration/configuration.wf.json
  daisy_workflows/image_test/configuration/debian.py
  daisy_workflows/image_test/configuration/generic_distro.py
  daisy_workflows/image_test/configuration/redhat.py
  daisy_workflows/image_test/configuration/suse.py
  daisy_workflows/image_test/configuration/ubuntu.py
  daisy_workflows/image_test/img_test.wf.json
  daisy_workflows/image_test/linux_common/utils.py
Labels: size/XL

#411 Add FreeBSD configuration tests
  daisy_workflows/image_test/configuration/configuration-test.py
  daisy_workflows/image_test/configuration/configuration.wf.json
  daisy_workflows/image_test/configuration/freebsd.py
  daisy_workflows/image_test/configuration/generic_distro.py
Labels: size/L

#413 image_test: boot: improve portability
  daisy_workflows/image_test/boot/boot.sh
  daisy_workflows/image_test/boot/boot.wf.json
Labels: size/S

#412 image_test: remove SizeGb from workflows
  daisy_workflows/image_test/boot/boot.wf.json
  daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Labels: size/XS

#415 Configuration integration tests cmdline
  daisy_workflows/image_test/configuration/configuration-test.py
  daisy_workflows/image_test/configuration/debian.py
  daisy_workflows/image_test/configuration/freebsd.py
  daisy_workflows/image_test/configuration/generic_distro.py
  daisy_workflows/image_test/configuration/suse.py
  daisy_workflows/image_test/configuration/ubuntu.py
Labels: size/L

#410 Fix bug in sending serial logs to Cloud and refactor
  daisy/logger.go
  daisy/logger_test.go
  daisy/step_create_instances.go
Labels: size/L

#418 image_test: fix python shebang for FreeBSD
  daisy_workflows/image_test/linux_common/bootstrap.py
  daisy_workflows/image_test/linux_common/utils.py
  daisy_workflows/image_test/metadata-ssh/metadata-ssh-tester.py
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh-master-tester.py
Labels: size/XS

#397 daisy: Add StopStep
  daisy/compute/compute.go
  daisy/compute/compute_test.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/instance.go
  daisy/resource.go
  daisy/resource_registry.go
  daisy/resource_registry_test.go
  daisy/step.go
  daisy/step_stop_instances.go
  daisy/step_stop_instances_test.go
  daisy/step_test.go
  docs/daisy-workflow-config-spec.md
Labels: size/L

#419 Workflows: add 2016 translate test
  daisy_workflows/e2e_tests/2016_translate.wf.json
Labels: size/M

#420 Daisy: Fix logging race condition
  daisy/logger.go
  daisy/step_create_instances.go
  daisy/workflow.go
Labels: size/M

#422 daisy: fix uploading sources from subworkflows
  daisy/workflow.go
Labels: size/S

#424 daisy: fix workflow cleanup wait bug
  daisy/step_create_instances.go
  daisy/workflow.go
Labels: size/S

#427 Daisy: allow creating instances with local-sdd attached
  daisy/instance.go
  daisy_workflows/e2e_tests/create_instances.wf.json
Labels: size/M

#425 image_test: replace FULLNAME by RealName
  daisy_workflows/image_test/configuration/configuration.wf.json
  daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Labels: size/S

#432 daisy: don't close cloud logger
  daisy/logger.go
Labels: size/XS

#430 Disk integration test
  daisy_workflows/image_test/disk/disk-local-ssd.sh
  daisy_workflows/image_test/disk/disk-testee.sh
  daisy_workflows/image_test/disk/disk-tester.py
  daisy_workflows/image_test/disk/disk.wf.json
  daisy_workflows/image_test/img_test.wf.json
  daisy_workflows/image_test/linux_common/utils.py
Labels: size/XL

#433 Workflows: Add 'export_network' var to export workflows
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export/image_export.wf.json
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/M
