Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-08, with the labels that each got.

#495 image_tests: add firewall rule to allow ssh communication
  daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Labels: size/M

#497 Add FreeBSD image import
  daisy_workflows/image_import/README.md
  daisy_workflows/image_import/freebsd/translate.py
  daisy_workflows/image_import/freebsd/translate_freebsd.wf.json
Labels: size/L

#491 gce_inventory_agent: add rpm spec
  cli_tools/gce_inventory_agent/google-compute-engine-inventory.conf
  cli_tools/gce_inventory_agent/google-compute-engine-inventory.spec
Labels: size/M

#498 Fix windows container build
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Labels: size/XS

#499 Add all windows images to tests, remove configuration test for now
  daisy_workflows/image_test/windows_images.test.gotmpl
  test-infra/prow/config.yaml
Labels: size/S

#501 Configuration test: retry apt/yum network operations
  daisy_workflows/image_test/configuration/debian.py
  daisy_workflows/image_test/configuration/redhat.py
Labels: size/S

#500 oslogin-ssh test: Avoid empty ssh-keys inclusion
  daisy_workflows/image_test/oslogin-ssh/README.md
  daisy_workflows/linux_common/utils.py
Labels: size/S

#503 Fix flake8 warnings
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/google_cloud_test_repos/__init__.py
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_import/debian/translate.py
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/suse/translate.py
  daisy_workflows/image_import/ubuntu/translate.py
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh-master-tester.py
  daisy_workflows/linux_common/utils.py
Labels: size/M

#502 prow: Remove deprecated Debian 8 from linux image list
  test-infra/prow/config.yaml
Labels: size/XS

#504 Increase boot test timeout to 10m to account for Windows on small machine types
  daisy_workflows/image_test/boot/boot.wf.json
Labels: size/XS

#508 Add install_gce_packages variable to translation wrappers
  daisy_workflows/image_import/import_and_translate.wf.json
  daisy_workflows/image_import/import_from_image.wf.json
  daisy_workflows/image_import/windows/translate_windows_2003.wf.json
Labels: size/S

#507 Use debian worker image for import/export workflows
  daisy/disk.go
  daisy/instance.go
  daisy/network.go
  daisy/sources.go
  daisy/sources_test.go
  daisy/step_create_disks.go
  daisy/step_create_instances.go
  daisy/step_sub_workflow.go
  daisy/subnetwork.go
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/image_export_latest.wf.json
  daisy_integration_tests/image_export_release.wf.json
  daisy_integration_tests/image_export_vmdk.subwf.json
  daisy_integration_tests/image_export_vmdk_latest.wf.json
  daisy_integration_tests/image_export_vmdk_release.wf.json
  daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
  daisy_integration_tests/validate_cloud_logging.wf.json
  daisy_integration_tests/vmdk_import_latest.wf.json
  daisy_integration_tests/vmdk_import_release.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export/export_disk.sh
  daisy_workflows/export/export_disk_ext.sh
  daisy_workflows/export/image_export.wf.json
  daisy_workflows/export/image_export_ext.wf.json
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_image.sh
  daisy_workflows/image_import/import_image.wf.json
Labels: size/L

#509 Actually install the google-cloud-api python library.
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
Labels: size/XS

#511 Fix save logs status output.
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
Labels: size/XS

#512 Fix log uploads and cleanup redundant installs.
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/enterprise_linux/save_logs.py
Labels: size/S

#513 Check uid instead of username.
  cli_tools/import_precheck/user_linux.go
Labels: size/XS

#514 Fix metadata scripts on windows
  daisy_workflows/image_test/metadata-script/junk.ps1
  daisy_workflows/image_test/metadata-script/metadata-script-integrity.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-junk.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-linux.wf.json
  daisy_workflows/image_test/metadata-script/metadata-script-noscript.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-subwf/sub-startup-shutdown-check.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-windows.wf.json
  daisy_workflows/image_test/metadata-script/metadata-script.subwf.json
Labels: size/M

#515 Separate Linux and Windows image configuration tests
  daisy_workflows/image_test/configuration/linux-configuration.wf.json
  daisy_workflows/image_test/configuration/linux/centos.py
  daisy_workflows/image_test/configuration/linux/configuration-test.py
  daisy_workflows/image_test/configuration/linux/debian.py
  daisy_workflows/image_test/configuration/linux/freebsd.py
  daisy_workflows/image_test/configuration/linux/generic_distro.py
  daisy_workflows/image_test/configuration/linux/redhat.py
  daisy_workflows/image_test/configuration/linux/suse.py
  daisy_workflows/image_test/configuration/linux/ubuntu.py
  daisy_workflows/image_test/configuration/windows-configuration.wf.json
  daisy_workflows/image_test/configuration/windows/test_config.ps1
  daisy_workflows/image_test/linux_images.test.gotmpl
  daisy_workflows/image_test/windows_images.test.gotmpl
Labels: size/M

#516 Add windows configuration tests
  daisy_workflows/image_test/configuration/windows/test_config.ps1
Labels: size/L

#517 Fix s/configuragion/configuration typo
  daisy_workflows/image_test/windows_images.test.gotmpl
Labels: needs-ok-to-test, size/XS

#518 Don't test windows on f1-micro, bump up high resource machine type
  daisy_workflows/image_test/boot/README.md
  daisy_workflows/image_test/configuration/linux-configuration.wf.json
  daisy_workflows/image_test/linux_images.test.gotmpl
  daisy_workflows/image_test/windows_images.test.gotmpl
Labels: size/XS

#520 Add optional min_cpu_platform parameter to boot test
  daisy_workflows/image_test/boot/boot.wf.json
  daisy_workflows/image_test/linux_images.test.gotmpl
  daisy_workflows/image_test/windows_images.test.gotmpl
Labels: size/S

#519 fix typo: s/getend/getent
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh-master-tester.py
Labels: size/XS

#526 Reduce boot, disk and multi-nic test conflicts
  daisy_workflows/image_test/boot/boot.sh
  daisy_workflows/image_test/linux_images.test.gotmpl
Labels: needs-ok-to-test, size/XS

#528 Solve quota issues for windows too
  daisy_workflows/image_test/windows_images.test.gotmpl
Labels: needs-ok-to-test, size/XS

#527 Allow setting of family and description in import and translate workflows
  daisy_workflows/image_import/debian/translate_debian_8.wf.json
  daisy_workflows/image_import/debian/translate_debian_9.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json
  daisy_workflows/image_import/freebsd/translate_freebsd.wf.json
  daisy_workflows/image_import/import_and_translate.wf.json
  daisy_workflows/image_import/import_from_image.wf.json
  daisy_workflows/image_import/import_image.wf.json
  daisy_workflows/image_import/suse/translate_suse.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1404.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1604.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1804.wf.json
  daisy_workflows/image_import/windows/translate_windows_2003.wf.json
  daisy_workflows/image_import/windows/translate_windows_2008_r2.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012_r2.wf.json
  daisy_workflows/image_import/windows/translate_windows_2016.wf.json
Labels: size/L

#524 Remove code related to Debian 8 (jessie)
  daisy_tutorials/variables/vars.wf.json
  daisy_tutorials/vm_creation/simple_vm.wf.json
  daisy_workflows/image_build/debian/README.md
  docs/daisy-workflow-config-spec.md
  docs/image-import.md
Labels: size/S

#530 Update prow container version
  test-infra/prow/cluster/deck_deployment.yaml
  test-infra/prow/cluster/hook_deployment.yaml
  test-infra/prow/cluster/horologium_deployment.yaml
  test-infra/prow/cluster/plank_deployment.yaml
  test-infra/prow/cluster/sinker_deployment.yaml
  test-infra/prow/cluster/splice_deployment.yaml
  test-infra/prow/cluster/tide_deployment.yaml
  test-infra/prow/cluster/tot_deployment.yaml
Labels: size/S

#531 Update prow plugins, Makefile
  test-infra/prow/Makefile
  test-infra/prow/plugins.yaml
Labels: size/XS
