Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-04, with the labels that each got.

#378 s/zone/zones in PartialURL description
  docs/daisy-workflow-config-spec.md
Labels: size/XS

#379 Increase Windows translation timeout to 1h.
  daisy_workflows/image_import/windows/translate_windows_wf.json
Labels: size/XS

#380 Add basic Cloud Logging support.
  cli_tools/daisy/main.go
  cli_tools/daisy/main_test.go
  daisy/logger.go
  daisy/logger_test.go
  daisy/sources_test.go
  daisy/step.go
  daisy/step_attach_disks.go
  daisy/step_create_disks.go
  daisy/step_create_images.go
  daisy/step_create_instances.go
  daisy/step_create_instances_test.go
  daisy/step_create_networks.go
  daisy/step_create_networks_test.go
  daisy/step_delete_resources.go
  daisy/step_deprecate_images.go
  daisy/step_includeworkflow.go
  daisy/step_includeworkflow_test.go
  daisy/step_sub_workflow.go
  daisy/step_wait_for_instances_signal.go
  daisy/test_common_test.go
  daisy/validate_test.go
  daisy/workflow.go
  daisy/workflow_test.go
Labels: size/XL

#381 Cloud Logging - test permissions when creating client.
  daisy/disk_test.go
  daisy/network_test.go
  daisy/step_delete_resources_test.go
  daisy/step_includeworkflow_test.go
  daisy/test_common_test.go
  daisy/workflow.go
  daisy/workflow_test.go
  docs/daisy-installation-usage.md
Labels: size/L

#382 Daisy Cloud Logging integration tests
  daisy_workflows/e2e_tests/scripts/run_daisy_and_check_logs.sh
  daisy_workflows/e2e_tests/validate_cloud_logging.wf.json
Labels: size/L

#383 Run export_disk workflow with host network stack.
  daisy_workflows/export/export_disk.sh
Labels: size/XS

#384 Fix serial console logging in COS
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
Labels: size/S

#385 Daisy: Fixup cloud logging
  cli_tools/daisy/main.go
  cli_tools/daisy/main_test.go
  daisy/logger.go
  daisy/logger_test.go
  daisy/step_attach_disks.go
  daisy/step_create_disks.go
  daisy/step_create_images.go
  daisy/step_create_instances.go
  daisy/step_create_instances_test.go
  daisy/step_create_networks.go
  daisy/step_delete_resources.go
  daisy/step_deprecate_images.go
  daisy/step_includeworkflow.go
  daisy/step_sub_workflow.go
  daisy/step_wait_for_instances_signal.go
  daisy/step_wait_for_instances_signal_test.go
  daisy/validate.go
  daisy/workflow.go
  daisy/workflow_test.go
  daisy_workflows/e2e_tests/validate_cloud_logging.wf.json
Labels: size/L

#386 Daisy: set MTUs in Windows-for-containers image.
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Labels: size/S

#387 Fix logging docs.
  docs/daisy-installation-usage.md
Labels: size/S

#388 Use ID in image import disk naming
  daisy_workflows/image_import/import_image.wf.json
Labels: size/XS
