Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-03, with the labels that each got.

#347 Fix release tag and docker pull for export.
  daisy_release_cloudbuild.yaml
  daisy_workflows/export/export_disk.sh
Labels: size/S

#349 Fix image export tests by having a second stage workflow.
  daisy_workflows/e2e_tests/image_export_latest.wf.json
  daisy_workflows/e2e_tests/image_export_latest2.wf.json
  daisy_workflows/e2e_tests/image_export_release.wf.json
  daisy_workflows/e2e_tests/image_export_release2.wf.json
Labels: size/L

#350 prow: add autobuilds for prowjobs, make unittests run against all go code
  Dockerfile.daisy
  Dockerfile.gce_export
  Dockerfile.gce_image_publish
  daisy_latest_cloudbuild.yaml
  daisy_release_cloudbuild.yaml
  test-infra/prowjobs/cloudbuild.yaml
  test-infra/prowjobs/flake8/Dockerfile
  test-infra/prowjobs/flake8/main.sh
  test-infra/prowjobs/gocheck/main.sh
  test-infra/prowjobs/unittests/Dockerfile
  test-infra/prowjobs/wrapper/Dockerfile
  unittests.sh
Labels: size/M

#351 prow: add gobuild checks, go vet windows code
  packages/packages_windows.go
  test-infra/prow/config.yaml
  test-infra/prowjobs/cloudbuild.yaml
  test-infra/prowjobs/gobuild/Dockerfile
  test-infra/prowjobs/gobuild/main.sh
  test-infra/prowjobs/gocheck/main.sh
  test-infra/prowjobs/unittests/main.sh
  test-infra/prowjobs/wrapper/main.go
Labels: size/L

#353 prow: Install git for flake8 check
  test-infra/prowjobs/flake8/Dockerfile
  test-infra/prowjobs/flake8/main.sh
Labels: size/XS

#354 worfklows: add registry edits needed for Windows 2003, no workflow yet
  daisy_workflows/image_import/windows/translate_windows_2008_r2.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012_r2.wf.json
  daisy_workflows/image_import/windows/translate_windows_wf.json
  daisy_workflows/image_import/windows/windows_2003/drivers.reg
  daisy_workflows/image_import/windows/windows_2003/regini.txt
Labels: size/XL

#355 workflows: add Windows 2003 image translate workflow
  daisy_workflows/e2e_tests/2003_32_translate.wf.json
  daisy_workflows/image_import/windows/bootstrap_2003.ps1
  daisy_workflows/image_import/windows/translate_windows_2003.wf.json
  daisy_workflows/image_import/windows/windows_2003/agent.reg
  daisy_workflows/image_import/windows/windows_2003/boot.ini
  daisy_workflows/image_import/windows/windows_2003/regini.txt
  daisy_workflows/image_import/windows/windows_2003/shutdown.reg
Labels: size/L

#357 Add pseudo support for OVA
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_image.sh
Labels: size/S

#358 docs: fix typo s/Dasiy/Daisy
  docs/daisy-workflow-config-spec.md
Labels: size/XS

#356 gce_inventory_agent: make gce_inventory_agent a service
  cli_tools/gce_inventory_agent/main.go
  cli_tools/gce_inventory_agent/metadata.go
  cli_tools/import_precheck/check_sha2.go
  cli_tools/instance_inventory/main.go
  package_library/packages.go
  package_library/packages_linux.go
  package_library/packages_windows.go
  service_library/service.go
Labels: size/L

#359 prow: fix up presubmit checks to work with PR's
  daisy_latest_cloudbuild.yaml
  daisy_release_cloudbuild.yaml
  test-infra/prowjobs/cloudbuild.yaml
  test-infra/prowjobs/gobuild/main.sh
  test-infra/prowjobs/gocheck/main.sh
Labels: size/M

#361 Fix Debian build.
  daisy_workflows/image_build/debian/build.py
Labels: size/XS

#362 Spelling
  cli_tools/gce_export/main.go
  daisy/disk_test.go
  daisy_workflows/README.md
  daisy_workflows/e2e_tests/image_export_latest.wf.json
  daisy_workflows/e2e_tests/image_export_latest2.wf.json
  daisy_workflows/e2e_tests/image_export_release.wf.json
  daisy_workflows/e2e_tests/image_export_release2.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/create-synopsis-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_import/linux_common/utils.py
  daisy_workflows/image_import/ubuntu/translate.py
  daisy_workflows/image_test/metadata-ssh-tester.py
  docs/daisy-passing-data.md
  docs/daisy-styleguide.md
  docs/image-import.md
Labels: size/M

#363 Grammar
  cli_tools/import_precheck/check_disks_linux.go
  docs/image-import.md
Labels: size/S

#364 spelling: files
  docs/daisy-workflow-config-spec.md
Labels: size/XS

#367 FIx some documentation issues
  cli_tools/import_precheck/README.md
  docs/daisy-workflow-config-spec.md
Labels: size/XS

#369 Fix docs.
  daisy_workflows/image_import/README.md
Labels: size/XS

#372 Add import from image workflow
  daisy_workflows/image_import/import_from_image.wf.json
Labels: size/M

#340 Add a diagnostics tool to help collect logs on Windows.
  cli_tools/diagnostics/main.go
  cli_tools/diagnostics/main_windows.go
  cli_tools/diagnostics/stub_linux.go
  cli_tools/diagnostics/wmi_windows.go
Labels: size/XL

#374 Add descriptions to imported images.
  daisy_workflows/image_import/import_and_translate.wf.json
  daisy_workflows/image_import/import_image.wf.json
Labels: size/XS

#375 Fix Debian build and take full .tar.gz path as image_dest arg.
  daisy_workflows/image_build/debian/README.md
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/debian_8.wf.json
  daisy_workflows/image_build/debian/debian_9.wf.json
Labels: size/S
