Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-12, with the labels that each got.

#603 Fix configuration test for centos/rhel
  image_test/configuration/linux/redhat.py
Labels: size/XS

#600 metadata-ssh: test root privileges after re-add ssh key
  daisy_workflows/linux_common/utils/common.py
  image_test/metadata-ssh/metadata-ssh-tester.py
Labels: size/S

#599 RHEL for SAP point release support.
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-3-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-4-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-5-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-sap-apps-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-sap-hana-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-sap-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/rhel_7_sap.wf.json
Labels: size/M

#607 Fix rhel point release image publish so they don't conflict.
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/rhel_7_sap.wf.json
Labels: size/S

#604 Add image_import workflows for Windows 10
  daisy_workflows/image_import/windows/translate_windows_10_byol.wf.json
Labels: size/M

#605 Add image_import workflows for Windows 7
  daisy_workflows/image_import/windows/translate_windows_7_byol.wf.json
Labels: size/M

#608 Test new import files & if BYOL activation skipped
  daisy_integration_tests/10_1709_translate.wf.json
  daisy_integration_tests/7_translate.wf.json
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/scripts/post_translate_test.ps1
Labels: size/L

#609 Fix RHEL point release versions (for now).
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: size/XS

#610 osconfig_agent: add basic logging functions, add LastDeploymentChangeTime to WUA updates
  cli_tools/osconfig_agent/google-osconfig-agent.goospec
  cli_tools/osconfig_agent/inventory.go
  cli_tools/osconfig_agent/logger.go
  cli_tools/osconfig_agent/main.go
  cli_tools/osconfig_agent/osconfig.go
  cli_tools/osconfig_agent/patch_policies.go
  cli_tools/osconfig_agent/patch_state.go
  cli_tools/osconfig_agent/updates_windows.go
  go/packages/packages.go
  go/packages/packages_linux.go
  go/packages/packages_windows.go
Labels: size/L

#612 Refactor osconfig agent code into libraries and extract config.
  cli_tools/osconfig_agent/apipoller/apipoller.go
  cli_tools/osconfig_agent/attributes/attributes.go
  cli_tools/osconfig_agent/config/config.go
  cli_tools/osconfig_agent/config/metadata.go
  cli_tools/osconfig_agent/inventory/inventory.go
  cli_tools/osconfig_agent/inventory/inventory_test.go
  cli_tools/osconfig_agent/logger/logger.go
  cli_tools/osconfig_agent/main.go
  cli_tools/osconfig_agent/osconfig.go
  cli_tools/osconfig_agent/osconfig/osconfig_linux.go
  cli_tools/osconfig_agent/osconfig/osconfig_windows.go
  cli_tools/osconfig_agent/patch/patch_policies.go
  cli_tools/osconfig_agent/patch/patch_policies_test.go
  cli_tools/osconfig_agent/patch/patch_state.go
  cli_tools/osconfig_agent/patch/patch_state_test.go
  cli_tools/osconfig_agent/patch/patch_window.go
  cli_tools/osconfig_agent/patch/patch_window_test.go
  cli_tools/osconfig_agent/patch/updates_linux.go
  cli_tools/osconfig_agent/patch/updates_windows.go
Labels: size/XL

#615 UEFI workflow updates
  daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-uefi-post.cfg
  daisy_workflows/image_build/enterprise_linux/save_logs.py
Labels: size/M

#613 Move to python3
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_import/debian/translate.py
  daisy_workflows/image_import/debian/translate_debian.wf.json
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
  daisy_workflows/image_import/freebsd/translate.py
  daisy_workflows/image_import/freebsd/translate_freebsd.wf.json
  daisy_workflows/image_import/suse/translate.py
  daisy_workflows/image_import/suse/translate_suse.wf.json
  daisy_workflows/image_import/ubuntu/translate.py
  daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
  daisy_workflows/linux_common/bootstrap.py
  daisy_workflows/linux_common/bootstrap.sh
  daisy_workflows/linux_common/utils/__init__.py
  daisy_workflows/linux_common/utils/common.py
  daisy_workflows/linux_common/utils/diskutils.py
  image_test/configuration/linux-configuration.wf.json
  image_test/configuration/linux/centos.py
  image_test/configuration/linux/configuration-test.py
  image_test/configuration/linux/debian.py
  image_test/configuration/linux/freebsd.py
  image_test/configuration/linux/generic_distro.py
  image_test/configuration/linux/redhat.py
  image_test/configuration/linux/suse.py
  image_test/configuration/linux/ubuntu.py
  image_test/metadata-ssh/metadata-ssh-tester.py
  image_test/metadata-ssh/metadata-ssh.wf.json
  image_test/network/genips.py
  image_test/network/network-tester.py
  image_test/network/network.wf.json
  image_test/oslogin-ssh/oslogin-ssh-master-tester.py
  image_test/oslogin-ssh/oslogin-ssh.wf.json
Labels: size/L

#617 image_import: 7 does not support disabling hibernate
  daisy_workflows/image_import/windows/translate.ps1
Labels: size/XS

#618 daisy_integration_tests: 7 translate import
  daisy_integration_tests/7_translate.wf.json
Labels: size/XS

#616 osconfig_agent: add tasker package, rename osconfig to ospackage
  cli_tools/osconfig_agent/attributes/attributes.go
  cli_tools/osconfig_agent/config/config.go
  cli_tools/osconfig_agent/config/metadata.go
  cli_tools/osconfig_agent/inventory/inventory.go
  cli_tools/osconfig_agent/logger/logger.go
  cli_tools/osconfig_agent/main.go
  cli_tools/osconfig_agent/ospackage/ospackage.go
  cli_tools/osconfig_agent/ospackage/ospackage_linux.go
  cli_tools/osconfig_agent/ospackage/ospackage_windows.go
  cli_tools/osconfig_agent/packages/googet/google-osconfig-agent.goospec
  cli_tools/osconfig_agent/packages/googet/install.ps1
  cli_tools/osconfig_agent/packages/googet/uninstall.ps1
  cli_tools/osconfig_agent/patch/patch_policies.go
  cli_tools/osconfig_agent/service/service.go
  cli_tools/osconfig_agent/tasker/tasker.go
Labels: size/L

#619 Fix conversion to python 3 in translation workflows
  daisy_workflows/linux_common/utils/common.py
  daisy_workflows/linux_common/utils/diskutils.py
Labels: size/S

#620 image_test: catch metadata script runner failure
  image_test/metadata-script/metadata-script-inc/wait-message.wf.json
Labels: size/XS

#621 osconfig_tests: add core images, update tests a bit
  osconfig_tests/junitxml/junitxml.go
  osconfig_tests/test_suites/inventory/inventory.go
Labels: size/M

#624 linux_common: raise pending exception
  daisy_workflows/linux_common/utils/common.py
Labels: size/XS

#623 image_test: disk: don't flood logger
  image_test/disk/disk-testee.sh
Labels: size/XS

#625 image_test: oslogin: add status messages
  image_test/oslogin-ssh/oslogin-ssh-master-tester.py
  image_test/oslogin-ssh/oslogin-ssh.wf.json
Labels: size/S

#627 Fix EL builds since bootstrap.sh change.
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/save_logs.py
Labels: size/S

#628 osconfig_agent: Add Apt and Yum ospackage commands
  cli_tools/osconfig_agent/config/config.go
  cli_tools/osconfig_agent/logger/logger.go
  cli_tools/osconfig_agent/main.go
  cli_tools/osconfig_agent/ospackage/ospackage_linux.go
  cli_tools/osconfig_agent/service/service.go
  osconfig_tests/test_suites/inventory/inventory.go
Labels: size/L

#629 osconfig_agent: actually run inventory
  cli_tools/osconfig_agent/service/service.go
Labels: size/XS
