Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-06, with the labels that each got.

#435 Fix oauth2 deprecation
  daisy_workflows/image_test/disk/disk-tester.py
  daisy_workflows/image_test/disk/disk.wf.json
  daisy_workflows/image_test/linux_common/bootstrap.py
  daisy_workflows/image_test/linux_common/utils.py
  daisy_workflows/image_test/metadata-ssh/metadata-ssh-tester.py
  daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh-master-tester.py
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Labels: size/L

#439 Add daisy_test_runner tool
  cli_tools/daisy_test_runner/main.go
  daisy/logger.go
  daisy/logger_test.go
  daisy/step.go
  daisy/step_attach_disks.go
  daisy/step_create_disks.go
  daisy/step_create_images.go
  daisy/step_create_instances.go
  daisy/step_create_networks.go
  daisy/step_delete_resources.go
  daisy/step_deprecate_images.go
  daisy/step_stop_instances.go
  daisy/step_sub_workflow.go
  daisy/step_wait_for_instances_signal.go
  daisy/workflow.go
  daisy/workflow_test.go
  daisy_workflows/image_test/img_test.wf.json
  daisy_workflows/image_test/linux_images.test.gotmpl
  test-infra/README.md
  test-infra/prow/config.yaml
  test-infra/prowjobs/README.md
  test-infra/prowjobs/cloudbuild.yaml
  test-infra/prowjobs/gobuild/main.sh
  test-infra/prowjobs/test-runner/Dockerfile
  test-infra/prowjobs/test-runner/main.sh
  test-infra/prowjobs/wrapper/main.go
Labels: size/XXL

#440 daisy: fix console logging
  daisy/step_create_instances.go
Labels: size/XS

#441 prow: update container versions
  cli_tools/daisy_test_runner/main.go
  test-infra/prow/Makefile
  test-infra/prow/cluster/deck_deployment.yaml
  test-infra/prow/cluster/hook_deployment.yaml
  test-infra/prow/cluster/horologium_deployment.yaml
  test-infra/prow/cluster/plank_deployment.yaml
  test-infra/prow/cluster/sinker_deployment.yaml
  test-infra/prow/cluster/splice_deployment.yaml
  test-infra/prow/cluster/starter.yaml
  test-infra/prow/cluster/tide_deployment.yaml
  test-infra/prow/cluster/tot_deployment.yaml
  test-infra/prow/config.yaml
  test-infra/prow/plugins.yaml
  test-infra/prowjobs/gocheck/main.sh
Labels: size/M

#444 daisy: don't use workflow logger until it is instantiated
  daisy/logger.go
Labels: size/S

#443 Update EL6 builds to quote CloudSDK input.
  daisy_workflows/image_build/enterprise_linux/kickstart/co6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/ol6-post.cfg
Labels: size/XS

#437 Refactor python code: commonlize scripts utils and bootstrap
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/save_logs.py
  daisy_workflows/image_build/linux_common/bootstrap.py
  daisy_workflows/image_build/linux_common/utils.py
  daisy_workflows/image_import/debian/translate_debian.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
  daisy_workflows/image_import/linux_common/bootstrap.py
  daisy_workflows/image_import/linux_common/utils.py
  daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
  daisy_workflows/image_test/configuration/configuration.wf.json
  daisy_workflows/image_test/disk/disk.wf.json
  daisy_workflows/image_test/linux_common/bootstrap.py
  daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
  daisy_workflows/linux_common/bootstrap.py
  daisy_workflows/linux_common/utils.py
Labels: size/XXL

#446 prow: add golint back to gocheck
  test-infra/prowjobs/gocheck/main.sh
Labels: size/S

#434 Network integration image test
  daisy/compute/compute.go
  daisy/compute/compute_test.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/forwarding_rule.go
  daisy/region.go
  daisy/resource.go
  daisy/step.go
  daisy/step_create_forwarding_rule.go
  daisy/step_create_forwarding_rule_test.go
  daisy/step_create_target_instance.go
  daisy/step_create_target_instance_test.go
  daisy/target_instance.go
  daisy/test_common_test.go
  daisy/test_data/test.wf.json
  daisy/workflow.go
  daisy_workflows/image_test/network/genips.py
  daisy_workflows/image_test/network/network-testee.sh
  daisy_workflows/image_test/network/network-tester.py
  daisy_workflows/image_test/network/network.wf.json
  daisy_workflows/linux_common/utils.py
Labels: size/XXL

#449 prow: add FreeBSD 11-2 and 12-0-snap in image test
  test-infra/prow/config.yaml
Labels: size/XS

#438 Multi NIC integration test
  daisy_workflows/image_test/multi-nic/multi_nic.wf.json
Labels: size/L

#448 Remove gsutils dependency on python scripts and fix bootstrap.py
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/enterprise_linux/save_logs.py
  daisy_workflows/linux_common/bootstrap.py
  daisy_workflows/linux_common/utils.py
Labels: size/M

#447 daisy_test_runner: add project locking logic
  cli_tools/daisy_test_runner/main.go
  daisy/compute/compute.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/workflow.go
Labels: size/L

#450 Metadata script integration test
  daisy/step_stop_instances.go
  daisy/step_sub_workflow.go
  daisy_workflows/image_test/metadata-script/junk.sh
  daisy_workflows/image_test/metadata-script/metadata-script-integrity.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-junk.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-noscript.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-subwf/sub-create-instance.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-subwf/sub-startup-shutdown-check.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-subwf/sub-wait-message.subwf.json
  daisy_workflows/image_test/metadata-script/metadata-script-test-shutdown-hash.sh
  daisy_workflows/image_test/metadata-script/metadata-script-test-startup-hash.sh
  daisy_workflows/image_test/metadata-script/metadata-script.wf.json
Labels: size/XL

#451 test runner: fix wait lock loop
  cli_tools/daisy_test_runner/main.go
Labels: size/XS

#453 daisy e2e: move e2e tests to new test runner
  daisy/image.go
  daisy/sources.go
  daisy/step_copy_gcs_objects.go
  daisy/step_copy_gcs_objects_test.go
  daisy/workflow.go
  daisy_integration_tests/2003_32_translate.wf.json
  daisy_integration_tests/2008r2_vmware_translate.wf.json
  daisy_integration_tests/2012r2_vmware_translate.wf.json
  daisy_integration_tests/2016_translate.wf.json
  daisy_integration_tests/README.md
  daisy_integration_tests/can_retrieve_sources.wf.json
  daisy_integration_tests/centos_6_qcow2_translate.wf.json
  daisy_integration_tests/centos_7_qcow2_translate.wf.json
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/data/test.txt
  daisy_integration_tests/image_export_latest.wf.json
  daisy_integration_tests/image_export_release.wf.json
  daisy_integration_tests/scripts/can_retrieve_sources.sh
  daisy_integration_tests/scripts/output-and-stop.sh
  daisy_integration_tests/scripts/post_translate_test.ps1
  daisy_integration_tests/scripts/post_translate_test.sh
  daisy_integration_tests/scripts/report_success.sh
  daisy_integration_tests/scripts/retrieve-files-from-gcs.sh
  daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
  daisy_integration_tests/scripts/stop.sh
  daisy_integration_tests/scripts/test_devices.sh
  daisy_integration_tests/step_attach_disks.wf.json
  daisy_integration_tests/step_copy_gcs_object.wf.json
  daisy_integration_tests/step_create_disks.wf.json
  daisy_integration_tests/step_create_images.wf.json
  daisy_integration_tests/step_create_instances.wf.json
  daisy_integration_tests/step_create_networks.wf.json
  daisy_integration_tests/step_include_workflow.subwf.json
  daisy_integration_tests/step_include_workflow.wf.json
  daisy_integration_tests/step_wait_for_instance_signal.wf.json
  daisy_integration_tests/ubuntu_1404_img_translate.wf.json
  daisy_integration_tests/ubuntu_1604_import_and_translate.wf.json
  daisy_integration_tests/ubuntu_1604_vmware_translate.wf.json
  daisy_integration_tests/validate_cloud_logging.wf.json
  daisy_integration_tests/vmdk_import.wf.json
  daisy_workflows/e2e_tests/README.md
  daisy_workflows/e2e_tests/exact_name_no_cleanup.wf.json
  daisy_workflows/e2e_tests/exact_name_no_cleanup2.wf.json
  daisy_workflows/e2e_tests/image_export_latest.wf.json
  daisy_workflows/e2e_tests/image_export_release.wf.json
  test-infra/prow/config.yaml
  test-infra/prowjobs/cloudbuild.yaml
  test-infra/prowjobs/daisy-e2e/Dockerfile
  test-infra/prowjobs/daisy-e2e/requirements.txt
  test-infra/prowjobs/daisy-e2e/run/__init__.py
  test-infra/prowjobs/daisy-e2e/run/__main__.py
  test-infra/prowjobs/daisy-e2e/run/call.py
  test-infra/prowjobs/daisy-e2e/run/common.py
  test-infra/prowjobs/daisy-e2e/run/constants.py
  test-infra/prowjobs/daisy-e2e/run/gcs.py
  test-infra/prowjobs/daisy-e2e/run/git.py
  test-infra/prowjobs/daisy-e2e/run/result.py
  test-infra/prowjobs/wrapper/main.go
Labels: size/XL

#452 Fix WaitForInstanceSignal on stopped instance: don't give up!
  daisy/step_wait_for_instances_signal.go
  daisy/step_wait_for_instances_signal_test.go
Labels: size/M

#454 image_test: fix race condition on /dev/console
  daisy_workflows/image_test/boot/boot.sh
  daisy_workflows/image_test/boot/boot.wf.json
  daisy_workflows/image_test/metadata-ssh/metadata-ssh.wf.json
  daisy_workflows/image_test/multi-nic/multi_nic.wf.json
  daisy_workflows/image_test/network/network-testee.sh
  daisy_workflows/image_test/network/network.wf.json
  daisy_workflows/image_test/oslogin-ssh/oslogin-ssh.wf.json
Labels: size/S

#456 Fix StopInstances serial output log
  daisy/step_create_instances.go
Labels: size/S

#457 test runner: fix up some bugs in e2e tests, clean up sources
  cli_tools/daisy_test_runner/main.go
  daisy/compute/compute.go
  daisy/workflow.go
  daisy/workflow_test.go
  daisy_integration_tests/README.md
  daisy_integration_tests/can_retrieve_sources.wf.json
  daisy_integration_tests/step_create_images.wf.json
  daisy_integration_tests/ubuntu_1604_import_and_translate.wf.json
  daisy_workflows/image_test/linux_images.test.gotmpl
  test-infra/prow/config.yaml
  test-infra/prowjobs/wrapper/main.go
Labels: size/M

#459 test runner: Add CustomProjectLock
  cli_tools/daisy_test_runner/main.go
  daisy/common.go
  daisy/common_test.go
  daisy/test_data/almost_too_big.txt
  daisy/test_data/big_string.txt
Labels: size/M

#460 Fix disk integration test
  daisy/compute/compute.go
  daisy/compute/compute_test.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/instance.go
  daisy/resource_registry.go
  daisy/resource_registry_test.go
  daisy/step.go
  daisy/step_start_instances.go
  daisy/step_start_instances_test.go
  daisy/step_test.go
  daisy_workflows/image_test/disk/disk-local-ssd.sh
  daisy_workflows/image_test/disk/disk-testee.sh
  daisy_workflows/image_test/disk/disk-tester.py
  daisy_workflows/image_test/disk/disk.wf.json
  docs/daisy-workflow-config-spec.md
Labels: size/L

#462 e2e tests: fix a few permission issues, format workflows
  daisy_integration_tests/2003_32_translate.wf.json
  daisy_integration_tests/2008r2_vmware_translate.wf.json
  daisy_integration_tests/2012r2_vmware_translate.wf.json
  daisy_integration_tests/2016_translate.wf.json
  daisy_integration_tests/can_retrieve_sources.wf.json
  daisy_integration_tests/centos_6_qcow2_translate.wf.json
  daisy_integration_tests/centos_7_qcow2_translate.wf.json
  daisy_integration_tests/image_export_latest.wf.json
  daisy_integration_tests/image_export_release.wf.json
  daisy_integration_tests/scripts/output-and-stop.sh
  daisy_integration_tests/scripts/retrieve-files-from-gcs.sh
  daisy_integration_tests/scripts/stop.sh
  daisy_integration_tests/step_attach_disks.wf.json
  daisy_integration_tests/step_copy_gcs_object.wf.json
  daisy_integration_tests/step_create_disks.wf.json
  daisy_integration_tests/step_create_images.wf.json
  daisy_integration_tests/step_create_instances.wf.json
  daisy_integration_tests/step_create_networks.wf.json
  daisy_integration_tests/step_include_workflow.subwf.json
  daisy_integration_tests/step_include_workflow.wf.json
  daisy_integration_tests/step_wait_for_instance_signal.wf.json
  daisy_integration_tests/ubuntu_1404_img_translate.wf.json
  daisy_integration_tests/ubuntu_1604_import_and_translate.wf.json
  daisy_integration_tests/ubuntu_1604_vmware_translate.wf.json
  daisy_integration_tests/validate_cloud_logging.wf.json
  daisy_integration_tests/vmdk_import.wf.json
Labels: size/XXL

#463 test runner: fix custom lock logic
  cli_tools/daisy_test_runner/main.go
Labels: size/M

#464 image_test: utils: wait setMetadata operation
  daisy_workflows/linux_common/utils.py
Labels: size/XS

#465 daisy e2e tests: fix more tests
  daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
  daisy_integration_tests/step_wait_for_instance_signal.wf.json
  daisy_integration_tests/vmdk_import.wf.json
Labels: size/S

#466 daisy e2e: fix AttachDisks test
  daisy_integration_tests/step_attach_disks.wf.json
Labels: size/XS
