Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2018-10, with the labels that each got.

#556 Update FAI builds with build date.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_9_fai.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
Labels: size/S

#558 osconfig: support rebootConfig, windows update classifications and excludes
  cli_tools/gce_inventory_agent/google-compute-engine-inventory.goospec
  cli_tools/gce_inventory_agent/main.go
  cli_tools/import_precheck/check_sha2.go
  cli_tools/import_precheck/main.go
  cli_tools/instance_inventory/main.go
  cli_tools/osconfig_agent/google-osconfig-agent.goospec
  cli_tools/osconfig_agent/main.go
  cli_tools/osconfig_agent/osconfig.go
  cli_tools/osconfig_agent/osconfig_linux.go
  cli_tools/osconfig_agent/osconfig_windows.go
  cli_tools/osconfig_agent/patch_policies.go
  cli_tools/osconfig_agent/patch_policies_test.go
  cli_tools/osconfig_agent/patch_state.go
  cli_tools/osconfig_agent/patch_state_test.go
  cli_tools/osconfig_agent/updates_linux.go
  cli_tools/osconfig_agent/updates_windows.go
  go/osinfo/osinfo.go
  go/osinfo/osinfo_linux.go
  go/osinfo/osinfo_windows.go
  go/packages/packages.go
  go/packages/packages_linux.go
  go/packages/packages_windows.go
  go/service/service.go
  test-infra/prowjobs/gocheck/main.sh
Labels: size/XL

#561 gce_inventory_agent: Rewrite compressed encoding to use stacked writers
  cli_tools/gce_inventory_agent/main.go
Labels: size/S

#565 Added subnet variable to image and disk export workflows.
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export/image_export.wf.json
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/S

#566 daisy_integration_tests: fix logging and disk attachment tests
  daisy_integration_tests/2003_32_translate.wf.json
  daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
  daisy_integration_tests/scripts/test_devices.sh
  daisy_integration_tests/step_attach_disks.wf.json
Labels: size/M

#567 osconfig_agent: Update osconfig libraries
  cli_tools/osconfig_agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/assignments.pb.go
  cli_tools/osconfig_agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/os_configs.pb.go
  cli_tools/osconfig_agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/osconfig_service.pb.go
  cli_tools/osconfig_agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_policies.pb.go
  test-infra/prowjobs/gocheck/main.sh
Labels: size/XL

#568 daisy: Allow 3 different settings for network.autoCreateSubnetworks
  daisy/network.go
  daisy/network_test.go
Labels: size/S

#563 gce_inventory_agent: Update the format for WUA and QFE packages
  cli_tools/gce_inventory_agent/debian/changelog
  cli_tools/gce_inventory_agent/debian/control
  cli_tools/gce_inventory_agent/google-compute-engine-inventory.goospec
  cli_tools/gce_inventory_agent/google-compute-engine-inventory.spec
  cli_tools/gce_inventory_agent/main.go
  cli_tools/import_precheck/check_sha2.go
  go/packages/packages.go
  go/packages/packages_linux.go
  go/packages/packages_windows.go
Labels: size/L

#570 daisy: don't cancel workflow on subworkflow completion
  daisy/step_sub_workflow.go
Labels: size/S

#572 OS Config Patch Window RunOnce support
  cli_tools/osconfig_agent/patch_window.go
  cli_tools/osconfig_agent/patch_window_test.go
Labels: size/M

#571 daisy_integration_test: fix the 2003 test
  daisy_integration_tests/2003_32_translate.wf.json
Labels: size/XS

#569 Refactor shutdown image tests
  image_test/metadata-script/metadata-script-inc/shutdown-check.wf.json
  image_test/metadata-script/metadata-script-test-shutdown-hash.sh
  image_test/metadata-script/shutdown-script-integrity.wf.json
  image_test/metadata-script/shutdown-script-junk.wf.json
  image_test/metadata-script/shutdown-script-linux.wf.json
  image_test/metadata-script/shutdown-script-noscript.wf.json
  image_test/metadata-script/shutdown-script-windows.wf.json
  image_test/metadata-script/shutdown-script.wf.json
  image_test/metadata-script/startup-script-for-shutdown-tests.ps1
  image_test/metadata-script/startup-script-for-shutdown-tests.sh
Labels: size/L
