Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2019-03, with the labels that each got.

#704 Add random suffix to resource names
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/package_management/package_management_test_data.go
Labels: size/M

#706 Fix flaky tests
  osconfig_tests/test_suites/package_management/package_management.go
Labels: size/XS

#707 Fix more flaky tests
  osconfig_tests/test_suites/package_management/package_management_test_data.go
Labels: size/M

#708 Added Windows BYOL options as well as windows-2012
  cli_tools/gce_vm_image_import/README.md
  cli_tools/gce_vm_image_import/main.go
Labels: size/M

#709 Install curl in Debian images and fix a string format
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/packages/GCE_SPECIFIC
Labels: size/XS

#705 osconfig agent: read config options out of instance metadata
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/config/config_test.go
  cli_tools/google-osconfig-agent/inventory/inventory.go
  cli_tools/google-osconfig-agent/inventory/inventory_test.go
  cli_tools/google-osconfig-agent/main.go
  cli_tools/google-osconfig-agent/ospackage/apt.go
  cli_tools/google-osconfig-agent/ospackage/googet.go
  cli_tools/google-osconfig-agent/ospackage/ospackage.go
  cli_tools/google-osconfig-agent/ospackage/yum.go
  cli_tools/google-osconfig-agent/ospackage/zypper.go
  cli_tools/google-osconfig-agent/ospatch/patch_run.go
  cli_tools/google-osconfig-agent/ospatch/watcher.go
  cli_tools/google-osconfig-agent/ospatch/watcher_test.go
  cli_tools/google-osconfig-agent/tasker/tasker.go
  osconfig_tests/test_suites/inventory/inventory.go
  osconfig_tests/test_suites/package_management/package_management.go
Labels: size/XL

#711 Removing go.mod and go.sum
  go.mod
  go.sum
Labels: size/L

#703 Resize buffer disk dynamically
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export/disk_resizing_mon.sh
  daisy_workflows/export/export_disk_ext.sh
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/L

#713 Test new export flow: e2e tests to verify 10G/210G/1T/8T
  daisy_integration_tests/create_random_data_disk.sh
  daisy_integration_tests/create_random_data_image.subwf.json
  daisy_integration_tests/create_random_data_image_1024gb.wf.json
  daisy_integration_tests/create_random_data_image_10gb.wf.json
  daisy_integration_tests/create_random_data_image_210gb.wf.json
  daisy_integration_tests/create_random_data_image_8192gb.wf.json
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/image_export_vmdk.subwf.json
  daisy_integration_tests/image_export_vmdk_given_size.subwf.json
  daisy_integration_tests/image_export_vmdk_given_size_1024gb.wf.json
  daisy_integration_tests/image_export_vmdk_given_size_10gb.wf.json
  daisy_integration_tests/image_export_vmdk_given_size_210gb.wf.json
  daisy_integration_tests/image_export_vmdk_given_size_8192gb.wf.json
  daisy_integration_tests/image_export_vmdk_given_size_verify.subwf.json
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/L

#714 osconfig-agent: Fix initialization of global values
  cli_tools/google-osconfig-agent/main.go
  cli_tools/google-osconfig-agent/ospackage/ospackage.go
  go/packages/apt_deb.go
  go/packages/gem.go
  go/packages/googet.go
  go/packages/packages_linux.go
  go/packages/packages_windows.go
  go/packages/pip.go
  go/packages/yum.go
  go/packages/zypper.go
Labels: size/M

#716 Add integration tests for installation from new repo
  osconfig_tests/osconfig_server/osconfig_data_builder.go
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/package_management/package_management_test_data.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
Labels: size/L

#712 osconfig agent: use a lock file
  cli_tools/google-osconfig-agent/lock_linux.go
  cli_tools/google-osconfig-agent/lock_windows.go
  cli_tools/google-osconfig-agent/logger/logger.go
  cli_tools/google-osconfig-agent/main.go
  cli_tools/google-osconfig-agent/ospatch/patch_run.go
  cli_tools/google-osconfig-agent/packaging/googet/install.ps1
Labels: size/L

#717 When version is empty, don't append the dash in image name
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_image_publish/publish/publish_test.go
Labels: size/S

#718 Add new repo test for yum based systems
  osconfig_tests/test_suites/package_management/package_management_test_data.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
Labels: size/S

#715 Enable export e2e large test (except for 8T)
  daisy_integration_tests/daisy_e2e_daily.test.gotmpl
  daisy_integration_tests/image_export_vmdk_given_size_verify.subwf.json
  test-infra/prow/config.yaml
Labels: size/M

#721 OVF importer Dockerfile
  Dockerfile.gce_ovf_import
Labels: size/S

#722 OVF importer: fix docker image autobuilds failure
  cli_tools/gce_ovf_import/main.go
Labels: size/XS

#723 make SetExpire public, so that expiry date can be computed
  cli_tools/gce_image_publish/publish/publish.go
Labels: size/S

#719 Allow increase log verbosity through instance metadata
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/config/config_test.go
Labels: size/S

#720 Export e2e: add 2T/4T tests as weekly
  daisy_integration_tests/create_random_data_image_2048gb.wf.json
  daisy_integration_tests/create_random_data_image_4096gb.wf.json
  daisy_integration_tests/daisy_e2e_daily.test.gotmpl
  daisy_integration_tests/daisy_e2e_weekly.test.gotmpl
  daisy_integration_tests/image_export_vmdk_given_size_2048gb.wf.json
  daisy_integration_tests/image_export_vmdk_given_size_4096gb.wf.json
  daisy_integration_tests/image_export_vmdk_given_size_verify.subwf.json
  test-infra/prow/config.yaml
Labels: size/L

#725 fix "geting" typo
  daisy/step_wait_for_instances_signal.go
  osconfig_tests/compute/instance.go
Labels: size/XS

#724 update ospatch
  cli_tools/google-osconfig-agent/main.go
  cli_tools/google-osconfig-agent/ospatch/patch_run.go
  cli_tools/google-osconfig-agent/ospatch/updates_linux.go
  cli_tools/google-osconfig-agent/ospatch/updates_windows.go
  go/packages/packages_windows.go
  test-infra/prowjobs/unittests/Dockerfile
Labels: size/L

#728 Update translate to force reboot and force no restart on vmware uninstall
  daisy_workflows/image_import/windows/translate.ps1
Labels: size/XS

#727 OVF importer: additional info logs.
  cli_tools/gce_ovf_import/main.go
Labels: size/XS

#726 osconfig agent: close connections once finished with them, add metadata key for endpoint override
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/config/config_test.go
  cli_tools/google-osconfig-agent/main.go
  cli_tools/google-osconfig-agent/ospackage/ospackage.go
  cli_tools/google-osconfig-agent/ospatch/patch_run.go
  cli_tools/google-osconfig-agent/ospatch/patch_state.go
  cli_tools/google-osconfig-agent/packaging/common.sh
  cli_tools/google-osconfig-agent/packaging/debian/changelog
  cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec
Labels: size/L

#729 Correct CentOS7 GSetup path
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: size/XS

#730 osconfig agent: fix bugs in windows, reporting, linux rebooting and apt upgrading
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/config/config_test.go
  cli_tools/google-osconfig-agent/ospatch/updates_linux.go
  cli_tools/google-osconfig-agent/ospatch/updates_windows.go
  go/packages/apt_deb.go
Labels: size/M

#731 osconfig agent: update go version
  cli_tools/google-osconfig-agent/packaging/common.sh
Labels: size/XS

#732 osconfig agent: add GOCACHE
  cli_tools/google-osconfig-agent/packaging/common.sh
  cli_tools/google-osconfig-agent/packaging/debian/rules
Labels: size/XS

#733 Fix PackageManagement tests
  osconfig_tests/osconfig_server/osconfig_client.go
Labels: size/XS
