Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2019-07, with the labels that each got.

#843 improve error message from createWorkflow
  cli_tools/gce_image_publish/publish/publish.go
Labels: size/XS

#844 use parallel uploading for exporting vmdk
  daisy_workflows/export/export_disk_ext.sh
Labels: size/XS

#846 Support for multiple failure matches in Daisy.
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go
  daisy/step_wait_for_instances_signal.go
  daisy/step_wait_for_instances_signal_test.go
  daisy_workflows/image_import/import_disk.wf.json
  docs/daisy-workflow-config-spec.md
Labels: size/M

#847 Install disk expand in EL8.
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
Labels: size/XS

#845 gce_export: add component uploading with local buffer
  cli_tools/gce_export/file_writer.go
  cli_tools/gce_export/main.go
Labels: size/L

#849 Add osconfig agent tests against staging and stable versions
  osconfig_tests/config/config.go
  osconfig_tests/test_suites/inventory/test_setup.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
  osconfig_tests/test_suites/patch/test_setup.go
  osconfig_tests/utils/utils.go
  test-infra/prow/config.yaml
Labels: size/L

#848 Daisy: removed the check for network being in the same project
  daisy/instance.go
Labels: size/XS

#850 Debian10: Include gce-disk-expand, remove cloud-initramfs-growroot.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/fai_config/packages/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/scripts/10-gce-clean
Labels: size/M

#851 Up quota for osconfig tests and add new zones
  test-infra/prow/config.yaml
Labels: size/XS

#852 Revert accidental rewrite of Windows post command
  osconfig_tests/utils/utils.go
Labels: size/XS

#855 fix param network/subnet logic for import/export wrapper
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_import/main.go
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Labels: size/M

#856 Fix export_network param name
  cli_tools/gce_vm_image_export/main.go
Labels: size/XS

#853 osconfig_tests: fix OSPackage tests
  osconfig_tests/gcp_clients/gcp_clients.go
  osconfig_tests/main.go
  osconfig_tests/osconfig_server/assignment_wrapper.go
  osconfig_tests/osconfig_server/osconfig_wrapper.go
  osconfig_tests/test_suites/inventory/inventory.go
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
  osconfig_tests/test_suites/patch/patch.go
Labels: size/L

#860 [export cli tool]Exporter refactoring
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/compute/metadata_gce.go
  cli_tools/common/utils/compute/node_affinity_label_parser.go
  cli_tools/common/utils/compute/node_affinity_label_parser_test.go
  cli_tools/common/utils/compute/zone_validator.go
  cli_tools/common/utils/compute/zone_validator_test.go
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/common/utils/daisy/daisy_utils_test.go
  cli_tools/common/utils/daisy/resource_labeler.go
  cli_tools/common/utils/daisy/resource_labeler_test.go
  cli_tools/common/utils/param/key_value_parser.go
  cli_tools/common/utils/param/key_value_parser_test.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/param_utils_test.go
  cli_tools/common/utils/path/path_utils.go
  cli_tools/common/utils/storage/bucket_iterator.go
  cli_tools/common/utils/storage/object_iterator.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/common/utils/storage/storage_client_test.go
  cli_tools/common/utils/storage/tar_gcs_extractor.go
  cli_tools/common/utils/storage/tar_gcs_extractor_test.go
  cli_tools/common/utils/storage/zone_retriever.go
  cli_tools/common/utils/storage/zone_retriever_test.go
  cli_tools/common/utils/validation/validation_utils.go
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/daisycommon/daisy_utils_test.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_loader.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_validator.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_export/main_test.go
  cli_tools/gce_vm_image_import/main.go
  cli_tools/gce_vm_image_import/main_test.go
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/XL

#858 Add some useful packages to Debian 10 and move repo configs to common names.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/packages/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/scripts/10-gce-clean
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_STAGING
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_UNSTABLE
Labels: size/M

#859 Create Windows Server build from ISO wf and doc
  daisy_workflows/image_build/windows/README.md
  daisy_workflows/image_build/windows/bootstrap_install.ps1
  daisy_workflows/image_build/windows/components/Autounattend-template.xml
  daisy_workflows/image_build/windows/components/SetupComplete.cmd
  daisy_workflows/image_build/windows/post_install.ps1
  daisy_workflows/image_build/windows/windows-build.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc.wf.json
Labels: size/XL

#863 A couple of improvements for gce_export
  cli_tools/gce_export/README.md
  cli_tools/gce_export/main.go
Labels: size/S

#862 We use "-" everywhere else so be consistent.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/scripts/10-gce-clean
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_STAGING
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_UNSTABLE
Labels: size/S

#867 [OS Config] Update patch tests to v1alpha2
  osconfig_tests/gcp_clients/gcp_clients.go
  osconfig_tests/test_suites/patch/patch.go
Labels: size/M

#869 Fix debian fai typo.
  daisy_workflows/image_build/debian/build_fai.py
Labels: size/XS

#865 Refactor import wrapper
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/common/utils/daisy/daisy_utils_test.go
  cli_tools/common/utils/test/test_utils.go
  cli_tools/gce_ovf_import/main_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/main.go
  cli_tools/gce_vm_image_import/main_test.go
Labels: size/XXL
