Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2019-08, with the labels that each got.

#873 osconfig_tests: large refactor of GuestPolicy for v1alpha2
  go/e2e_test_utils/junitxml/junitxml.go
  osconfig_tests/gcp_clients/gcp_clients.go
  osconfig_tests/main.go
  osconfig_tests/osconfig_server/assignment_wrapper.go
  osconfig_tests/osconfig_server/osconfig_client.go
  osconfig_tests/osconfig_server/osconfig_data_builder.go
  osconfig_tests/osconfig_server/osconfig_wrapper.go
  osconfig_tests/test_suites/guestpolicies/guest_policies.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_test_data.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/package_management/package_management_test_data.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
  osconfig_tests/test_suites/patch/patch.go
  osconfig_tests/utils/utils.go
Labels: size/XXL

#875 osconfig_tests: Only create one GuestPolicy at a time to limit QPS
  osconfig_tests/test_suites/guestpolicies/guest_policies.go
Labels: size/S

#870 Move export related images out of the main Daisy Cloud Build config
  daisy_release_cloudbuild.yaml
  export_release_cloudbuild.yaml
Labels: size/M

#877 Build for RHEL 7.7 for SAP.
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-7-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: size/XS

#876 Import: Windows 8.1 x64
  daisy_integration_tests/81_x64_translate.wf.json
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_workflows/image_import/windows/translate_windows_8-1_x64_byol.wf.json
Labels: size/L

#762 Import: Windows Server 2019
  daisy_integration_tests/2019_translate.wf.json
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_workflows/image_import/windows/translate_windows_2019.wf.json
  daisy_workflows/image_import/windows/translate_windows_2019_byol.wf.json
Labels: size/L

#878 Enable passing IgnoreLicenseValidationIfForbidden flag for gce_image_publish workflow.
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_image_publish/publish/publish_test.go
Labels: size/M

#879 Fixed GuestOsFeatures not being parsed.
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_image_publish/publish/publish_test.go
  daisy/image.go
  daisy/image_test.go
  daisy/test_data/test.wf.json
  daisy/workflow_test.go
Labels: size/L

#872 Debian 10 secure boot support.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/fai_config/packages/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/scripts/10-gce-clean
Labels: lgtm, size/S

#880 Fixed GuestOsFeatures in wrong object in image publish test
  cli_tools/gce_image_publish/publish/publish_test.go
Labels: size/XS

#882 Add Debian sid build. Remove Debian 8 and Debian 9 Fai build (never used).
  daisy_workflows/image_build/debian/README.md
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_8.wf.json
  daisy_workflows/image_build/debian/debian_sid_fai.wf.json
Labels: size/M

#881 Fix OVF e2e test
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/XS

#871 [import/export wrapper] Change bucket creation logic
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/param_utils_test.go
  cli_tools/common/utils/paramhelper/region.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  mocks/mock_scratch_bucket_creator.go
Labels: size/L

#884 Extra error message when disk not bootable during import
  daisy/step.go
  daisy/workflow.go
  daisy_workflows/image_import/debian/translate_debian.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
  daisy_workflows/image_import/freebsd/translate_freebsd.wf.json
  daisy_workflows/image_import/suse/translate_suse.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
  daisy_workflows/image_import/windows/translate_windows_wf.json
Labels: size/M

#883 e2e test for gcloud images import/export
  gce_image_import_export_tests/main.go
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
  gce_image_import_export_tests/test_suites/test_suite_utils.go
  go/e2e_test_utils/launcher.go
  test-infra/prow/config.yaml
  test-infra/prowjobs/cloudbuild.yaml
  test-infra/prowjobs/gce-image-import-export-tests/Dockerfile
  test-infra/prowjobs/wrapper/DockerfileWithGcloud
Labels: size/XL

#887 Image-import: Preattach destination disk prior to running import_disk.sh
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_image.sh
Labels: size/M

#888 osconfig_tests: add suse support
  osconfig_tests/test_suites/guestpolicies/guest_policies.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_test_data.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go
  osconfig_tests/test_suites/inventory/inventory.go
  osconfig_tests/test_suites/inventory/test_setup.go
  osconfig_tests/test_suites/patch/patch.go
  osconfig_tests/test_suites/patch/test_setup.go
  osconfig_tests/utils/utils.go
Labels: size/L

#889 fix exit code for e2e test
  gce_image_import_export_tests/main.go
  test-infra/prowjobs/cloudbuild.yaml
Labels: size/XS

#891 fix test images build cmd
  test-infra/prowjobs/cloudbuild.yaml
Labels: size/XS

#892 extend test cloudbuild timeout to 30min
  test-infra/prowjobs/cloudbuild.yaml
Labels: size/XS

#890 Daisy bugs in non-JSON workflow creation paths.
  daisy/disk_test.go
  daisy/step_includeworkflow.go
  daisy/step_includeworkflow_test.go
  daisy/step_wait_for_instances_signal.go
  daisy/workflow.go
Labels: size/M

#893 import_image.sh: Bring back manual disk attachment.
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_image.sh
Labels: size/S

#897 Fix Debian 9 import failing if gnupg is not installed
  daisy_workflows/image_import/debian/translate.py
Labels: size/XS

#895 Fix OVF import failure when location restrictions are on
  cli_tools/common/utils/daisy/resource_labeler_test.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
Labels: size/L

#898 fix exit code for test suite launcher
  go/e2e_test_utils/launcher.go
Labels: size/XS

#900 osconfig_tests: fixup guest policy tests for suse/rhel-8
  osconfig_tests/test_suites/guestpolicies/guest_policies_test_data.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go
  osconfig_tests/utils/utils.go
  test-infra/prow/config.yaml
Labels: size/M

#894 Add Windows Server 2019 and Windows 8.1 x64 option
  cli_tools/common/utils/daisy/daisy_utils.go
  daisy_workflows/image_import/README.md
Labels: size/M

#903 [Logging] return disk/image/file size from import/export script
  daisy/step_wait_for_instances_signal.go
  daisy/step_wait_for_instances_signal_test.go
  daisy/workflow.go
  daisy_workflows/export/export_disk.sh
  daisy_workflows/export/export_disk_ext.sh
  daisy_workflows/image_import/import_image.sh
Labels: size/L

#901 Log Cloud Build ID in import/export wrappers to help with debugging
  cli_tools/common/utils/storage/zone_retriever.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/importer/importer.go
Labels: size/S

#907 Log Cloud Build ID in import/export wrappers to help with debugging
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/importer/importer.go
Labels: size/S

#908 Allocate a scratch disk when importing OVFs.
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go
Labels: size/S
