Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2019-01, with the labels that each got.

#631 Debian packaging for OSConfig agent
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/doc.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/mock_test.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client_example_test.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/assignments.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/os_configs.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/osconfig_service.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_policies.pb.go
  cli_tools/google-osconfig-agent/attributes/attributes.go
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/inventory/inventory.go
  cli_tools/google-osconfig-agent/inventory/inventory_test.go
  cli_tools/google-osconfig-agent/logger/logger.go
  cli_tools/google-osconfig-agent/main.go
  cli_tools/google-osconfig-agent/ospackage/ospackage.go
  cli_tools/google-osconfig-agent/ospackage/ospackage_linux.go
  cli_tools/google-osconfig-agent/ospackage/ospackage_windows.go
  cli_tools/google-osconfig-agent/packaging/debian/changelog
  cli_tools/google-osconfig-agent/packaging/debian/compat
  cli_tools/google-osconfig-agent/packaging/debian/control
  cli_tools/google-osconfig-agent/packaging/debian/copyright
  cli_tools/google-osconfig-agent/packaging/debian/rules
  cli_tools/google-osconfig-agent/packaging/debian/source/format
  cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec
  cli_tools/google-osconfig-agent/packaging/googet/install.ps1
  cli_tools/google-osconfig-agent/packaging/googet/uninstall.ps1
  cli_tools/google-osconfig-agent/packaging/setup_deb.sh
  cli_tools/google-osconfig-agent/patch/patch_policies.go
  cli_tools/google-osconfig-agent/patch/patch_policies_test.go
  cli_tools/google-osconfig-agent/patch/patch_state.go
  cli_tools/google-osconfig-agent/patch/patch_state_test.go
  cli_tools/google-osconfig-agent/patch/patch_window.go
  cli_tools/google-osconfig-agent/patch/patch_window_test.go
  cli_tools/google-osconfig-agent/patch/updates_linux.go
  cli_tools/google-osconfig-agent/patch/updates_windows.go
  cli_tools/google-osconfig-agent/service/service.go
  cli_tools/google-osconfig-agent/tasker/tasker.go
Labels: size/L

#633 OSConfig packaging rpm and init scripts
  cli_tools/google-osconfig-agent/google-osconfig-agent.conf
  cli_tools/google-osconfig-agent/google-osconfig-agent.service
  cli_tools/google-osconfig-agent/packaging/debian/control
  cli_tools/google-osconfig-agent/packaging/debian/rules
  cli_tools/google-osconfig-agent/packaging/google-osconfig-agent.spec
  cli_tools/google-osconfig-agent/packaging/setup_deb.sh
  cli_tools/google-osconfig-agent/packaging/setup_rpm.sh
Labels: size/L

#634 image_test/metadata-script: update the expected messages
  image_test/metadata-script/shutdown-script-linux.wf.json
  image_test/metadata-script/startup-script-linux.wf.json
Labels: size/XS

#636 Correct OSConfig import paths following name change
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/mock_test.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client_example_test.go
  cli_tools/google-osconfig-agent/inventory/inventory.go
  cli_tools/google-osconfig-agent/logger/logger.go
  cli_tools/google-osconfig-agent/main.go
  cli_tools/google-osconfig-agent/ospackage/ospackage_linux.go
  cli_tools/google-osconfig-agent/ospackage/ospackage_windows.go
  cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec
  cli_tools/google-osconfig-agent/patch/patch_policies.go
  cli_tools/google-osconfig-agent/patch/patch_policies_test.go
  cli_tools/google-osconfig-agent/patch/patch_state.go
  cli_tools/google-osconfig-agent/patch/patch_state_test.go
  cli_tools/google-osconfig-agent/patch/patch_window.go
  cli_tools/google-osconfig-agent/patch/patch_window_test.go
  cli_tools/google-osconfig-agent/patch/updates_linux.go
  cli_tools/google-osconfig-agent/patch/updates_windows.go
  cli_tools/google-osconfig-agent/service/service.go
  cli_tools/google-osconfig-agent/tasker/tasker.go
  test-infra/prowjobs/gobuild/main.sh
Labels: size/M

#640 prow: remove tot and splice config
  test-infra/prow/Makefile
  test-infra/prow/cluster/deck_deployment.yaml
  test-infra/prow/cluster/plank_deployment.yaml
Labels: size/S

#643 Fixed image building failure. Added image importer to release.
  cli_tools/gce_vm_image_import/main.go
  daisy_latest_cloudbuild.yaml
  daisy_release_cloudbuild.yaml
Labels: size/S

#642 osconfig_agent: Update autogen code for new patch api
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/mock_test.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client_example_test.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/osconfig_service.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_jobs.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_policies.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_status.pb.go
  cli_tools/google-osconfig-agent/google-osconfig-agent.service
  cli_tools/google-osconfig-agent/inventory/inventory.go
  cli_tools/google-osconfig-agent/ospackage/ospackage_linux.go
  cli_tools/google-osconfig-agent/packaging/debian/rules
  cli_tools/google-osconfig-agent/packaging/google-osconfig-agent.spec
  cli_tools/google-osconfig-agent/packaging/setup_goo.sh
  cli_tools/google-osconfig-agent/packaging/setup_rpm.sh
  cli_tools/google-osconfig-agent/patch/patch_policies.go
  cli_tools/google-osconfig-agent/patch/patch_policies_test.go
  cli_tools/google-osconfig-agent/patch/patch_run.go
  cli_tools/google-osconfig-agent/patch/patch_run_test.go
  cli_tools/google-osconfig-agent/patch/patch_state.go
  cli_tools/google-osconfig-agent/patch/patch_state_test.go
  cli_tools/google-osconfig-agent/patch/updates_linux.go
  cli_tools/google-osconfig-agent/patch/updates_windows.go
  cli_tools/google-osconfig-agent/patch/watcher.go
  cli_tools/google-osconfig-agent/service/service.go
  osconfig_tests/test_suites/inventory/inventory.go
Labels: size/XXL

#647 Change RHEL UEFI image artifact name so it doesn't conflict.
  daisy_workflows/image_build/enterprise_linux/rhel_7_uefi.wf.json
Labels: size/XS

#649 Add licenses to Linux translations.
  daisy_workflows/image_import/debian/translate_debian_8.wf.json
  daisy_workflows/image_import/debian/translate_debian_9.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json
  daisy_workflows/image_import/suse/translate_suse.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1404.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1604.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1804.wf.json
Labels: size/S

#646 osconfig_agent: update packaging process
  cli_tools/google-osconfig-agent/90-google-osconfig-agent.preset
  cli_tools/google-osconfig-agent/google-osconfig-agent.conf
  cli_tools/google-osconfig-agent/google-osconfig-agent.service
  cli_tools/google-osconfig-agent/packaging/build_packages.wf.json
  cli_tools/google-osconfig-agent/packaging/build_packages_deb.sh
  cli_tools/google-osconfig-agent/packaging/build_packages_goo.sh
  cli_tools/google-osconfig-agent/packaging/build_packages_rpm.sh
  cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec
  cli_tools/google-osconfig-agent/packaging/googet/install.ps1
  cli_tools/google-osconfig-agent/packaging/google-osconfig-agent.spec
  go/packages/packages_linux.go
  osconfig_tests/test_suites/inventory/inventory.go
Labels: size/L

#650 osconfig_tests: add utils library
  osconfig_tests/compute/instance.go
  osconfig_tests/test_suites/inventory/inventory.go
  osconfig_tests/utils/utils.go
Labels: size/L

#651 Add additional images to image test configs.
  test-infra/prow/config.yaml
Labels: size/S

#648 Add e2e test structure for package management
  cli_tools/google-osconfig-agent/service/service.go
  osconfig_tests/main.go
  osconfig_tests/osconfig_server/osconfig_service_wrapper.go
  osconfig_tests/test_suites/package_management/package_management.go
Labels: size/L

#653 osconfig_agent: update api protos
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/doc.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/mock_test.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/cloud.google.com/go/osconfig/apiv1alpha1/os_config_client_example_test.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/assignments.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/os_configs.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/osconfig_service.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_jobs.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_policies.pb.go
  cli_tools/google-osconfig-agent/_internal/gapi-cloud-osconfig-go/google.golang.org/genproto/googleapis/cloud/osconfig/v1alpha1/patch_status.pb.go
  cli_tools/google-osconfig-agent/packaging/common.sh
  cli_tools/google-osconfig-agent/packaging/debian/changelog
  cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec
  cli_tools/google-osconfig-agent/patch/patch_window.go
  cli_tools/google-osconfig-agent/patch/patch_window_test.go
Labels: size/XXL

#654 image_test: Fix metadata-script with empty ServiceAccount
  image_test/metadata-script/metadata-script-inc/create-instance-no-scope.wf.json
Labels: size/XS

#657 Fix invalid name of test OsConfig
  osconfig_tests/test_suites/package_management/package_management.go
Labels: size/XS

#658 Fix invalid name of test OsConfig
  osconfig_tests/test_suites/package_management/package_management.go
Labels: size/XS

#656 New UEFI CentOS build and publish workflows, based on RHEL
  daisy_workflows/image_build/enterprise_linux/centos_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-uefi-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: size/M

#652 Fix test results marshalling into different files
  osconfig_tests/main.go
  test-infra/prow/config.yaml
Labels: size/M

#662 Fix test grid ui for osconfig tests
  osconfig_tests/main.go
Labels: size/XS
