Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2019-06, with the labels that each got.

#824 add cleaning up done msg for workflow
  daisy/workflow.go
Labels: size/XS

#825 osconfig_tests: use old public windows images for tests
  osconfig_tests/test_suites/patch/test_setup.go
  osconfig_tests/utils/utils.go
Labels: size/M

#826 [import/export cli] add more image import/export cli tool e2e tests for rich params
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Labels: size/M

#827 fix a import line
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Labels: size/XS

#828 Fixed E2E OVF import test for Windows 2012 R2 failing.
  gce_ovf_import_tests/scripts/ovf_import_test_windows_two_disks.ps1
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/S

#829 Fixed OVF e2e test VM cleanup if test fails.
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/XS

#830 remove incorrect '#' for gce_image_import_export_tests docker
  test-infra/prowjobs/gce-image-import-export-tests/Dockerfile
Labels: size/XS

#831 osconfig_test: fix many of the flakes
  osconfig_tests/compute/instance.go
  osconfig_tests/test_suites/inventory/inventory.go
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/patch/patch.go
  osconfig_tests/utils/utils.go
Labels: size/M

#832 osconfig_tests: attempt to deflake Windows patch tests
  osconfig_tests/compute/instance.go
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/package_management/package_management_test_data.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
  osconfig_tests/test_suites/patch/patch.go
  osconfig_tests/test_suites/patch/test_setup.go
Labels: size/L

#833 [export cli tool] modify "source_image" param and fix e2e tests
  cli_tools/gce_vm_image_export/README.md
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_export/main_test.go
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
  gce_image_import_export_tests/test_suites/test_suite_utils.go
Labels: size/M

#834 Fix Windows 2003 import translate failing
  daisy_workflows/image_import/windows/translate_windows_2003.wf.json
Labels: size/XS

#835 Update Debian builds.
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_9.wf.json
  daisy_workflows/image_build/debian/debian_9_fai.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/fai_config/sources/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/sources/GCE_STAGING
  daisy_workflows/image_build/debian/fai_config/sources/GCE_UNSTABLE
  daisy_workflows/image_build/debian/fai_config/sources/file_modes
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_STAGING
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_UNSTABLE
Labels: size/L

#836 [import wrapper] fix e2e test "ImageImportWithRichParams"
  gce_image_import_export_tests/compute/image.go
  gce_image_import_export_tests/storage/file.go
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Labels: size/M

#837 Retry package installs.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/linux_common/utils/common.py
Labels: size/L

#838 [gce_export] Export raw: support exporting to local disk
  cli_tools/gce_export/README.md
  cli_tools/gce_export/file_writer.go
  cli_tools/gce_export/main.go
  daisy_workflows/export/disk_export_ext.wf.json
Labels: size/L

#839 Correct DetachDisks[].DeviceName field in the spec
  docs/daisy-workflow-config-spec.md
Labels: size/XS

#841 [daisy] a new param "print_perf" to show perf statistics on console
  cli_tools/common/utils/performance/performance_utils.go
  cli_tools/daisy/main.go
  daisy/step.go
  daisy/workflow.go
Labels: size/M
