Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2019-04, with the labels that each got.

#735 Fix Windows translate- remove unnecessary RDP restart and force shutdown to prevent possible errors.
  daisy_workflows/image_import/windows/translate.ps1
Labels: size/XS

#736 osconfig agent: actually enable ospatch when set in metadata
  cli_tools/google-osconfig-agent/ospatch/patch_run.go
  cli_tools/google-osconfig-agent/ospatch/system_linux.go
  cli_tools/google-osconfig-agent/ospatch/system_test_stub.go
  cli_tools/google-osconfig-agent/ospatch/system_windows.go
  cli_tools/google-osconfig-agent/ospatch/updates_linux.go
  cli_tools/google-osconfig-agent/ospatch/updates_test_stub.go
  cli_tools/google-osconfig-agent/ospatch/updates_windows.go
Labels: size/M

#739 osconfig agent: fix closing of a nil channel
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/logger/logger.go
  cli_tools/google-osconfig-agent/ospatch/patch_run.go
Labels: size/XS

#740 Ignoring license validation errors
  daisy/image.go
Labels: size/S

#737 OVF importer: govmomi vmware library added to third_party folder
  mocks/mock_zone_validator.go
  vendor/github.com/vmware/govmomi/LICENSE.txt
  vendor/github.com/vmware/govmomi/ovf/cim.go
  vendor/github.com/vmware/govmomi/ovf/doc.go
  vendor/github.com/vmware/govmomi/ovf/env.go
  vendor/github.com/vmware/govmomi/ovf/env_test.go
  vendor/github.com/vmware/govmomi/ovf/envelope.go
  vendor/github.com/vmware/govmomi/ovf/ovf.go
  vendor/github.com/vmware/govmomi/ovf/ovf_test.go
Labels: size/XL

#742 Fix potential time issues with Windows import
  daisy_workflows/image_import/windows/run_startup_scripts.cmd
Labels: size/XS

#743 osconfig agent: separate package manager lookup for ospackage
  cli_tools/google-osconfig-agent/ospackage/apt.go
  cli_tools/google-osconfig-agent/ospackage/googet.go
  cli_tools/google-osconfig-agent/ospackage/yum.go
  cli_tools/google-osconfig-agent/ospackage/zypper.go
  cli_tools/google-osconfig-agent/packaging/common.sh
  cli_tools/google-osconfig-agent/packaging/debian/changelog
  cli_tools/google-osconfig-agent/packaging/googet/google-osconfig-agent.goospec
  go/packages/apt_deb.go
  go/packages/gem.go
  go/packages/googet.go
  go/packages/packages.go
  go/packages/packages_linux.go
  go/packages/packages_test.go
  go/packages/packages_windows.go
  go/packages/pip.go
  go/packages/qfe_windows.go
  go/packages/rpm.go
  go/packages/wua_windows.go
  go/packages/yum.go
  go/packages/zypper.go
Labels: size/XL

#745 OS Config - Make service poll interval overridable from metadata
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/config/config_test.go
Labels: size/M

#746 Fix potential time issues with Windows import: set UTC time zone
  daisy_workflows/image_import/windows/run_startup_scripts.cmd
Labels: size/XS

#747 Fix nil pointer failure and add unit test
  cli_tools/google-osconfig-agent/config/config.go
  cli_tools/google-osconfig-agent/config/config_test.go
Labels: size/M

#748 Don't wrap error returned from exec
  go/packages/packages.go
Labels: size/XS

#750 [OsConfig Agent] answer yes to all questions
  go/packages/yum.go
Labels: size/XS

#738 [osconfig-agent] add windows end to end tests
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/package_management/package_management_test_data.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
Labels: size/L

#751 [OsConfig agent] fix windows removal startup script
  osconfig_tests/test_suites/package_management/package_management_utils.go
Labels: size/XS

#741 [OsConfig Agent] Add other supported images for different platforms
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/package_management/package_management_test_data.go
Labels: size/L

#753 Add testing tide config
  test-infra/prow/Makefile
  test-infra/prow/cluster/tide_deployment.yaml
  test-infra/prow/config.yaml
Labels: size/S

#756 Add "custom_translate_workflow" flag for gce vm image import cli tool
  cli_tools/gce_vm_image_import/main.go
  cli_tools/gce_vm_image_import/main_test.go
Labels: size/M

#758 Create dummy.txt
  dummy.txt
Labels: approved, lgtm, size/XS

#760 Update tide image, disable dry-run
  test-infra/prow/Makefile
  test-infra/prow/cluster/tide_deployment.yaml
Labels: size/S

#759 OVF Import: use OVF osType attribute if --os flag not set.
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/main_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
Labels: size/L

#757 [daisy Import] throw error msg
  daisy_workflows/image_import/import_image.sh
Labels: size/S

#761 fix bucket split logic
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/gce_vm_image_import/main.go
Labels: size/S

#764 Create grr.txt
  grr.txt
Labels: approved, lgtm, size/XS

#765 Update dummy.txt
  dummy.txt
Labels: approved, lgtm, size/XS

#766 Update grr.txt
  grr.txt
Labels: approved, lgtm, size/XS

#752 [OsConfig agent] Add framework for patching e2e test and a basic test case
  osconfig_tests/compute/instance.go
  osconfig_tests/main.go
  osconfig_tests/test_suites/inventory/inventory.go
  osconfig_tests/test_suites/package_management/package_management.go
  osconfig_tests/test_suites/patch/patch.go
  osconfig_tests/utils/utils.go
Labels: size/XL

#769 [Osconfig Agent] Fix e2e tests of yum based platforms
  osconfig_tests/test_suites/package_management/package_management_test_data.go
  osconfig_tests/test_suites/package_management/package_management_utils.go
Labels: size/M

#767 Untranslated image: remove from workflow
  daisy_workflows/image_import/import_and_translate.wf.json
Labels: size/S

#763 OVF Import: instance creation in sole tenant nodes
  cli_tools/common/utils/compute/node_affinity_label_parser.go
  cli_tools/common/utils/compute/node_affinity_label_parser_test.go
  cli_tools/common/utils/flags/string_array_flag.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/main_test.go
Labels: size/L
