Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2019-09, with the labels that each got.

#910 Increase scratch disk to account for EXT4 overhead.
  daisy_workflows/image_import/import_image.sh
Labels: size/S

#912 Install OSConfig agent in Debian 10 and RHEL 8.
  daisy_workflows/image_build/debian/fai_config/packages/GCE_SPECIFIC
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
Labels: size/XS

#914 Refactor: Move ovf programmatic unit parsing to its own file.
  cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
Labels: size/L

#909 Add function to gather kubernetes logs
  cli_tools/diagnostics/main_windows.go
  cli_tools/diagnostics/main_windows_test.go
Labels: size/L

#916 Support additional unit types for OVF disk and memory sizes.
  cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_programmatic_units_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
Labels: size/L

#913 Ovf import cleanup on error
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  daisy/resource_registry.go
  daisy/resource_registry_test.go
  daisy/workflow.go
  daisy/workflow_test.go
Labels: size/M

#917 Added Debian 9 to OVF import E2E tests
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/S

#922 prowjobs wrapper: fix artifact upload
  test-infra/prowjobs/README.md
  test-infra/prowjobs/wrapper/main.go
Labels: size/S

#919 daisy: compute: Retry on transport-level failures
  daisy/compute/compute.go
  daisy/compute/compute_test.go
Labels: size/XS

#921 OVF import E2E tests: override Build ID
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/S

#924 Add debug logs prior to using dynamically-sized disks.
  daisy_workflows/image_import/import_image.sh
Labels: size/S

#925 osconfig_tests: fix suse package tests, add more patch tests
  osconfig_tests/test_suites/guestpolicies/guest_policies_test_data.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go
  osconfig_tests/test_suites/patch/patch.go
  osconfig_tests/test_suites/patch/test_setup.go
  osconfig_tests/utils/utils.go
Labels: size/M

#926 Updated OVF importer docs
  cli_tools/gce_ovf_import/README.md
  cli_tools/gce_ovf_import/main.go
Labels: size/S

#928 Support VirtualBox ovfs
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
  cli_tools/gce_ovf_import/ovf_utils/testdata/from-virtualbox.ovf
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
  vendor/github.com/vmware/govmomi/ovf/cim.go
  vendor/github.com/vmware/govmomi/ovf/envelope.go
Labels: size/L

#923 gce_image_publish: set optional ObsoleteDate
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_image_publish/publish/publish_test.go
Labels: size/S

#929 Log OVF import flags to aid debugging customer issues
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
Labels: size/XS

#930 Disable startup script e2e test validation for Debian 9
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/S

#931 Fix yum reinstall test so that we make sure new package is available.
  daisy_integration_tests/scripts/post_translate_test.sh
Labels: size/XS

#927 test-infra: make sure artifact directory is set in environmnet
  test-infra/prow/config.yaml
Labels: size/M

#932 osconfig_tests: fix suse tests
  osconfig_tests/utils/utils.go
Labels: size/XS

#933 osconfig_tests: fix rhel and zypper installs
  osconfig_tests/utils/utils.go
Labels: size/S

#936 Add OVF test for image exported by AWS.
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/S

#938 Update license for Windows Server 2019 BYOL import
  daisy_workflows/image_import/windows/translate_windows_2019_byol.wf.json
Labels: size/XS

#935 Enable GuestOsFeatures for intermediate Windows disks
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  daisy/disk.go
  daisy/disk_test.go
  daisy_workflows/image_import/import_and_translate.wf.json
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_from_image.wf.json
Labels: size/L

#939 osconfig_tests: ensure latest package is isntalled for GuestPolicies
  osconfig_tests/compute/instance.go
  osconfig_tests/test_suites/guestpolicies/guest_policies.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_test_data.go
  osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go
  osconfig_tests/utils/utils.go
Labels: size/L

#941 osconfig_tests: don't stop agent on install, fix flag parsing
  osconfig_tests/config/config.go
  osconfig_tests/main.go
  osconfig_tests/utils/utils.go
Labels: size/L

#942 Fix is_windows variable name causing E2E test failures
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
Labels: size/XS

#934 [export wrapper] support simple image name
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
Labels: size/S

#944 osconfig_tests: make package test work with Ubuntu
  osconfig_tests/test_suites/guestpolicies/guest_policies_utils.go
  osconfig_tests/test_suites/inventory/test_setup.go
Labels: size/M

#945 Remove the use of Time.Milliseconds()
  cli_tools/common/utils/logging/service/logger.go
Labels: size/XS

#947 Fix the em dash that was causing sles-12 issues
  osconfig_tests/utils/utils.go
Labels: size/XS
