Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-08, with the labels that each got.

#1289 Install OS config agent during import.
  daisy_integration_tests/2008r2_vmware_translate.wf.json
  daisy_integration_tests/debian_8_translate.wf.json
  daisy_integration_tests/opensuse_15_1.wf.json
  daisy_integration_tests/scripts/post_translate_test.ps1
  daisy_integration_tests/scripts/post_translate_test.sh
  daisy_integration_tests/sles_12_4_byol.wf.json
  daisy_integration_tests/sles_12_5_byol.wf.json
  daisy_integration_tests/sles_15_1_byol.wf.json
  daisy_integration_tests/sles_sap_12_4_byol.wf.json
  daisy_integration_tests/ubuntu_1404_img_translate.wf.json
  daisy_integration_tests/ubuntu_1604_vmware_translate.wf.json
  daisy_integration_tests/ubuntu_1804_aws.wf.json
  daisy_integration_tests/ubuntu_1804_azure.wf.json
  daisy_integration_tests/ubuntu_1804_vmware.wf.json
  daisy_integration_tests/windows_10_x86_byol.wf.json
  daisy_integration_tests/windows_7_x86_byol.wf.json
  daisy_integration_tests/windows_8_x86_byol.wf.json
  daisy_workflows/image_import/debian/translate.py
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, size/L

#1309 Add variables flag to E2E tests
  go/e2e_test_utils/go.mod
  go/e2e_test_utils/launcher.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#1310 Image import: Include UEFI guest OS feature during inflation, if requested.
  cli_tools/gce_vm_image_import/importer/api_inflater.go
  cli_tools/gce_vm_image_import/importer/api_inflater_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/post_translate_test.wf.json
  daisy_integration_tests/scripts/post_translate_test.ps1
  gce_image_import_export_tests.Dockerfile
Labels: approved, lgtm, size/L

#1311 Don't check for OSConfig agent in Ubuntu e2e test.
  daisy_integration_tests/image_import_and_translate_ova_with_spaces_in_vmdk_filename.wf.json
Labels: approved, lgtm, size/XS

#1307 [Onestep Import] e2e tests
  cli_tools_e2e_test/gce_image_import_export/main.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/aws_test_utils.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/scripts/post_translate_test.wf.json
  cli_tools_e2e_test/go.mod
  gce_image_import_export_tests.Dockerfile
Labels: approved, lgtm, needs-ok-to-test, size/L

#1314 [Onestep Image Import] Add onestep import test variables in test infra
  test-infra/prow/config.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1313 OVF e2e: Whitelist platforms not supporting osconfig agent
  cli_tools_e2e_test/common/compute/instance.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
Labels: approved, lgtm, size/M

#1312 Check for OS config agent in Windows e2e
  daisy_integration_tests/scripts/post_translate_test.ps1
Labels: approved, lgtm, size/XS

#1315 EL import: Ensure /etc/yum.repos.d exists.
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, lgtm, size/XS

#1316 [Onestep Import] Move sections in prow config to trigger args update
  test-infra/prow/config.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#1318 Disable OS config test on windows_7_x64_byol.wf.json
  daisy_integration_tests/windows_7_x64_byol.wf.json
Labels: approved, lgtm, size/XS

#1297 EL build fixes and additions
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/cleanup.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el6-cleanup.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el6-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-cleanup.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-cleanup.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-packages.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-byos-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-sap-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel8-1-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel8-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel8-sap-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/rhel_8_sap.wf.json
  daisy_workflows/image_build/enterprise_linux/save_logs.py
Labels: approved, lgtm, size/L

#1319 prow config: add cos to osconfig-head-images tests
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/XS

#1317 Added client version flag to all the wrappers and logging
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/gce_onestep_image_import/main.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/utils.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/main.go
  cli_tools/gce_windows_upgrade/main.go
Labels: approved, lgtm, size/M

#1321 Fix return statement in RHEL 7 SAP build.
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel7-sap-post.cfg
Labels: approved, lgtm, size/XS

#1320 [Onestep Image Import] Remove adding HTTP client option to gcs client
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer_test.go
  cli_tools/go.mod
Labels: approved, lgtm, needs-ok-to-test, size/S

#1324 [Onestep Image Import E2E] Skip os-config-agent check for ubuntu
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/aws_test_utils.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/scripts/post_translate_test.wf.json
Labels: approved, lgtm, needs-ok-to-test, size/M

#1325 [Onestep Image Import E2E] Fix e2e test errors
  cli_tools/gce_onestep_image_import/onestep_importer/utils.go
  cli_tools/go.mod
  cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1323 Test RHEL 8 import with e2e
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, lgtm, size/XS

#1327 First batch of M4CE adaptation E2E tests
  daisy_integration_tests/2012r2_vmware_translate.wf.json
  daisy_integration_tests/2019_translate.wf.json
  daisy_integration_tests/scripts/v2v_adapt.sh
  daisy_integration_tests/v2v_adapt_e2e.test.gotmpl
  daisy_integration_tests/v2v_adapt_windows.wf.json
  daisy_integration_tests/v2v_adapt_windows_byol.wf.json
  daisy_integration_tests/windows_10_x64_byol.wf.json
  daisy_integration_tests/windows_7_x64_byol.wf.json
  daisy_integration_tests/windows_8_x64_byol.wf.json
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/L

#1330 [Onestep Import] Change image import exec path
  cli_tools/gce_onestep_image_import/onestep_importer/utils.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1328 Adding more Windows V2V adapt E2E tests
  daisy_integration_tests/2008r2_vmware_translate.wf.json
  daisy_integration_tests/2016_translate.wf.json
  daisy_integration_tests/v2v_adapt_e2e.test.gotmpl
  daisy_integration_tests/windows_10_x86_byol.wf.json
  daisy_integration_tests/windows_7_x86_byol.wf.json
  daisy_integration_tests/windows_8_x86_byol.wf.json
Labels: approved, size/M

#1331 Daisy e2e: Increase wait period prior to checking logs
  daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
Labels: approved, lgtm, size/XS

#1329 Support import of Ubuntu 20.04
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/gce_onestep_image_import/README.md
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_ovf_import/README.md
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_vm_image_import/README.md
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/ubuntu/translate.py
  daisy_workflows/image_import/ubuntu/translate_ubuntu_2004.wf.json
Labels: approved, enhancement, lgtm, size/L

#1326 Configure Python inspection unit tests to work with pytest
  daisy_workflows/image_import/inspection/README.md
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
  daisy_workflows/image_import/inspection/daisy-shim.sh
  daisy_workflows/image_import/inspection/inspectors/os/__init__.py
  daisy_workflows/image_import/inspection/pyproject.toml
  daisy_workflows/image_import/inspection/setup.py
  daisy_workflows/image_import/inspection/src/boot_inspect/__init__.py
  daisy_workflows/image_import/inspection/src/boot_inspect/cli.py
  daisy_workflows/image_import/inspection/src/boot_inspect/inspection.py
  daisy_workflows/image_import/inspection/src/boot_inspect/inspectors/__init__.py
  daisy_workflows/image_import/inspection/src/boot_inspect/inspectors/os/__init__.py
  daisy_workflows/image_import/inspection/src/boot_inspect/inspectors/os/architecture.py
  daisy_workflows/image_import/inspection/src/boot_inspect/inspectors/os/linux.py
  daisy_workflows/image_import/inspection/src/boot_inspect/inspectors/os/windows.py
  daisy_workflows/image_import/inspection/src/boot_inspect/model.py
  daisy_workflows/image_import/inspection/src/boot_inspect/system/__init__.py
  daisy_workflows/image_import/inspection/src/boot_inspect/system/filesystems.py
  daisy_workflows/image_import/inspection/tests/linux_tests.py
  daisy_workflows/image_import/inspection/tests/test_linux.py
  daisy_workflows/image_import/inspection/tests/test_model.py
Labels: approved, size/L

#1334 Update Go inspection clients workflow reference
  cli_tools/common/disk/inspect.go
Labels: approved, lgtm, size/XS

#1306 Add two steps to create a disk with root.tar.gz for debian
  cli_tools/go.mod
  cli_tools/go.sum
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_9.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/debian_sid_fai.wf.json
Labels: approved, lgtm, size/L

#1332 Deploying image import wrappers to Artifact registry
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/XS
