Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-06, with the labels that each got.

#1237 Update image-import.md
  docs/image-import.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1238 Fixed nil pointer dereference breaking OVF import
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
Labels: approved, lgtm, size/S

#1226 [windows upgrade] improve params
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/gce_windows_upgrade/main.go
  cli_tools/gce_windows_upgrade/upgrader/test_common_test.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader_test.go
  cli_tools/gce_windows_upgrade/upgrader/utils_test.go
  cli_tools/gce_windows_upgrade/upgrader/validators_test.go
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
  cli_tools/gce_windows_upgrade/upgrader/workflows_test.go
  cli_tools_e2e_test/common/compute/instance.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_e2e_test/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
Labels: approved, lgtm, size/L

#1222 Image import: Show detection results only when libguestfs's results can be verified.
  cli_tools/common/assert/assert.go
  cli_tools/common/assert/assert_test.go
  cli_tools/common/assert/doc.go
  cli_tools/common/distro/distro.go
  cli_tools/common/distro/distro_test.go
  cli_tools/gce_vm_image_import/importer/errors.go
  cli_tools/gce_vm_image_import/importer/errors_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
Labels: approved, size/XL

#1168 Use disk file from daisy's scratch path.
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_image.sh
Labels: approved, lgtm, size/XS

#1241 Revert "Use disk file from daisy's scratch path."
  daisy_workflows/image_import/import_disk.wf.json
  daisy_workflows/image_import/import_image.sh
Labels: approved, lgtm, size/XS

#1239 Added custom cancel reason to Daisy workflow.
  daisy/step.go
  daisy/workflow.go
  daisy/workflow_test.go
Labels: approved, lgtm, size/L

#1242 Added global timeout to OVF import
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/mocks/mock_logger.go
Labels: approved, lgtm, size/L

#1227 Split image import into two phases.
  cli_tools/common/utils/logging/service/literal_loggable.go
  cli_tools/common/utils/logging/service/literal_loggable_test.go
  cli_tools/common/utils/logging/service/logger_test.go
  cli_tools/common/utils/string/string_utils.go
  cli_tools/common/utils/string/string_utils_test.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/source_test.go
  cli_tools/gce_vm_image_import/importer/testdata/image_import
  cli_tools/gce_vm_image_import/main.go
  daisy_integration_tests/image_export_vmdk.subwf.json
  daisy_integration_tests/image_export_vmdk_given_size_verify.subwf.json
  daisy_workflows/image_import/import_and_translate.wf.json
  daisy_workflows/image_import/import_image.sh
  daisy_workflows/image_import/import_image.wf.json
  daisy_workflows/image_import/inflate_file.wf.json
  daisy_workflows/image_import/inflate_image.wf.json
  daisy_workflows/ovf_import/import_ovf_to_instance.wf.json
  daisy_workflows/ovf_import/import_ovf_to_machine_image.wf.json
Labels: approved, do-not-merge/hold, size/XXL

#1244 Sanitize control characters from image filename.
  daisy_workflows/image_import/import_image.sh
  daisy_workflows/image_import/inflate_file.wf.json
Labels: approved, lgtm, size/S

#1248 Update Docker version to latest
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Labels: approved, lgtm, size/XS

#1064 test-infra: update FreeBSD images
  test-infra/prow/config.yaml
Labels: lgtm, ok-to-test, size/XS

#1240 Refactor buffered writer
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/storage/buffered_writer.go
  cli_tools/common/utils/storage/buffered_writer_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/common/utils/storage/storage_client_test.go
  cli_tools/common/utils/storage/storage_object.go
  cli_tools/common/utils/storage/tar_gcs_extractor.go
  cli_tools/common/utils/storage/tar_gcs_extractor_test.go
  cli_tools/gce_export/main.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/importer/source.go
  cli_tools/gce_vm_image_import/importer/source_test.go
  cli_tools/gce_vm_image_import/main.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/mocks/mock_object_deleter.go
  cli_tools/mocks/mock_storage_client.go
  cli_tools/mocks/mock_storage_object.go
  cli_tools/mocks/mock_storage_object_creator.go
Labels: approved, do-not-merge/hold, lgtm, ok-to-test, size/XXL

#1249 [windows upgrade] post-upgrade step; log privacy
  cli_tools/gce_windows_upgrade/upgrade_script_2008r2_to_2012r2.ps1
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
Labels: approved, lgtm, size/S

#1257 Ensure destination image doesn't exist prior to running import.
  cli_tools/gce_vm_image_import/importer/data_disk_processor.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/validator.go
  cli_tools/gce_vm_image_import/importer/validator_test.go
Labels: approved, do-not-merge/hold, lgtm, size/L

#1258 Revert "Sanitize control characters from image filename. (#1244)"
  daisy_workflows/image_import/import_image.sh
  daisy_workflows/image_import/inflate_file.wf.json
Labels: approved, lgtm, size/S

#1255 [windows upgrade] firelog: adjust field sequence
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/gce_windows_upgrade/main.go
Labels: approved, lgtm, size/S

#1256 [windows upgrade] show cleanup guide again when success
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  cli_tools/gce_windows_upgrade/upgrader/utils_test.go
Labels: approved, lgtm, size/M

#1262 Don't allocate an external IP during inflation.
  daisy_workflows/image_import/inflate_file.wf.json
Labels: approved, lgtm, size/XS

#1259 Support ShieldedInstanceInitialState in the publish workflow
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_image_publish/publish/publish_test.go
Labels: approved, lgtm, size/M

#1251 Improve the logging of diagnostics
  cli_tools/diagnostics/main.go
Labels: approved, lgtm, size/XS

#1265 During inflate, allocate external IP unless NoExternalIP is set.
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  daisy_workflows/image_import/inflate_file.wf.json
Labels: approved, lgtm, size/M

#1268 fix err typo, otherwise it won't be built in bazel
  daisy/workflow.go
Labels: approved, lgtm, size/XS

#1270 [windows upgrade] rename 'OS disk' to 'boot disk' on user interface
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  cli_tools/gce_windows_upgrade/upgrader/validators.go
  cli_tools/gce_windows_upgrade/upgrader/validators_test.go
Labels: approved, lgtm, size/S

#1269 [daisy] fixed 2 DetachDisks problem
  daisy/disk.go
  daisy/disk_test.go
  daisy/instance.go
  daisy/resource_registry.go
  daisy/step_attach_disks.go
  daisy/step_detach_disk_test.go
  daisy/step_detach_disks.go
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/step_detach_disks.wf.json
Labels: approved, lgtm, size/L

#1260 Clear immutable attr from 70-persistent-net.rules before deleting.
  daisy_workflows/linux_common/utils/common.py
Labels: approved, lgtm, size/S

#1271 [windows upgrade] use new daisy module
  cli_tools/go.mod
  cli_tools/go.sum
Labels: approved, lgtm, size/M

#1272 [windows-upgrade e2e] add gcloud e2e tests
  cli_tools_e2e_test/common/utils/utils.go
  cli_tools_e2e_test/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
Labels: approved, size/M

#1275 [windows upgrade e2e] delete instance after test
  cli_tools_e2e_test/common/utils/utils.go
  cli_tools_e2e_test/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
Labels: approved, lgtm, size/S

#1276 fix export
  daisy_workflows/export/export_disk_ext.sh
Labels: approved, lgtm, size/XS

#1274 refactored flag value into common utils
  cli_tools/common/utils/flags/key_value_flag.go
  cli_tools/common/utils/flags/key_value_flag_test.go
  cli_tools/common/utils/flags/string_utils.go
  cli_tools/common/utils/flags/string_utils_test.go
  cli_tools/gce_vm_image_import/importer/args.go
Labels: approved, lgtm, ok-to-test, size/L
