Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-07, with the labels that each got.

#1278 [export] adjust 'echo' sequence
  daisy_workflows/export/export_disk_ext.sh
Labels: approved, lgtm, size/XS

#1280 daisy/: added variable parsing to resize-disk.
  daisy/step_resize_disks.go
Labels: approved, lgtm, ok-to-test, size/S

#1263 Image import global timeout handling
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/main.go
Labels: approved, size/L

#1284 Cleanup in cli_tools/gce_vm_image_import/importer.
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/source.go
Labels: approved, lgtm, size/XS

#1285 Check for /etc/resolvconf/resolv.conf.d/base before modifying it.
  daisy_workflows/image_import/ubuntu/translate.py
Labels: approved, lgtm, size/XS

#1252 Add script to export image and package metadata during linux builds
  cli_tools_e2e_test/go.sum
  daisy_workflows/guest_package.txt
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_9.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/debian_sid_fai.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_6.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_7.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_8.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_8_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/export_metadata.py
  daisy_workflows/image_build/enterprise_linux/rhel_6.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_6_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_sap.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_uefi.wf.json
Labels: approved, lgtm, ok-to-test, size/XL

#1264 Add script to export image and package metadata during windows builds
  daisy_workflows/image_build/windows/post_install.ps1
Labels: approved, lgtm, ok-to-test, size/M

#1281 Set timeout of 2hr for osconfig tests
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/XS

#1277 An image import suite focused on translation logic.
  cli_tools_e2e_test/common/logging/logging.go
  cli_tools_e2e_test/gce_image_import_export/main.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/post_translate_test.wf.json
  gce_image_import_export_tests.Dockerfile
Labels: approved, lgtm, size/L

#1283 Avoid resizing PDs on inflation worker during import.
  cli_tools/common/gcsfuse/client.go
  cli_tools/common/imagefile/inspector.go
  cli_tools/common/imagefile/inspector_test.go
  cli_tools/common/imagefile/qemu_img.go
  cli_tools/common/imagefile/qemu_img_test.go
  cli_tools/common/utils/files/files.go
  cli_tools/common/utils/files/files_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  daisy_workflows/image_import/import_image.sh
  daisy_workflows/image_import/inflate_file.wf.json
  gce_vm_image_import.Dockerfile
  gcsfuse-apt-key.gpg
Labels: approved, lgtm, size/XL

#1261 onestep image from AWS
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/gce_onestep_image_import/README.md
  cli_tools/gce_onestep_image_import/main.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_args.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_args_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/test_utils_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/utils.go
  cli_tools/gce_onestep_image_import/onestep_importer/utils_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  gce_onestep_image_import.Dockerfile
Labels: approved, ok-to-test, size/XXL

#1287 Fix build failure
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/export_metadata.py
Labels: approved, lgtm, ok-to-test, size/XS

#1286 Scaffold for disk inspection.
  cli_tools/common/disk/inspect.go
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  daisy_workflows/image_import/inspection/inspect-disk.wf.json
  daisy_workflows/image_import/inspection/inspect_disk.py
Labels: approved, lgtm, size/L

#1291 Don't install the EOL python guest in EL imports.
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, lgtm, size/S

#1292 Pass inflation disk sizes during OVF data disk import.
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go
  daisy_workflows/image_import/import_image.sh
Labels: approved, size/S

#1290 [new vmdk api adoption] daisy support new vmdk alpha API
  daisy/compute/compute.go
Labels: approved, lgtm, size/M

#1294 Load disk inspection workflow relative to daisy_workflows directory.
  cli_tools/common/disk/inspect.go
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
Labels: approved, lgtm, size/S

#1295 Ensure gce_vm_image_import.Dockerfile has CA certs.
  gce_vm_image_import.Dockerfile
Labels: approved, lgtm, size/XS

#1296 Rollback Linux image metadata changes.
  cli_tools_e2e_test/go.sum
  daisy_workflows/guest_package.txt
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_9.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/debian_sid_fai.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_6.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_7.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_8.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_8_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/export_metadata.py
  daisy_workflows/image_build/enterprise_linux/rhel_6.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_6_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_sap.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_uefi.wf.json
Labels: approved, lgtm, size/XL

#1288 [Onestep import] change text/flags, cleanup AWS resource
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/gce_onestep_image_import/README.md
  cli_tools/gce_onestep_image_import/main.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_args.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_args_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/test_utils_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/utils.go
  cli_tools/gce_onestep_image_import/onestep_importer/utils_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XL

#1298 Don't install Cloud SDK when importing Debian 8.
  daisy_integration_tests/scripts/post_translate_test.sh
  daisy_workflows/image_import/debian/translate.py
Labels: approved, size/S

#1293 Increase timeout for el_import_dont_use_proxy.wf.json
  daisy_integration_tests/el_import_dont_use_proxy.wf.json
Labels: approved, lgtm, size/XS

#1300 Switch to gcr.io endpoint that doesn't require auth.
  gce_vm_image_import.Dockerfile
Labels: approved, lgtm, size/XS

#1299 Ensure that gcloud shows image import translation logs.
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools/gce_vm_image_import/main.go
Labels: approved, lgtm, size/M

#1301 Switch OVF import tests to a 12hrs schedule
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/XS

#1303 Update osconfig-unstable tests to target zonal endpoints
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/S

#1304 fix comma in config.yaml
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/XS

#1305 e2e_tests: update osconfig-unstable flags
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/XS

#1302 OVF import: use OS ID from OVF descriptor in addition to OS Type
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_loader_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
Labels: approved, size/L
