Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-12, with the labels that each got.

#1399 [ImageExport] allow custom compute service account
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools_tests/e2e/gce_image_import_export/main.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
  cli_tools_tests/e2e/variables.go
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export/image_export.wf.json
  daisy_workflows/export/image_export_ext.wf.json
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/L

#1447 Image import: Renaming to generalize UEFI processor
  cli_tools/gce_vm_image_import/importer/metadata_processor.go
  cli_tools/gce_vm_image_import/importer/metadata_processor_test.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/processor_test.go
  cli_tools/gce_vm_image_import/importer/uefi_processor_test.go
Labels: approved, lgtm, size/L

#1449 Switch existing CentOS 6 based OVF import E2E tests to CentOS 8 as Ce…
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/S

#1445 Correcting GCE PowerShell googet package name
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, lgtm, size/XS

#1450 Fix CentOS 8 OVF import E2E tests. Renaming.
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_tests/go.sum
Labels: approved, lgtm, size/S

#1444 CLI: Add new common logger
  cli_tools/common/utils/logging/logger.go
  cli_tools/common/utils/logging/logger_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/common/utils/storage/storage_client_test.go
  cli_tools/common/utils/storage/tar_gcs_extractor.go
  cli_tools/common/utils/storage/tar_gcs_extractor_test.go
  cli_tools/gce_export/main.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/cli/cli.go
  cli_tools/mocks/mock_logger.go
  proto/go/go.mod
  proto/go/go.sum
  proto/go/pb/inspect.pb.go
  proto/go/pb/output_info.pb.go
  proto/go/pbtesting/assert_matcher.go
  proto/go/pbtesting/gomock_matcher.go
  proto/output_info.proto
  proto/py/compute_image_tools_proto/output_info_pb2.py
  proto/py/compute_image_tools_proto/output_info_pb2.pyi
Labels: approved, lgtm, size/XXL

#1451 Image import: Pick translator based on OS detection when `--os` unspecified
  cli_tools/common/distro/distro.go
  cli_tools/common/distro/distro_test.go
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/common/utils/daisy/daisy_utils_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/disk_inspection_processor.go
  cli_tools/gce_vm_image_import/importer/disk_inspection_processor_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/metadata_processor.go
  cli_tools/gce_vm_image_import/importer/metadata_processor_test.go
  cli_tools/gce_vm_image_import/importer/process_planner.go
  cli_tools/gce_vm_image_import/importer/process_planner_test.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/processor_test.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/windows/translate_windows_8_x86_byol.wf.json
Labels: approved, lgtm, size/XXL

#1454 Import e2e: Only check licenses when provided expected value
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_tests/module/import/inflater_test.go
Labels: approved, lgtm, size/XS

#1457 Use CentOS 7 instead of 8 for OVF import E2E tests.
  cli_tools/go.sum
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  common/gcp/instance.go
Labels: approved, lgtm, size/M

#1452 move centos debian rhel wf and publish json to github
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_10.wf.json
  daisy_workflows/build-publish/debian/debian_9.publish.json
  daisy_workflows/build-publish/debian/debian_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_7_uefi.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7_uefi.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_8_uefi.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8_uefi.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_6.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_6.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_uefi.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_uefi.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_uefi.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_uefi.wf.json
Labels: approved, lgtm, size/XXL

#1459 typo in build wf
  daisy_workflows/build-publish/enterprise_linux/rhel_7_uefi.wf.json
Labels: approved, size/XS

#1458 Import: Remove support for CentOS 6
  cli_tools/common/distro/distro_test.go
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/common/utils/daisy/daisy_utils_test.go
  cli_tools/gce_onestep_image_import/README.md
  cli_tools/gce_ovf_import/README.md
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
  cli_tools/gce_vm_image_import/README.md
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_integration_tests/centos_6_qcow2_translate.wf.json
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json
Labels: approved, lgtm, size/L

#1456 Handle case where ListImages gets permission denied
  daisy/image.go
Labels: approved, lgtm, size/S

#1463 Daisy integ: Remove missing reference to centos 6 test
  daisy_integration_tests/daisy_e2e.test.gotmpl
Labels: approved, lgtm, size/XS

#1466 File inspection: Don't panic when context cancelled
  cli_tools/common/imagefile/qemu_img.go
  cli_tools/common/imagefile/qemu_img_test.go
Labels: approved, lgtm, size/S

#1467 Image import: Take logging.Logger as a dependency
  cli_tools/common/assert/assert.go
  cli_tools/common/assert/assert_test.go
  cli_tools/common/disk/inspect.go
  cli_tools/common/disk/inspect_test.go
  cli_tools/common/utils/files/files.go
  cli_tools/common/utils/files/files_test.go
  cli_tools/common/utils/logging/logger.go
  cli_tools/common/utils/logging/logger_test.go
  cli_tools/common/utils/logging/service/daisy_loggable_test.go
  cli_tools/common/utils/logging/service/outputinfo_loggable.go
  cli_tools/common/utils/logging/service/outputinfo_loggable_test.go
  cli_tools/daisycommon/daisy_worker.go
  cli_tools/gce_vm_image_import/cli/cli.go
  cli_tools/gce_vm_image_import/importer/api_inflater.go
  cli_tools/gce_vm_image_import/importer/api_inflater_test.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools/gce_vm_image_import/importer/metadata_processor.go
  cli_tools/gce_vm_image_import/importer/metadata_processor_test.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/validator.go
  cli_tools/gce_vm_image_import/main.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
  cli_tools_tests/module/import/inflater_test.go
  cli_tools_tests/module/import/logs_test.go
  cli_tools_tests/module/import/pkg_test.go
  cli_tools_tests/module/import/scratch_ownership_test.go
Labels: approved, size/XXL

#1470 When resolving paths, leave absolute paths unchanged.
  cli_tools/common/utils/files/files.go
  cli_tools/common/utils/files/files_test.go
Labels: approved, lgtm, size/S

#1446 OVF Exporter
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/logging/service/literal_loggable.go
  cli_tools/common/utils/logging/service/literal_loggable_test.go
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/common/utils/string/string_utils.go
  cli_tools/common/utils/string/string_utils_test.go
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_ovf_export/README.md
  cli_tools/gce_ovf_export/domain/args.go
  cli_tools/gce_ovf_export/domain/args_test.go
  cli_tools/gce_ovf_export/domain/exported_disks.go
  cli_tools/gce_ovf_export/domain/interfaces.go
  cli_tools/gce_ovf_export/domain/mocks/mock_instance_disks_exporter.go
  cli_tools/gce_ovf_export/domain/mocks/mock_instance_export_cleaner.go
  cli_tools/gce_ovf_export/domain/mocks/mock_instance_export_preparer.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_descriptor_generator.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_export_param_populator.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_export_param_validator.go
  cli_tools/gce_ovf_export/domain/mocks/mock_ovf_manifest_generator.go
  cli_tools/gce_ovf_export/domain/test_data.go
  cli_tools/gce_ovf_export/exporter/exporter.go
  cli_tools/gce_ovf_export/exporter/exporter_test.go
  cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go
  cli_tools/gce_ovf_export/exporter/instance_disks_exporter_test.go
  cli_tools/gce_ovf_export/exporter/instance_export_cleaner.go
  cli_tools/gce_ovf_export/exporter/instance_export_cleaner_test.go
  cli_tools/gce_ovf_export/exporter/instance_export_preparer.go
  cli_tools/gce_ovf_export/exporter/instance_export_preparer_test.go
  cli_tools/gce_ovf_export/exporter/manifest_file_generator.go
  cli_tools/gce_ovf_export/exporter/manifest_file_generator_test.go
  cli_tools/gce_ovf_export/exporter/ovf/cim.go
  cli_tools/gce_ovf_export/exporter/ovf/envelope.go
  cli_tools/gce_ovf_export/exporter/ovf_descriptor_generator.go
  cli_tools/gce_ovf_export/exporter/ovf_descriptor_generator_test.go
  cli_tools/gce_ovf_export/exporter/param_populator.go
  cli_tools/gce_ovf_export/exporter/param_populator_test.go
  cli_tools/gce_ovf_export/exporter/param_validator.go
  cli_tools/gce_ovf_export/exporter/param_validator_test.go
  cli_tools/gce_ovf_export/exporter/steps.go
  cli_tools/gce_ovf_export/exporter/test_utils.go
  cli_tools/gce_ovf_export/main.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/mocks/mock_disk_inspector.go
  cli_tools/mocks/mock_param_populator.go
  cli_tools/mocks/mock_storage_client.go
  cli_tools/test_data/ovf_descriptor.ovf
  daisy_workflows/export/disk_export_ext.wf.json
Labels: approved, size/XXL

#1472 Windows import: Don't disable hibernation.
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, size/XS

#1474 [small] fix import-without-permission e2e err msg
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Labels: approved, lgtm, size/XS

#1460 Add gaohannk to reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#1476 Show a more user friendly error when external IP addresses are prohibited
  cli_tools/gce_vm_image_import/cli/cli.go
Labels: approved, size/S

#1469 Image import: Always run inspection
  cli_tools/common/disk/inspect.go
  cli_tools/common/disk/inspect_test.go
  cli_tools/common/disk/mocks/mock_inspect.go
  cli_tools/gce_ovf_export/exporter/exporter_test.go
  cli_tools/gce_ovf_export/exporter/steps.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/process_planner.go
  cli_tools/gce_vm_image_import/importer/process_planner_test.go
  cli_tools/mocks/mock_disk_inspector.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
  daisy_workflows/image_import/inspection/daisy-shim.sh
  daisy_workflows/image_import/inspection/src/boot_inspect/cli.py
Labels: approved, size/L
