Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-05, with the labels that each got.

#1192 Switch debian import to use the new guest agent.
  daisy_workflows/image_import/debian/translate.py
Labels: size/XS

#1193 Use Python guest agent for Debian 8.
  daisy_workflows/image_import/debian/translate.py
  daisy_workflows/image_import/ubuntu/translate.py
  daisy_workflows/linux_common/utils/common.py
Labels: size/S

#1197 Correct intra-page links in the workflow spec
  docs/daisy-workflow-config-spec.md
Labels: ok-to-test, size/XS

#1198 Retry apt-get update until a package is successfully installed.
  daisy_workflows/linux_common/utils/common.py
Labels: size/S

#1199 [ovf import] fix e2e build folder
  gce_ovf_import_tests.Dockerfile
Labels: size/XS

#1202 [ovf import e2e docker] fix target path of test scripts
  gce_ovf_import_tests.Dockerfile
Labels: size/XS

#1204 Use kaniko-project/executor:debug-edge for builds
  prowjobs_cloudbuild.yaml
Labels: size/S

#1195 daisy: fix image IgnoreLicenseValidationIfForbidden
  daisy/resource.go
  daisy/step_create_images_test.go
  daisy/test_common_test.go
Labels: size/M

#1207 fix cli tools e2e test in gocheck/gobuild/precheck
  cli_tools_e2e_test/gce_image_import_export_tests/go.mod
  cli_tools_e2e_test/gce_image_import_export_tests/go.sum
  cli_tools_e2e_test/gce_image_import_export_tests/main.go
  cli_tools_e2e_test/gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  cli_tools_e2e_test/gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
  cli_tools_e2e_test/gce_ovf_import_tests/go.mod
  cli_tools_e2e_test/gce_ovf_import_tests/main.go
  cli_tools_e2e_test/gce_ovf_import_tests/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_e2e_test/gce_ovf_import_tests/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_e2e_test/go.mod
  test-infra/prowjobs/gobuild/main.sh
  test-infra/prowjobs/gocheck/main.sh
  test-infra/prowjobs/unittests/main.sh
Labels: size/XL

#1208 update cli_e2e_test_tools to use the latest modules
  cli_tools_e2e_test/go.mod
  gce_image_import_export_tests.Dockerfile
  gce_ovf_import_tests.Dockerfile
Labels: size/S

#1206 If translation fails, alert user of what was detected on disk.
  cli_tools/common/distro/distro.go
  cli_tools/common/distro/distro_test.go
  cli_tools/gce_vm_image_import/importer/errors.go
  cli_tools/gce_vm_image_import/importer/importer.go
  daisy_workflows/image_import/debian/translate_debian.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
  daisy_workflows/image_import/freebsd/translate_freebsd.wf.json
  daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
  daisy_workflows/image_import/suse/translate_sles_12_byol.wf.json
  daisy_workflows/image_import/suse/translate_sles_15_byol.wf.json
  daisy_workflows/image_import/suse/translate_sles_sap_12_byol.wf.json
  daisy_workflows/image_import/suse/translate_suse.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
  daisy_workflows/linux_common/utils/diskutils.py
Labels: size/L

#1205 Using v0.22.0 release of kaniko-project/executor
  prowjobs_cloudbuild.yaml
Labels: size/M

#1194 Decouple daisy from import/export logging.
  cli_tools/common/utils/logging/service/daisy_loggable.go
  cli_tools/common/utils/logging/service/daisy_loggable_test.go
  cli_tools/common/utils/logging/service/literal_loggable.go
  cli_tools/common/utils/logging/service/literal_loggable_test.go
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/common/utils/logging/service/logger_test.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_import/main.go
Labels: size/L

#1209 Fix firewall rule for RDP not being added for non-English Windows
  daisy_workflows/image_import/windows/translate.ps1
Labels: size/XS

#1191 Fixed lookup for .ovf descriptor doing a full depth search
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/compute/zone_validator_test.go
  cli_tools/common/utils/param/param_utils_test.go
  cli_tools/common/utils/storage/resource_location_retriever_test.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/common/utils/storage/storage_client_test.go
  cli_tools/common/utils/storage/tar_gcs_extractor_test.go
  cli_tools/gce_ovf_import/gce_utils/machine_type_provider_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_loader.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_loader_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_validator.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_validator_test.go
  cli_tools/gce_vm_image_import/importer/source_test.go
  cli_tools/mocks/mock_bucket_iterator.go
  cli_tools/mocks/mock_bucket_iterator_creator.go
  cli_tools/mocks/mock_compute_client.go
  cli_tools/mocks/mock_compute_service.go
  cli_tools/mocks/mock_http_client.go
  cli_tools/mocks/mock_metadata_gce.go
  cli_tools/mocks/mock_object_deleter.go
  cli_tools/mocks/mock_object_iterator.go
  cli_tools/mocks/mock_object_iterator_creator.go
  cli_tools/mocks/mock_ovf_descriptor_loader.go
  cli_tools/mocks/mock_ovf_descriptor_validator.go
  cli_tools/mocks/mock_reader_closer.go
  cli_tools/mocks/mock_resource_location_retriever.go
  cli_tools/mocks/mock_scratch_bucket_creator.go
  cli_tools/mocks/mock_storage_client.go
  cli_tools/mocks/mock_tar_gcs_extractor.go
  cli_tools/mocks/mock_zone_validator.go
  mocks/go.mod
  mocks/go.sum
Labels: size/XL

#1212 Using v0.22.0 release of kaniko executor in compute-image-tools
  cli_tools_cloudbuild.yaml
Labels: size/S

#1215 Only create workflowLoggable if workflow is non-nil.
  cli_tools/common/utils/logging/service/daisy_loggable.go
  cli_tools/common/utils/logging/service/daisy_loggable_test.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_vm_image_import/main.go
Labels: size/M

#1214 SUSE import: Don't install cloud-init; require iputils.
  daisy_integration_tests/scripts/post_translate_test.sh
  daisy_workflows/image_import/suse/translate.py
Labels: size/M

#1216 prune NGE flag
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_9.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/fai_config/packages/GCE_SPECIFIC_NGE
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py
  daisy_workflows/image_build/enterprise_linux/centos_6.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_7.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_8.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_8_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/rhel_6.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_6_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_sap.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_uefi.wf.json
Labels: size/L

#1210 Provide dependencies to importer.Run
  cli_tools/common/utils/logging/logger.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/param_utils_test.go
  cli_tools/common/utils/param/populator.go
  cli_tools/common/utils/param/populator_test.go
  cli_tools/common/utils/storage/storage_client_test.go
  cli_tools/common/utils/storage/tar_gcs_extractor_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/main.go
Labels: size/XL

#1178 [windows upgrader] initial version
  cli_tools/common/utils/collections/collections_utils.go
  cli_tools/common/utils/collections/collections_utils_test.go
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/common/utils/daisy/daisy_utils_test.go
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/gce_windows_upgrade/main.go
  cli_tools/gce_windows_upgrade/upgrade_script_2008r2_to_2012r2.ps1
  cli_tools/gce_windows_upgrade/upgrader/test_common_test.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader_test.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  cli_tools/gce_windows_upgrade/upgrader/utils_test.go
  cli_tools/gce_windows_upgrade/upgrader/validators.go
  cli_tools/gce_windows_upgrade/upgrader/validators_test.go
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
  cli_tools/gce_windows_upgrade/upgrader/workflows_test.go
  cli_tools/go.mod
  cli_tools/go.sum
Labels: size/XXL

#1220 use hopkiw fork which is updated for NGE
  daisy_workflows/image_build/debian/debian_9.wf.json
Labels: size/XS

#1221 restore disk expand in EL builds
  daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
Labels: size/XS

#1223 build windows-upgrade test docker
  prowjobs_cloudbuild.yaml
Labels: size/XS

#1218 remove presubmits
  test-infra/prow/config.yaml
Labels: size/M

#1224 fix windows_upgrade docker
  cli_tools/gce_windows_upgrade/main.go
  gce_windows_upgrade.Dockerfile
Labels: size/S

#1217 Validate arguments prior to running import.
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/source.go
  cli_tools/gce_vm_image_import/importer/source_test.go
  cli_tools/gce_vm_image_import/main.go
Labels: size/XXL

#1161 Build SQL Server on Windows Server UEFI
  daisy_workflows/image_build/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-standard-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-web-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql_install.ps1
Labels: size/L

#1225 [windows upgrade] use executable path to generate script path
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
Labels: size/XS

#1228 [window supgrade e2e] launch e2e in test infra
  test-infra/prow/config.yaml
Labels: size/S

#1230 EL6 import: Ensure pip is updated.
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: size/XS

#1232 [windows upgrade e2e] fix typo
  test-infra/prow/config.yaml
Labels: lgtm, size/XS

#1165 Avoid import failures by recreating GCEStartup task
  daisy_workflows/image_import/windows/translate.ps1
Labels: size/XS

#1213 Only enable yum-cron for security updates on EL7.
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
Labels: approved, lgtm, size/XS

#1234 add OWNERS file
  OWNERS
Labels: approved, lgtm, size/S

#1236 leave empty machine-id file for autogen
  daisy_workflows/image_build/debian/fai_config/scripts/10-gce-clean
Labels: approved, lgtm, size/XS
