Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-04, with the labels that each got.

#1169 [daisy] Put resource cache inside workflow to avoid race condition
  daisy/common.go
  daisy/compute/compute.go
  daisy/compute/test_client.go
  daisy/disk.go
  daisy/firewall_rule.go
  daisy/forwarding_rule.go
  daisy/image.go
  daisy/instance.go
  daisy/instance_test.go
  daisy/license.go
  daisy/machineimage.go
  daisy/machinetype.go
  daisy/network.go
  daisy/region.go
  daisy/resource.go
  daisy/resource_registry.go
  daisy/step_deprecate_images_test.go
  daisy/subnetwork.go
  daisy/target_instance.go
  daisy/test_common_test.go
  daisy/validate.go
  daisy/workflow.go
  daisy/zone.go
  mocks/mock_compute_client.go
Labels: size/XL

#1171 Fix validate_cloud_logging test.
  daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
  daisy_integration_tests/validate_cloud_logging.wf.json
Labels: size/M

#1173 Increase EL image to 20GB and cleanup old UEFI bits.
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
Labels: size/S

#1172 Remove epel from EL7 builds. It is no longer needed for the base image
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
Labels: size/XS

#1175 Remove gsetup from EL builds.
  daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-uefi-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: size/S

#1176 Put back epel until the go based guest agent is deployed.
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
Labels: size/XS

#1177 [daisy] populate daisy input vars early to support non-string types
  daisy/cli/main.go
  daisy/daisy_test_runner/main.go
  daisy/step_includeworkflow.go
  daisy/step_sub_workflow.go
  daisy/test_data/test.wf.json
  daisy/workflow.go
  daisy/workflow_test.go
Labels: size/M

#1174 [daisy] create "snapshot" step (it's required by windows upgrade proj)
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/go.mod
  cli_tools/go.sum
  daisy/compute/compute.go
  daisy/compute/test_client.go
  daisy/disk.go
  daisy/disk_test.go
  daisy/resource.go
  daisy/snapshot.go
  daisy/snapshot_test.go
  daisy/step.go
  daisy/step_attach_disk_test.go
  daisy/step_create_disks.go
  daisy/step_create_disks_test.go
  daisy/step_create_snapshots.go
  daisy/step_create_snapshots_test.go
  daisy/test_common_test.go
  daisy/workflow.go
  mocks/go.mod
  mocks/go.sum
  mocks/mock_compute_client.go
Labels: size/XL

#1181 Revert "[daisy] populate daisy input vars early to support non-string types"
  daisy/cli/main.go
  daisy/daisy_test_runner/main.go
  daisy/step_includeworkflow.go
  daisy/step_sub_workflow.go
  daisy/test_data/test.wf.json
  daisy/workflow.go
  daisy/workflow_test.go
Labels: size/M

#1170 Don't allow sourceImage to be a GCS path.
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/source.go
  cli_tools/gce_vm_image_import/importer/source_test.go
Labels: size/XL

#1179 [daisy] snapshots: add tests; adjust populate logic
  daisy/disk_test.go
  daisy/snapshot.go
  daisy/snapshot_test.go
  daisy/step_create_snapshots.go
  daisy_integration_tests/step_create_snapshots.wf.json
Labels: size/L

#1183 [daisy] remove param from daysycommon newFromFile
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/go.mod
  cli_tools/go.sum
Labels: size/M

#1184 Update EFI grub configs in EL7 build.
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
Labels: lgtm, size/XS

#1185 Add extended logging for machine image import.
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/main_test.go
Labels: size/L

#1186 [daisy] step_create_snapshot: extract project name from source disk's URI
  daisy/step_create_snapshots.go
Labels: size/XS

#1188 [cli tools] fix dependencies to osconfig
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/import_precheck/check_sha2.go
  cli_tools/import_precheck/main.go
Labels: size/M

#1189 Small refactor: Remove unused kms params.
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/main.go
Labels: size/S
