Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-01, with the labels that each got.

#1061 Move cleanerupper to use beta osconfig
  test-infra/prowjobs/cleanerupper/main.go
Labels: size/XS

#1060 Fix windows translate script to print "Translate complete" when sysprep is run
  daisy_workflows/image_import/windows/translate.ps1
Labels: size/S

#1059 Make image import translate step use Daisy Workflow default timeout
  daisy/workflow.go
  daisy_workflows/image_import/debian/translate_debian.wf.json
  daisy_workflows/image_import/debian/translate_debian_8.wf.json
  daisy_workflows/image_import/debian/translate_debian_9.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_6.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_centos_7.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_7_licensed.wf.json
  daisy_workflows/image_import/freebsd/translate_freebsd.wf.json
  daisy_workflows/image_import/import_from_image.wf.json
  daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
  daisy_workflows/image_import/suse/translate_sles_12_byol.wf.json
  daisy_workflows/image_import/suse/translate_sles_15_byol.wf.json
  daisy_workflows/image_import/suse/translate_suse.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1404.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1604.wf.json
  daisy_workflows/image_import/ubuntu/translate_ubuntu_1804.wf.json
  daisy_workflows/image_import/windows/translate_windows_10_x64_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_10_x86_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2008_r2.wf.json
  daisy_workflows/image_import/windows/translate_windows_2008_r2_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012_r2.wf.json
  daisy_workflows/image_import/windows/translate_windows_2012_r2_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2016.wf.json
  daisy_workflows/image_import/windows/translate_windows_2016_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_2019.wf.json
  daisy_workflows/image_import/windows/translate_windows_2019_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_7_x64_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_7_x86_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_8_x64_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_8_x86_byol.wf.json
  daisy_workflows/image_import/windows/translate_windows_wf.json
  daisy_workflows/image_import/windows/translate_windows_x86_wf.json
Labels: size/M

#1065 fix network/subnet e2e: url typo
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
Labels: size/S

#1067 Test cleanup: Delete exported disk image if export is successful.
  daisy_integration_tests/image_export_vmdk_given_size.subwf.json
Labels: size/S

#1066 Improve error message for failed EL translation.
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: size/M

#1069 [ovf e2e] fix dup ovf test name
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
Labels: size/S

#1070 Added support for machine images to Daisy
  daisy/compute/compute.go
  daisy/compute/compute_test.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/machineimage.go
  daisy/machineimage_test.go
  daisy/resource.go
  daisy/resource_registry_test.go
  daisy/step.go
  daisy/step_create_machine_images.go
  daisy/step_create_machine_images_test.go
  daisy/step_delete_resources.go
  daisy/step_delete_resources_test.go
  daisy/step_test.go
  daisy/test_common_test.go
  daisy/test_data/test.wf.json
  daisy/workflow.go
  daisy/workflow_test.go
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/step_create_machine_images.wf.json
  docs/daisy-workflow-config-spec.md
  mocks/mock_compute_client.go
Labels: size/XL

#1071 Added support for machine images to cleanerupper
  test-infra/prowjobs/cleanerupper/main.go
Labels: size/M

#1072 Move daisy to use go modules
  daisy/go.mod
  daisy/go.sum
Labels: size/L

#1068 Image import: Support OVAs where enclosed vmdk has spaces.
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/image_import_and_translate_ova_with_spaces_in_vmdk_filename.wf.json
  daisy_workflows/image_import/import_image.sh
Labels: size/M

#1075 prowjobs: reorganize cloudbuild
  cli_tools/daisy_test_runner/Dockerfile
  cli_tools/daisy_test_runner/main.sh
  gce_image_import_export_tests.Dockerfile
  gce_ovf_import_tests.Dockerfile
  prowjobs_cloudbuild.yaml
  test-infra/prowjobs/cleanerupper/Dockerfile
  test-infra/prowjobs/cleanerupper/go.mod
  test-infra/prowjobs/cleanerupper/go.sum
  test-infra/prowjobs/cloudbuild.yaml
  test-infra/prowjobs/flake8/Dockerfile
  test-infra/prowjobs/gobuild/Dockerfile
  test-infra/prowjobs/gocheck/Dockerfile
  test-infra/prowjobs/unittests/Dockerfile
  test-infra/prowjobs/wrapper/Dockerfile
  test-infra/prowjobs/wrapper/go.mod
  test-infra/prowjobs/wrapper/go.sum
  test-infra/prowjobs/wrapper/withgcloud.Dockerfile
Labels: size/XL

#1076 Fix golint
  prowjobs_cloudbuild.yaml
Labels: size/XS

#1073 [ovf import / daisy] avoid undesired deletion
  daisy/image.go
  daisy/resource.go
  daisy/resource_registry.go
  daisy/resource_registry_test.go
  daisy/step_create_disks.go
  daisy/step_create_firewall_rule.go
  daisy/step_create_forwarding_rule.go
  daisy/step_create_images.go
  daisy/step_create_instances.go
  daisy/step_create_machine_images.go
  daisy/step_create_networks.go
  daisy/step_create_subnetworks.go
  daisy/step_create_target_instance.go
Labels: size/L

#1077 fix gce_image_import_export_test docker permission
  gce_image_import_export_tests.Dockerfile
Labels: size/S

#1074 Image import: Add hint for when VMDK decoding fails.
  daisy_workflows/image_import/import_image.sh
Labels: size/S

#1062 Python rhel8
  daisy_workflows/image_build/enterprise_linux/kickstart/el6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: lgtm, size/S

#1083 More modules
  go/e2e_test_utils/go.mod
  go/e2e_test_utils/go.sum
  mocks/go.mod
  mocks/go.sum
Labels: size/L

#1078 Added machine image import to OVF importer
  cli_tools/common/utils/storage/storage_client.go
  cli_tools/gce_ovf_import/README.md
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/test_data/test_import_ovf_to_instance.wf.json
  cli_tools/test_data/test_import_ovf_to_machine_image.wf.json
  daisy_workflows/ovf_import/import_ovf_to_instance.wf.json
  daisy_workflows/ovf_import/import_ovf_to_machine_image.wf.json
Labels: size/XL

#1086 OVF import: validate hostname flag
  cli_tools/common/utils/validation/validation_utils.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params_validator_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
Labels: size/M

#1079 [export ssd quota] allow fallback to pd-standard for source disk
  daisy_workflows/export/image_export.wf.json
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/XS

#1087 Fix daisy validate cloud logging test
  daisy_integration_tests/scripts/run_daisy_and_check_logs.sh
Labels: size/S

#1089 Added missing default timeout for import from image workflow
  daisy_workflows/image_import/import_from_image.wf.json
Labels: size/XS

#1088 Add missing nge flag for centos 8 uefi.
  daisy_workflows/image_build/enterprise_linux/centos_8_uefi.wf.json
Labels: size/XS

#1081 Better hint for default resource
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/go.mod
  cli_tools/go.sum
  daisy/error.go
  daisy/error_test.go
  daisy/resource_registry.go
  daisy/step.go
  daisy/step_delete_resources.go
Labels: size/L

#1082 Add support for importing CentOS-8.
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  daisy_integration_tests/centos_8_translate.wf.json
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/scripts/post_translate_test.sh
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json
Labels: size/L

#1090 Improve error message when 'cloud-init init' fails.
  daisy_workflows/image_import/ubuntu/translate.py
Labels: size/S

#1091 Better hint for missed default network: add supporting for image export/instance import
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/go.mod
  cli_tools/go.sum
Labels: size/M

#1094 Fix flakiness for image storage location retrieving
  cli_tools/common/utils/storage/resource_location_retriever.go
  cli_tools/common/utils/storage/resource_location_retriever_test.go
Labels: size/M

#1097 Clarify how to import a disk image that is contained within a gzip compressed file.
  cli_tools/gce_vm_image_import/importer/importer.go
Labels: size/XS

#1093 Add support for importing RHEL8.
  cli_tools/common/utils/daisy/daisy_utils.go
  daisy_integration_tests/rhel_8_translate.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
Labels: size/L

#1092 [daisy][log] allow nested DError anonymized msg
  daisy/error.go
  daisy/error_test.go
  daisy/go.mod
  daisy/go.sum
  daisy/step.go
Labels: size/M

#1098 Allow post-translate test to wait until cloud-init finishes its startup work.
  daisy_integration_tests/scripts/post_translate_test.sh
Labels: size/S

#1095 Rephrase RHEL byol as byos and add RHEL 8.
  daisy_workflows/image_build/enterprise_linux/README.md
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/build_installer_uefi.py
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-byos-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/rhel_6_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos.wf.json
Labels: size/L

#1096 OVF instance import E2E tests on wrapper and gcloud CLI
  gce_ovf_import_tests.Dockerfile
  gce_ovf_import_tests/compute/instance.go
  gce_ovf_import_tests/go.mod
  gce_ovf_import_tests/main.go
  gce_ovf_import_tests/test_suites/ovf_import_test_suite.go
  gce_ovf_import_tests/test_suites/ovf_instance_import/ovf_import_test_suite.go
  gce_ovf_import_tests/test_suites/test_suite_utils.go
Labels: size/XXL

#1100 Fall-back to pd-standard for disks used in OVF import if quota exceeded
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater_test.go
Labels: size/S

#1101 test_suite_utils.go refactoring to share between image and OVF e2e tests
  gce_image_import_export_tests/go.mod
  gce_image_import_export_tests/go.sum
  gce_image_import_export_tests/test_suites/export/image_export_test_suite.go
  gce_image_import_export_tests/test_suites/import/image_import_test_suite.go
  gce_ovf_import_tests/go.mod
  gce_ovf_import_tests/test_suites/ovf_instance_import/ovf_import_test_suite.go
  gce_ovf_import_tests/test_suites/test_suite_utils.go
  go/e2e_test_utils/cli_tools/cli_tools_test_utils.go
Labels: size/XL

#1102 Support importing RHEL 8 BYOL.
  cli_tools/common/utils/daisy/daisy_utils.go
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json
Labels: size/M

#1104 refer to e2e_test_utils directly, no go mod replace
  gce_image_import_export_tests/go.mod
  gce_ovf_import_tests/go.mod
Labels: size/XS

#1103 Fix new OVF gcloud E2E tests
  gce_ovf_import_tests.Dockerfile
Labels: size/XS

#1106 Remove SECURE_BOOT flag from uefi builds.
  daisy_workflows/image_build/enterprise_linux/centos_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_8_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_7_uefi.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1809-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1909-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers-uefi.wf.json
Labels: size/S

#1107 Fixed OVF import e2e tests failing
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_import_params/ovf_import_params.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  gce_ovf_import_tests/test_suites/ovf_instance_import/ovf_import_test_suite.go
Labels: size/S

#1108 SLES 12.x image import fix, not only 12.5
  daisy_workflows/image_import/suse/translate.py
Labels: size/XS
