Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2020-09, with the labels that each got.

#1337 Deploying image import wrappers to Artifact registry fixe
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/XS

#1339 DaisyCompute client: support CreatDisk from beta api
  daisy/compute/compute.go
  daisy/workflow_test.go
Labels: approved, size/M

#1340 new VMDK API adoption: shadow test alpha -> beta
  cli_tools/gce_vm_image_import/importer/api_inflater.go
  cli_tools/gce_vm_image_import/importer/api_inflater_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/mocks/mock_compute_client.go
Labels: approved, lgtm, size/L

#1342 Split publishing to different repos in separate steps. Upgrade kaniko executor version.
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/S

#1341 Add tests for EL 7.8 and EL 8.2
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, lgtm, size/S

#1343 Use a non-GUI image to avoid flaky RHEL8 test.
  daisy_integration_tests/rhel_8_translate.wf.json
Labels: approved, lgtm, size/XS

#1344 Increase verbosity of disk resizing.
  daisy_workflows/image_import/import_image.sh
Labels: approved, lgtm, size/XS

#1345 Introduced failureMatches for OVF import and Windows upgrade E2E tests
  cli_tools_e2e_test/common/compute/instance.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_e2e_test/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
Labels: approved, lgtm, size/M

#1346 GMI import: stop imported instances before creating GMIs
  daisy_workflows/ovf_import/import_ovf_to_machine_image.wf.json
Labels: approved, lgtm, size/XS

#1348 Fix Debian 9 build.
  daisy_workflows/image_build/debian/build.py
Labels: approved, lgtm, size/XS

#1347 Update 3-disk Ubuntu OVF import test verification script
  cli_tools_e2e_test/gce_ovf_import/scripts/ovf_import_test_ubuntu_3_disks.sh
Labels: approved, lgtm, size/L

#1349 Update Windows 2-disk OVF import E2E test verification script
  cli_tools_e2e_test/gce_ovf_import/scripts/ovf_import_test_windows_two_disks.ps1
Labels: approved, lgtm, size/M

#1350 Update multi-regional mapping in import/export wrappers
  cli_tools/common/utils/storage/resource_location_retriever.go
Labels: approved, lgtm, size/XS

#1351 Don't check for OS config in OVF import E2E test verification
  cli_tools_e2e_test/common/compute/instance.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/M

#1353 Import unit tests: remove testdata symlink
  cli_tools/gce_vm_image_import/importer/api_inflater_test.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools/gce_vm_image_import/importer/testdata/image_import
Labels: approved, lgtm, size/S

#1355 Deploy image import wrappers to all regions in the Americas
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/M

#1338 [UEFI-compatible] auto detect & tag UEFI compatible
  cli_tools/common/disk/inspect.go
  cli_tools/common/utils/logging/service/daisy_loggable.go
  cli_tools/common/utils/logging/service/literal_loggable.go
  cli_tools/common/utils/logging/service/literal_loggable_test.go
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/gce_vm_image_import/importer/api_inflater.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor.go
  cli_tools/gce_vm_image_import/importer/data_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/disk_inspection_processor.go
  cli_tools/gce_vm_image_import/importer/disk_inspection_processor_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/importer_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/processor_test.go
  cli_tools/gce_vm_image_import/importer/uefi_processor.go
  cli_tools/gce_vm_image_import/importer/uefi_processor_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools_e2e_test/common/assert/assert.go
  cli_tools_e2e_test/common/utils/utils.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_e2e_test/go.mod
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
  daisy_workflows/image_import/inspection/src/boot_inspect/cli.py
  go/e2e_test_utils/go.sum
Labels: approved, size/XXL

#1358 mute has_efi_partition
  cli_tools/common/disk/inspect.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, size/M

#1359 Open source Debian 10 worker image build.
  daisy_workflows/image_build/debian/build.py
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_10_worker.sh
  daisy_workflows/image_build/debian/debian_10_worker.wf.json
  daisy_workflows/image_build/debian/debian_9.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/debian_sid_fai.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux_uefi.wf.json
Labels: approved, lgtm, size/L

#1357 Added gcloud-ga-latest/wrapper-release E2E tests
  cli_tools_e2e_test/common/utils/utils.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/export/image_export_test_suite.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_e2e_test/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_e2e_test/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_e2e_test/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
Labels: approved, lgtm, size/L

#1354 Integration test for boot-inspect
  cli_tools/common/disk/inspect.go
  cli_tools_e2e_test/diskinspect/README.md
  cli_tools_e2e_test/diskinspect/disk_inspect_test.go
  cli_tools_e2e_test/diskinspect/go.mod
  cli_tools_e2e_test/diskinspect/go.sum
  cli_tools_e2e_test/go.sum
  daisy_workflows/image_import/inspection/src/boot_inspect/cli.py
Labels: approved, size/XXL

#1360 Deploy image import wrapper Docker image to Artifact registry repos in Europe
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/M

#1361 Deploy image import wrapper Docker image to Artifact registry repos in Asia/Australia
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/M

#1363 Fixed GcloudGaLatestWrapperRelease E2E tests not running
  cli_tools_e2e_test/common/utils/utils.go
Labels: approved, lgtm, size/XS

#1364 EL import: Don't fail when unexpected directory in /lib/modules
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, size/M

#1367 Image import: Disable shadow VMDK inflation.
  cli_tools/gce_vm_image_import/importer/api_inflater_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
Labels: approved, lgtm, size/S

#1366 Image import: Disable shadow VMDK inflation.
  cli_tools/gce_vm_image_import/importer/api_inflater_test.go
  cli_tools/gce_vm_image_import/importer/inflater.go
Labels: approved, lgtm, size/S

#1370 Check if scratch bucket provided as a flag is in the same project
  cli_tools/common/domain/interfaces.go
  cli_tools/common/utils/flags/key_value_flag_test.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/populator_test.go
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
  cli_tools/mocks/mock_scratch_bucket_creator.go
Labels: approved, lgtm, size/L

#1373 Remove resources when bucket owned by different project
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/populator_test.go
  cli_tools/gce_vm_image_import/main.go
Labels: approved, lgtm, size/L

#1377 Image import: Only run inspection when -inspect flag is specified
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/processor_test.go
Labels: approved, lgtm, size/XS

#1369 Image import: e2e tests to validate rollout of new SLES targets to gcloud
  cli_tools_e2e_test/gce_image_import_export/test_suites/import/cli_tests.go
Labels: approved, lgtm, size/S

#1384 Building import wrapper into all repos in a single step
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/M
