Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-09, with the labels that each got.

#1740 Import precheck: Refactor to allow mocking
  cli_tools/import_precheck/check.go
  cli_tools/import_precheck/check_powershell.go
  cli_tools/import_precheck/check_sha2.go
  cli_tools/import_precheck/check_ssh.go
  cli_tools/import_precheck/common.go
  cli_tools/import_precheck/main.go
  cli_tools/import_precheck/precheck/check.go
  cli_tools/import_precheck/precheck/check_disks_linux.go
  cli_tools/import_precheck/precheck/check_disks_linux_test.go
  cli_tools/import_precheck/precheck/check_disks_windows.go
  cli_tools/import_precheck/precheck/check_osversion.go
  cli_tools/import_precheck/precheck/check_osversion_test.go
  cli_tools/import_precheck/precheck/check_powershell.go
  cli_tools/import_precheck/precheck/check_sha2.go
  cli_tools/import_precheck/precheck/check_ssh.go
  cli_tools/import_precheck/precheck/common.go
  cli_tools/import_precheck/precheck/report.go
  cli_tools/import_precheck/precheck/testdata/lsblk-efi.json
  cli_tools/import_precheck/precheck/testdata/lsblk-multi-disk-lvm.json
  cli_tools/import_precheck/precheck/testdata/lsblk-one-partition.json
  cli_tools/import_precheck/precheck/testdata/lsblk-single-disk-lvm.json
  cli_tools/import_precheck/precheck/user_linux.go
  cli_tools/import_precheck/precheck/user_windows.go
  cli_tools/import_precheck/report.go
  cli_tools/import_precheck/user_linux.go
  cli_tools/import_precheck/user_windows.go
Labels: size/XL, lgtm, approved

#1739 Image import: Support Rocky Linux 8
  cli_tools/common/distro/distro.go
  cli_tools/common/distro/distro_test.go
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/enterprise_linux/translate_rocky_8.wf.json
  daisy_workflows/image_import/inspection/src/boot_inspect/inspection.py
  daisy_workflows/image_import/inspection/tests/test-data/images/gcp-image-rocky-8-v20210817.yaml
  proto/go/pb/inspect.pb.go
  proto/go/pb/output_info.pb.go
  proto/inspect.proto
  proto/py/compute_image_tools_proto/inspect_pb2.py
  proto/py/compute_image_tools_proto/inspect_pb2.pyi
  proto/py/compute_image_tools_proto/output_info_pb2.py
  proto/py/compute_image_tools_proto/output_info_pb2.pyi
Labels: size/XL, lgtm, approved

#1742 Don't install the auto updater package on windows import
  daisy_workflows/image_import/windows/translate.ps1
Labels: size/XS, lgtm, approved

#1750 EL6 import: Don't install guest packages
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: size/M, lgtm, approved

#1748 fix `/etc/netplan` clean up issue for Ubuntu 18+ which interrupts the import process
  daisy_workflows/image_import/ubuntu/translate.py
Labels: size/XS, lgtm, approved

#1744 Add workflow for Windows Server 2022 BYOL
  daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-uefi-byol.wf.json
Labels: size/L, lgtm

#1752 Revert "EL6 import: Don't install guest packages (#1750)"
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: size/M, lgtm, approved

#1743 Import precheck: Support disk checking back to EL7
  cli_tools/common/mount/inspector.go
  cli_tools/common/mount/inspector_test.go
  cli_tools/common/mount/mock_mount_inspector.go
  cli_tools/common/utils/shell/executor.go
  cli_tools/import_precheck/main.go
  cli_tools/import_precheck/precheck/check_disks_linux.go
  cli_tools/import_precheck/precheck/check_disks_linux_test.go
  cli_tools/import_precheck/precheck/check_disks_windows.go
  cli_tools/import_precheck/precheck/check_osversion.go
  cli_tools/import_precheck/precheck/check_osversion_test.go
  cli_tools/import_precheck/precheck/check_powershell.go
  cli_tools/import_precheck/precheck/check_sha2.go
  cli_tools/import_precheck/precheck/check_ssh.go
  cli_tools/import_precheck/precheck/report.go
  cli_tools/import_precheck/precheck/testdata/lsblk-efi.json
  cli_tools/import_precheck/precheck/testdata/lsblk-multi-disk-lvm.json
  cli_tools/import_precheck/precheck/testdata/lsblk-one-partition.json
  cli_tools/import_precheck/precheck/testdata/lsblk-single-disk-lvm.json
  cli_tools/mocks/mock_shell_exececutor.go
Labels: size/XXL, lgtm, approved

#1753 EL6 import: Enable rsyslog and add e2e test
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: size/XS, lgtm, approved

#1754 Image Import: Use daisy worker
  cli_tools/common/assert/assert.go
  cli_tools/common/assert/assert_test.go
  cli_tools/common/disk/inspect.go
  cli_tools/common/image/importer/api_inflater.go
  cli_tools/common/image/importer/bootable_disk_processor.go
  cli_tools/common/image/importer/bootable_disk_processor_test.go
  cli_tools/common/image/importer/daisy_inflater.go
  cli_tools/common/image/importer/daisy_inflater_test.go
  cli_tools/common/image/importer/inflater_test.go
  cli_tools/common/image/importer/request.go
  cli_tools/common/imagefile/qemu_img_test.go
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/common/utils/daisyutils/daisy_worker.go
  cli_tools/common/utils/daisyutils/daisy_worker_test.go
  cli_tools/common/utils/daisyutils/daisy_worker_testing.go
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/domain/ovf_import_params_test.go
  cli_tools/gce_ovf_import/multi_image_importer/request_builder.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/mocks/mock_daisy_worker.go
Labels: size/XL, lgtm, approved

#1756 fix cleanerupper deletion of OS policy assignments
  test-infra/prowjobs/cleanerupper/main.go
Labels: size/XS, lgtm, approved

#1758 [import] respect custom network/subnet in shadow test workflow
  cli_tools/common/image/importer/api_inflater.go
Labels: size/XS, approved
