Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-01, with the labels that each got.

#1478 Disk inspection: Honor no-external-ip
  cli_tools/common/disk/inspect.go
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/daisycommon/daisy_utils_test.go
  cli_tools/daisycommon/daisy_worker.go
  cli_tools/gce_ovf_export/domain/args.go
  cli_tools/gce_ovf_export/domain/args_test.go
  cli_tools/gce_ovf_export/exporter/exporter.go
  cli_tools/gce_ovf_export/exporter/steps.go
  cli_tools/gce_vm_image_import/importer/api_inflater.go
  cli_tools/gce_vm_image_import/importer/args.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: approved, lgtm, size/XL

#1453 Updating the GCE Windows Build
  daisy_workflows/image_build/windows/README.md
  daisy_workflows/image_build/windows/bootstrap_install.ps1
  daisy_workflows/image_build/windows/components/Autounattend-template.xml
  daisy_workflows/image_build/windows/components/SetupComplete.cmd
  daisy_workflows/image_build/windows/post_install.ps1
  daisy_workflows/image_build/windows/windows-build.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-bios-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-bios-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-bios-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-bios-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
Labels: approved, lgtm, size/XXL

#1455 Configuring WinRM on Windows clients
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, lgtm, size/XS

#1482 Limiting hibernate to Win7/2008R2 SP1 and above.
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, lgtm, size/S

#1484 Reflect deprecation of SECURE_BOOT
  cli_tools/common/utils/string/string_utils_test.go
  daisy/common_test.go
Labels: approved, lgtm, size/S

#1481 Image import: Modularize arguments
  cli_tools/common/utils/validation/validation_utils.go
  cli_tools/common/utils/validation/validation_utils_test.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_vm_image_import/cli/args_test.go
  cli_tools/gce_vm_image_import/cli/cli.go
  cli_tools/gce_vm_image_import/importer/api_inflater.go
  cli_tools/gce_vm_image_import/importer/api_inflater_test.go
  cli_tools/gce_vm_image_import/importer/args_test.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor.go
  cli_tools/gce_vm_image_import/importer/bootable_disk_processor_test.go
  cli_tools/gce_vm_image_import/importer/importer.go
  cli_tools/gce_vm_image_import/importer/inflater.go
  cli_tools/gce_vm_image_import/importer/inflater_test.go
  cli_tools/gce_vm_image_import/importer/process_planner.go
  cli_tools/gce_vm_image_import/importer/process_planner_test.go
  cli_tools/gce_vm_image_import/importer/processor.go
  cli_tools/gce_vm_image_import/importer/processor_test.go
  cli_tools/gce_vm_image_import/importer/request.go
  cli_tools/gce_vm_image_import/importer/request_test.go
  cli_tools/gce_vm_image_import/importer/validator.go
  cli_tools/gce_vm_image_import/importer/validator_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools_tests/module/import/inflater_test.go
  cli_tools_tests/module/import/scratch_ownership_test.go
Labels: approved, lgtm, size/XXL

#1483 Changing hibernation management to use direct registry modification
  daisy_integration_tests/scripts/post_translate_test.ps1
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, lgtm, size/S

#1487 Improving hibernation integration test
  daisy_integration_tests/scripts/post_translate_test.ps1
Labels: approved, lgtm, size/S

#1488 Updating hibernation registry check
  daisy_integration_tests/scripts/post_translate_test.ps1
Labels: approved, lgtm, size/XS

#1489 Import module: Allow network to be empty
  cli_tools/gce_vm_image_import/importer/request.go
  cli_tools/gce_vm_image_import/importer/request_test.go
Labels: approved, lgtm, size/S

#1490 Update Debian cloud build tools commit.
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
Labels: approved, lgtm, size/XS

#1492 Fix centos-stream-8 path.
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.wf.json
Labels: approved, lgtm, size/XS

#1493 Add libatomic to RHEL for SAP build.
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-sap-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-8-sap-post.cfg
Labels: approved, lgtm, size/XS

#1480 Devcluster image build
  daisy_workflows/build-publish/debian/debian_10_worker.publish.json
  daisy_workflows/build-publish/debian/debian_10_worker.wf.json
  daisy_workflows/build-publish/linux_dev/centos_7_dev.wf.json
  daisy_workflows/build-publish/linux_dev/centos_8_dev.wf.json
  daisy_workflows/build-publish/linux_dev/centos_dev.sh
  daisy_workflows/build-publish/linux_dev/debian_10_dev.wf.json
  daisy_workflows/build-publish/linux_dev/debian_9_dev.wf.json
  daisy_workflows/build-publish/linux_dev/debian_dev.sh
  daisy_workflows/build-publish/linux_dev/debian_staging.publish.json
  daisy_workflows/build-publish/linux_dev/development.json
  daisy_workflows/build-publish/linux_dev/ubuntu_1604_dev.wf.json
  daisy_workflows/build-publish/linux_dev/ubuntu_1804_dev.wf.json
Labels: approved, lgtm, size/L

#1494 Image import: Add e2e test case for VHD
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, lgtm, size/XS

#1485 Bare metal image
  daisy_workflows/build-publish/bare_metal/rhel_7.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_7.wf.json
  daisy_workflows/build-publish/bare_metal/rhel_8.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_8.wf.json
  daisy_workflows/image_build/bare_metal/bare_metal_image_preparer.sh
  daisy_workflows/image_build/bare_metal/bare_metal_linux.wf.json
Labels: approved, lgtm, size/L

#1495 Remove unnecessary MTU settings.
  daisy_workflows/image_build/enterprise_linux/kickstart/centos-7-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos-8-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos-stream-8-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-8-options.cfg
Labels: approved, lgtm, size/S

#1486 Updated READMEs for image importer/exporter and OVF importer.
  cli_tools/gce_ovf_import/README.md
  cli_tools/gce_vm_image_export/README.md
  cli_tools/gce_vm_image_import/README.md
  cli_tools/gce_vm_image_import/cli/args.go
Labels: approved, lgtm, size/M

#1498 RHEL 8 boot for bare metal.
  daisy_workflows/image_build/bare_metal/bare_metal_image_preparer.sh
Labels: approved, lgtm, size/S

#1499 Don't set cmdline args since they are pulled from the running system.
  daisy_workflows/build-publish/bare_metal/rhel_7.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_8.publish.json
  daisy_workflows/image_build/bare_metal/bare_metal_image_preparer.sh
Labels: approved, lgtm, size/XS

#1496 Add disk space warning for Windows imports
  daisy_workflows/image_import/windows/translate.ps1
  daisy_workflows/image_import/windows/translate_bootstrap.ps1
Labels: approved, lgtm, size/M

#1500 Add RHEL BYOS workflows.
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.wf.json
Labels: approved, lgtm, size/L

#1501 Fix comment.
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
Labels: approved, lgtm, size/XS

#1502 Fixing powershell syntax issues
  daisy_workflows/image_import/windows/translate.ps1
  daisy_workflows/image_import/windows/translate_bootstrap.ps1
Labels: approved, lgtm, size/S

#1505 VPC image format E2E test
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_integration_tests/README.md
Labels: approved, lgtm, size/XS

#1504 OVF export E2E tests
  cli_tools_tests/e2e/gce_ovf_export/main.go
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
  cli_tools_tests/go.sum
  gce_ovf_export_tests.Dockerfile
  go/e2e_test_utils/go.sum
  go/e2e_test_utils/launcher.go
  prowjobs_cloudbuild.yaml
  test-infra/prow/config.yaml
  test-infra/prowjobs/cleanerupper/main.go
Labels: approved, size/XL

#1507 add gvnic feature
  daisy_workflows/build-publish/bare_metal/rhel_7.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_8.publish.json
Labels: approved, lgtm, size/XS

#1508 Increasing Cloud Build jobs timeout from 30m to 1hr
  cli_tools_cloudbuild.yaml
  prowjobs_cloudbuild.yaml
Labels: approved, lgtm, size/XS

#1509 OVF import: Specify default timeout
  cli_tools/gce_ovf_import/main.go
Labels: approved, lgtm, size/XS
