Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-02, with the labels that each got.

#1511 Adding restart in the startup scripts that is cancelled by translate.ps1
  daisy_workflows/image_import/windows/run_startup_scripts.cmd
  daisy_workflows/image_import/windows/run_startup_scripts_x86.cmd
  daisy_workflows/image_import/windows/translate.ps1
Labels: approved, lgtm, size/S

#1506 CLI logging: Trap panics in application code
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/common/utils/logging/service/logger_test.go
Labels: approved, lgtm, size/M

#1513 [vmdk api adoption] siwtch to GA shadow test
  cli_tools/common/image/importer/api_inflater.go
  cli_tools/common/image/importer/api_inflater_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/import_precheck/check_sha2.go
Labels: approved, lgtm, size/L

#1512 Machine image import: Use import module for alpha and beta
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  daisy_workflows/ovf_import/create_gmi.wf.json
Labels: approved, lgtm, size/L

#1515 GMI import worker: Use alphabetic prefix on data disks
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
Labels: approved, lgtm, size/S

#1517 [importer] build onestep importer
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/M

#1519 Build OVF exporter (gce_ovf_export) Docker image
  cli_tools_cloudbuild.yaml
  gce_ovf_export.Dockerfile
Labels: approved, lgtm, size/M

#1448 Add SerialPortToLog parameter to InstanceBase
  daisy/compute/compute.go
  daisy/instance.go
  daisy/instance_test.go
  daisy/step_create_instances.go
Labels: approved, lgtm, needs-ok-to-test, size/M

#1520 add bare-metal-dev wf and script
  daisy_workflows/build-publish/linux_dev/rhel_7_metal_dev.wf.json
  daisy_workflows/build-publish/linux_dev/rhel_8_metal_dev.wf.json
  daisy_workflows/image_build/bare_metal/bare_metal_image_preparer.sh
  daisy_workflows/image_build/bare_metal/bare_metal_linux.wf.json
Labels: approved, lgtm, size/M

#1518 Precheck tool: Use common OS list
  cli_tools/common/distro/distro.go
  cli_tools/common/distro/distro_test.go
  cli_tools/import_precheck/check_osversion.go
  cli_tools/import_precheck/check_osversion_test.go
  cli_tools/import_precheck/check_sha2.go
  cli_tools/import_precheck/main.go
Labels: approved, lgtm, size/L

#1503 Disable systemd ssh-keygen service on EL7.
  daisy_workflows/image_build/enterprise_linux/kickstart/centos-7-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-options.cfg
Labels: approved, lgtm, size/XS

#1521 Image import: Increase debug support when translation fails
  daisy_workflows/export_metadata/export_metadata.wf.json
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_import/debian/translate.py
  daisy_workflows/image_import/debian/translate_debian.wf.json
  daisy_workflows/image_import/enterprise_linux/translate.py
  daisy_workflows/image_import/enterprise_linux/translate_el.wf.json
  daisy_workflows/image_import/freebsd/translate_freebsd.wf.json
  daisy_workflows/image_import/ubuntu/translate.py
  daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
  daisy_workflows/linux_common/tests/test_guestfsprocess.py
  daisy_workflows/linux_common/utils/common.py
  daisy_workflows/linux_common/utils/guestfsprocess.py
Labels: approved, lgtm, size/L

#1522 [minor] rename onestep import log prefix
  cli_tools/gce_onestep_image_import/main.go
Labels: approved, lgtm, size/XS

#1523 add bare-metal dev publish wf
  daisy_workflows/build-publish/bare_metal/rhel_7.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_8.publish.json
  daisy_workflows/build-publish/linux_dev/rhel_7_metal_dev.publish.json
  daisy_workflows/build-publish/linux_dev/rhel_8_metal_dev.publish.json
Labels: approved, lgtm, size/M

#1524 Enable onestep-import gcloud e2e
  cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
Labels: approved, lgtm, size/XS

#1514 [vmdk api adoption] Switch from shadow-test mode to fallback mode
  cli_tools/common/image/importer/api_inflater.go
  cli_tools/common/image/importer/api_inflater_test.go
  cli_tools/common/image/importer/daisy_inflater.go
  cli_tools/common/image/importer/daisy_inflater_test.go
  cli_tools/common/image/importer/inflater.go
  cli_tools/common/image/importer/inflater_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Labels: approved, size/XXL

#1525 Ubuntu 18.04+ import: Add /snap/bin to service's path
  daisy_workflows/image_import/ubuntu/translate.py
Labels: approved, size/M

#1526 [e2e fix] adjust err msg for disabled-account-service testcase
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Labels: approved, lgtm, size/XS

#1529 Add EPEL for RHEL 8 and extra net dev packages.
  daisy_workflows/image_build/bare_metal/bare_metal_image_preparer.sh
Labels: approved, lgtm, size/XS

#1531 Add time var to publish workflows.
  daisy_workflows/build-publish/linux_dev/rhel_7_metal_dev.publish.json
  daisy_workflows/build-publish/linux_dev/rhel_8_metal_dev.publish.json
Labels: approved, lgtm, size/S

#1527 Add missing variables to Windows image build workflow
  daisy_workflows/image_build/windows/windows-server-2016-dc-bios-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-bios-byol.wf.json
Labels: lgtm, size/S

#1532 Run go mod tidy on cli_tools_tests/go.mod
  cli_tools_tests/go.mod
  cli_tools_tests/go.sum
Labels: approved, lgtm, size/L

#1530 Image import: Include network and subnet for inspection
  cli_tools/common/image/importer/api_inflater.go
  cli_tools/common/image/importer/request.go
  cli_tools/common/image/importer/request_test.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools_tests/module/import/inflater_test.go
  cli_tools_tests/module/import/vpc_test.go
Labels: approved, lgtm, size/L

#1533 Add win10/2012 builds. Remove most bios builds. Forking windows-build common wf.
  daisy_workflows/image_build/windows/README.md
  daisy_workflows/image_build/windows/post_install.ps1
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json
  daisy_workflows/image_build/windows/windows-build-bios.wf.json
  daisy_workflows/image_build/windows/windows-build-uefi.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
Labels: approved, lgtm, size/L

#1537 Pass "pwsh" variable to windows-build workflow
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
Labels: lgtm, size/XS

#1528 OVF import: Use import module for GA
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
Labels: approved, do-not-merge/hold, lgtm, size/XL

#1535 Bare metal dev
  daisy_workflows/build-publish/linux_dev/centos_7_dev.wf.json
  daisy_workflows/build-publish/linux_dev/centos_8_dev.wf.json
  daisy_workflows/build-publish/linux_dev/debian_10_dev.wf.json
  daisy_workflows/build-publish/linux_dev/debian_9_dev.wf.json
  daisy_workflows/build-publish/linux_dev/development.wf.json
  daisy_workflows/build-publish/linux_dev/rhel_7_metal_dev.wf.json
  daisy_workflows/build-publish/linux_dev/rhel_8_metal_dev.wf.json
  daisy_workflows/build-publish/linux_dev/ubuntu_1604_dev.wf.json
  daisy_workflows/build-publish/linux_dev/ubuntu_1804_dev.wf.json
Labels: approved, size/S

#1542 Fixed OVF machine image e2e tests failing due to multiple tests sharing single Cloud Build
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/XS

#1543 Added custom Compute engine service account to OVF import
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/multi_image_importer/request_builder.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools_tests/e2e/gce_ovf_import/main.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  common/gcp/instance.go
  daisy_workflows/ovf_import/create_gmi.wf.json
  daisy_workflows/ovf_import/create_instance.wf.json
  test-infra/prow/config.yaml
Labels: approved, size/L

#1544 Fix GMI e2e tests using project for zone
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/XS

#1545 Make sure dhcp-client is installed for EL8.
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-packages.cfg
Labels: approved, lgtm, size/XS

#1540 Updating byol and 2012r2 workflows
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
Labels: approved, lgtm, size/M

#1546 [onestep-import e2e] only test windows for wrapper
  cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
Labels: approved, size/S

#1548 add debian 9 build deps
  daisy_workflows/image_build/debian/build.py
Labels: approved, lgtm, size/XS

#1547 OVF Import: added -scope flag to allow custom instance access scopes
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  common/gcp/instance.go
Labels: approved, lgtm, size/L
