Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-03, with the labels that each got.

#1549 Add -byol flag to OVF import
  cli_tools/common/image/importer/request.go
  cli_tools/common/image/importer/request_test.go
  cli_tools/gce_ovf_import/README.md
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/multi_image_importer/request_builder.go
  cli_tools/gce_ovf_import/multi_image_importer/request_builder_test.go
  cli_tools/gce_vm_image_import/README.md
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_vm_image_import/cli/args_test.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, lgtm, size/L

#1534 add export metadata for windows
  daisy_workflows/export_metadata/export-metadata.ps1
  daisy_workflows/export_metadata/export-metadata.py
  daisy_workflows/export_metadata/export_metadata_windows.wf.json
Labels: approved, lgtm, size/L

#1550 Updating windows image build docs
  daisy_workflows/image_build/windows/README.md
Labels: approved, lgtm, size/M

#1552 Switch to shadow disk inflater
  cli_tools/common/image/importer/inflater.go
  cli_tools/common/image/importer/inflater_test.go
Labels: approved, lgtm, size/XS

#1553 added default service account in shadow disk inflater checksum calculator workflow
  cli_tools/common/image/importer/api_inflater.go
  cli_tools/common/image/importer/api_inflater_test.go
Labels: approved, lgtm, size/XS

#1554 Export metadata windows bug fix
  daisy_workflows/export_metadata/export-metadata.ps1
Labels: approved, lgtm, size/XS

#1555 Windows: Wait 5 seconds before dismounting registry files
  daisy_workflows/image_import/windows/translate.ps1
  daisy_workflows/image_import/windows/translate_bootstrap.ps1
Labels: approved, lgtm, size/XS

#1559 OVF Import: introduced instance service account flag
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_tests/e2e/variables.go
  daisy_workflows/ovf_import/create_gmi.wf.json
  daisy_workflows/ovf_import/create_instance.wf.json
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/L

#1564 Updating timeout to 100min for SQL 2017
  daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2019-dc.wf.json
Labels: approved, lgtm, size/S

#1565 error instead of warn, upload json to outs path
  daisy_workflows/export_metadata/export-metadata.py
Labels: approved, size/M

#1551 Updates
  cli_tools/gce_export/README.md
  cli_tools/gce_vm_image_export/README.md
  docs/daisy-workflow-config-spec.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1566 Rpm add epoch
  daisy_workflows/export_metadata/export-metadata.py
Labels: approved, size/S

#1567 update image version
  daisy_workflows/export_metadata/export-metadata.py
  daisy_workflows/export_metadata/export_metadata.wf.json
Labels: approved, lgtm, size/XS

#1568 Updating SQL Build timeouts and Windows Update function
  daisy_workflows/image_build/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-web-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-express-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-standard-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-web-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql_install.ps1
  daisy_workflows/image_build/sqlserver/sqlserver.wf.json
Labels: approved, lgtm, size/XL

#1558 Move image build workflows to e2 machine types.
  daisy_workflows/build-publish/linux_dev/development.wf.json
  daisy_workflows/image_build/bare_metal/bare_metal_linux.wf.json
  daisy_workflows/image_build/debian/debian.wf.json
  daisy_workflows/image_build/debian/debian_10_worker.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/sqlserver/sqlserver.wf.json
  daisy_workflows/image_build/windows/windows-build-bios.wf.json
  daisy_workflows/image_build/windows/windows-build-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1709-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1803-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1809-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1809-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1903-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1903-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1909-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-1909-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers.wf.json
Labels: approved, lgtm, size/M

#1572 osconfig tests: add Ubuntu to head tests
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/XS

#1563 Image import: Disable calling PD API.
  cli_tools/common/image/importer/inflater.go
Labels: approved, lgtm, size/XS

#1571 Refactor el
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-4-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-6-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-sap-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-8-1-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-8-2-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-8-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-8-sap-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-minor-post.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: approved, lgtm, size/L

#1561 Daisy: Don't panic when workflow is canceled twice
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/gce_image_publish/main.go
  daisy/cli/main.go
  daisy/daisy_test_runner/main.go
  daisy/step_create_instances.go
  daisy/workflow.go
  daisy/workflow_test.go
Labels: approved, lgtm, size/L

#1573 OVF Import: switched disks to SSD (from standard)
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go
  cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater_test.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  daisy_workflows/ovf_import/create_gmi.wf.json
  daisy_workflows/ovf_import/create_instance.wf.json
Labels: approved, lgtm, size/M

#1574 OVF import: support for no service account and no access scopes. Refa…
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  common/gcp/instance.go
  daisy_workflows/ovf_import/create_gmi.wf.json
  daisy_workflows/ovf_import/create_instance.wf.json
Labels: approved, lgtm, size/XXL

#1575 OVF GMI import E2E tests: a fix and consolidation
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/M

#1578 Make imagesCache usage optional.
  cli_tools/gce_image_publish/main.go
  cli_tools/gce_image_publish/publish/publish.go
Labels: approved, lgtm, size/S

#1580 Increase build timeout to 4h
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x86-bios-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-sac-1909-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-sac-2004-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-sac-20h2-dc-core-uefi-payg.wf.json
Labels: lgtm, size/S

#1582 Added compute-image-test-pool-001-1 and compute-image-test-pool-001-2 projects to cleanerupper config
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/XS

#1581 import_precheck: Fail when root device spans multiple physical disks
  cli_tools/import_precheck/check_disks_linux.go
  cli_tools/import_precheck/check_disks_linux_test.go
  cli_tools/import_precheck/testdata/lsblk-efi.json
  cli_tools/import_precheck/testdata/lsblk-multi-disk-lvm.json
  cli_tools/import_precheck/testdata/lsblk-one-partition.json
  cli_tools/import_precheck/testdata/lsblk-single-disk-lvm.json
Labels: approved, lgtm, size/L

#1584 Update CentOS 8 import tests: 8.2 to 8.3
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: approved, lgtm, size/XS

#1586 Support importing Debian 10
  cli_tools/common/utils/daisy/daisy_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_integration_tests/debian_10_translate.wf.json
  daisy_workflows/image_import/debian/translate.py
  daisy_workflows/image_import/debian/translate_debian_10.wf.json
Labels: approved, lgtm, size/L

#1569 AlmaLinux 8 image build.
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json
  daisy_workflows/image_build/enterprise_linux/almalinux_8.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux-8-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el8-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: approved, lgtm, size/L

#1587 Disable EL repo_gpgcheck for Google Cloud repositories.
  daisy_workflows/image_build/bare_metal/bare_metal_image_preparer.sh
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, lgtm, size/S

#1579 Add SEV_CAPABLE flag to EL8 images.
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/image_build/enterprise_linux/centos_8.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_stream_8.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos.wf.json
Labels: approved, lgtm, size/S

#1589 EL import: Retry GuestFS cleanup on failure
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, size/S

#1591 Image import: Don't log success on timeout
  cli_tools/common/image/importer/bootable_disk_processor.go
Labels: approved, lgtm, size/XS
