Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-10, with the labels that each got.

#1762 Support the gcloud bundled python3 package for RHEL 7.6.
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel-7-sap-post.cfg
Labels: size/S, lgtm, approved

#1764 cleanerupper: update flag defaults and fix some issues with OSPolicyAssignments
  test-infra/prow/config.yaml
  test-infra/prowjobs/cleanerupper/main.go
Labels: size/M, lgtm, approved

#1763 Ubuntu import: When possible, don't install cloud-init 21.3-1
  daisy_workflows/image_import/ubuntu/translate.py
  daisy_workflows/linux_common/tests/test_apt.py
  daisy_workflows/linux_common/utils/apt.py
Labels: size/L, lgtm, approved

#1759 Windows upgrade: Use daisy worker
  cli_tools/common/mount/inspector_test.go
  cli_tools/gce_windows_upgrade/upgrader/test_common_test.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
Labels: size/M, lgtm, approved

#1757 OVF Export: Use Daisy worker
  cli_tools/gce_ovf_export/domain/args.go
  cli_tools/gce_ovf_export/domain/args_test.go
  cli_tools/gce_ovf_export/domain/test_data.go
  cli_tools/gce_ovf_export/exporter/exporter.go
  cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go
  cli_tools/gce_ovf_export/exporter/instance_export_cleaner.go
  cli_tools/gce_ovf_export/exporter/instance_export_preparer.go
  cli_tools/gce_ovf_export/exporter/steps.go
Labels: size/M, lgtm, approved

#1765 CLI tools: Don't log metrics using the workflow directly
  cli_tools/common/utils/logging/service/daisy_loggable.go
  cli_tools/common/utils/logging/service/daisy_loggable_test.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/main.go
  cli_tools/gce_windows_upgrade/main.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader_test.go
Labels: size/L, lgtm, approved

#1774 Stop creation of cloud logging client when cloud logging is disabled
  daisy/workflow.go
  daisy/workflow_test.go
Labels: size/XS, approved
