Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-07, with the labels that each got.

#1688 Fix typo (missing comma)
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
Labels: approved, lgtm, size/XS

#1690 Update dual-region to region mappings
  cli_tools/common/utils/storage/resource_location_retriever.go
Labels: approved, lgtm, size/XS

#1689 Add SEV_CAPABLE flag to partner images.
  daisy_workflows/build-publish/partner/cos_81_lts.publish.json
  daisy_workflows/build-publish/partner/cos_85_lts.publish.json
  daisy_workflows/build-publish/partner/cos_89_lts.publish.json
  daisy_workflows/build-publish/partner/cos_dev.publish.json
  daisy_workflows/build-publish/partner/sles_15.publish.json
  daisy_workflows/build-publish/partner/ubuntu_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_2004.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_2004.publish.json
Labels: approved, lgtm, size/S

#1691 [onestep import] output help link for customers
  cli_tools/gce_onestep_image_import/main.go
Labels: approved, size/S

#1692 [import] calculate alloc size with minimum limit 10gb
  cli_tools/common/image/importer/daisy_inflater.go
Labels: approved, lgtm, size/S

#1696 Adding detection and remediation of static IP & DNS
  daisy_workflows/image_import/windows/network.ps1
  daisy_workflows/image_import/windows/run_startup_scripts.cmd
  daisy_workflows/image_import/windows/run_startup_scripts_x86.cmd
  daisy_workflows/image_import/windows/translate.ps1
  daisy_workflows/image_import/windows/translate_bootstrap.ps1
  daisy_workflows/image_import/windows/translate_windows_wf.json
  daisy_workflows/image_import/windows/translate_windows_x86_wf.json
Labels: approved, lgtm, size/M

#1695 Add RHEL 8.4 for SAP image builds.
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json
Labels: approved, lgtm, size/L

#1694 CLI Tools: Make client_id optional
  cli_tools/gce_onestep_image_import/README.md
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go
  cli_tools/gce_ovf_export/README.md
  cli_tools/gce_ovf_export/exporter/param_validator.go
  cli_tools/gce_ovf_export/exporter/param_validator_test.go
  cli_tools/gce_ovf_import/README.md
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools/gce_vm_image_export/README.md
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  cli_tools/gce_vm_image_import/README.md
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_vm_image_import/cli/args_test.go
  cli_tools/gce_windows_upgrade/upgrader/validators.go
  cli_tools/gce_windows_upgrade/upgrader/validators_test.go
Labels: approved, lgtm, size/L

#1693 Daisy: Recursively build child workflows in NewFromFile
  daisy/common.go
  daisy/step_includeworkflow.go
  daisy/step_includeworkflow_test.go
  daisy/step_sub_workflow.go
  daisy/step_sub_workflow_test.go
  daisy/test_data/TestNewFromFile_PopulatesVariables.child.wf.json
  daisy/test_data/TestNewFromFile_PopulatesVariables.parent.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.child1.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.child2.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.parent.wf.json
  daisy/test_data/TestNewIncludedWorkflowFromFile_UsesResourcesFromParent.wf.json
  daisy/test_data/test.wf.json
  daisy/validate.go
  daisy/workflow.go
  daisy/workflow_test.go
Labels: approved, lgtm, size/L

#1700 Revert "Daisy: Recursively build child workflows in NewFromFile (#1693)"
  daisy/common.go
  daisy/step_includeworkflow.go
  daisy/step_includeworkflow_test.go
  daisy/step_sub_workflow.go
  daisy/step_sub_workflow_test.go
  daisy/test_data/TestNewFromFile_PopulatesVariables.child.wf.json
  daisy/test_data/TestNewFromFile_PopulatesVariables.parent.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.child1.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.child2.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.parent.wf.json
  daisy/test_data/TestNewIncludedWorkflowFromFile_UsesResourcesFromParent.wf.json
  daisy/test_data/test.wf.json
  daisy/validate.go
  daisy/workflow.go
  daisy/workflow_test.go
Labels: approved, lgtm, size/L

#1701 Daisy: Recursively build child workflows in NewFromFile when path doesn't have variable.
  daisy/common.go
  daisy/common_test.go
  daisy/step_includeworkflow.go
  daisy/step_includeworkflow_test.go
  daisy/step_sub_workflow.go
  daisy/step_sub_workflow_test.go
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.child1.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.child2.wf.json
  daisy/test_data/TestNewFromFile_ReadsChildWorkflows.parent.wf.json
  daisy/test_data/TestNewFromFile_SupportsNestedVariables.child.wf.json
  daisy/test_data/TestNewFromFile_SupportsNestedVariables.parent.wf.json
  daisy/test_data/TestNewFromFile_SupportsNestedVariables_VarInFilename.child.wf.json
  daisy/test_data/TestNewFromFile_SupportsNestedVariables_VarInFilename.parent.wf.json
  daisy/test_data/TestNewIncludedWorkflowFromFile_UsesResourcesFromParent.wf.json
  daisy/test_data/test.wf.json
  daisy/validate.go
  daisy/workflow.go
  daisy/workflow_test.go
Labels: approved, lgtm, size/L

#1704 Daisy: Don't clobber child variables from parent workflow
  daisy/common.go
  daisy/test_data/TestNewFromFile_SupportsNestedVariables.child.wf.json
  daisy/test_data/TestNewFromFile_SupportsNestedVariables.parent.wf.json
  daisy/test_data/TestNewFromFile_SupportsNestedVariables_VarInFilename.child.wf.json
  daisy/test_data/TestNewFromFile_SupportsNestedVariables_VarInFilename.parent.wf.json
  daisy/workflow_test.go
Labels: approved, lgtm, size/S

#1577 I assume here we don't need the duplicated dependency
  cli_tools/gce_image_publish/publish/publish.go
Labels: approved, lgtm, size/XS

#1699 CLI tools: Pre-validate network and subnet
  cli_tools/common/image/importer/process_planner.go
  cli_tools/common/utils/param/network_resolver.go
  cli_tools/common/utils/param/network_resolver_test.go
  cli_tools/common/utils/param/param_utils.go
  cli_tools/common/utils/param/populator.go
  cli_tools/common/utils/param/populator_test.go
  cli_tools/common/utils/paramhelper/network.go
  cli_tools/common/utils/paramhelper/network_test.go
  cli_tools/common/utils/paramhelper/resources.go
  cli_tools/common/utils/paramhelper/resources_test.go
  cli_tools/common/utils/paramhelper/subnet.go
  cli_tools/common/utils/paramhelper/subnet_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_args.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
  cli_tools/gce_onestep_image_import/onestep_importer/test_utils_test.go
  cli_tools/gce_ovf_export/exporter/exporter.go
  cli_tools/gce_ovf_export/exporter/param_populator.go
  cli_tools/gce_ovf_export/exporter/param_populator_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_vm_image_import/cli/args_test.go
  cli_tools/gce_vm_image_import/cli/cli.go
  cli_tools/mocks/mock_network_resolver.go
  cli_tools/mocks/mock_param_populator.go
Labels: approved, lgtm, size/XXL
