Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-12, with the labels that each got.

#1800 daisy: modify daisy URL in daisy installation usage doc
  docs/daisy-installation-usage.md
Labels: size/XS, needs-ok-to-test

#1803 [onestep-import] install gcsfuse and qemu for onestep-import
  gce_onestep_image_import.Dockerfile
Labels: size/XS, lgtm, approved

#1804 Fix sql workflow path
  daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2019-dc.wf.json
Labels: size/M

#1805 Update sql disk export destination
  daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2012-r2-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2016-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2019-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2019-dc.wf.json
Labels: size/M

#1751 [rollout] new rollout config
  rollout/cli_tools_cloudbuild_build.yaml
  rollout/cli_tools_cloudbuild_build_prepare.yaml
  rollout/cli_tools_cloudbuild_deploy.yaml
  rollout/cli_tools_cloudbuild_release_workflow.yaml
  rollout/cli_tools_cloudbuild_rollback.yaml
Labels: size/L, approved

#1806 Update the publish filename to be consistent
  daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc-uefi.publish
  daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc-uefi.publish
Labels: size/XS

#1791 [safely Enable VMDK API] stage 2: enable API inflater
  cli_tools/common/image/importer/daisy_inflater_test.go
  cli_tools/common/image/importer/inflater.go
  cli_tools/common/image/importer/inflater_test.go
Labels: size/S, lgtm, approved

#1808 [e2e test] add qemu/gcsfuse for test docker images
  test-infra/prowjobs/wrapper/withgcloud.Dockerfile
Labels: size/S, lgtm, approved

#1810 [test base image] change the base image, add gcsfuse key
  test-infra/prowjobs/wrapper/gcsfuse-apt-key.gpg
  test-infra/prowjobs/wrapper/withgcloud.Dockerfile
Labels: size/XS, approved

#1809 OVF e2e: Use Debian 11 for 3 disk test
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/scripts/ovf_import_test_3_disks.sh
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: size/M, lgtm, approved

#1812 Add server 2022 to the VSS install regex
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS

#1807 Image Import: Warn when UEFI boot is specified but not detected.
  cli_tools/common/image/importer/process_planner.go
  cli_tools/common/image/importer/process_planner_test.go
Labels: size/M, lgtm, approved

#1814 follow staticcheck-S1012-and-ST1005 checks
  cli_tools/common/disk/inspect.go
  cli_tools/common/disk/inspect_test.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: needs-ok-to-test, size/M, lgtm, approved

#1815 Image Import e2e: add e2e test for sles sap 15sp3 unregistered
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: size/XS, needs-ok-to-test

#1816 Update publish to staging projects
  daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-2019-core-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-2019-for-containers-uefi.publish.json
Labels: size/M

#1818 Windows import: Don't fail when EMS is on COM1
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/windows/translate_bootstrap.ps1
Labels: size/S, lgtm, approved

#1821 Fix image export failing occasionally for large images by allocating buffer disk size to match raw image size
  cli_tools/common/utils/validation/validation_utils.go
  cli_tools/common/utils/validation/validation_utils_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  daisy_workflows/export/disk_export.wf.json
Labels: size/L, lgtm, approved

#1822 Image import inspection: update inspection stage to support archlinux and clearlinux distros
  daisy_workflows/image_import/inspection/src/boot_inspect/inspection.py
  daisy_workflows/image_import/inspection/tests/test-data/images/docker-image-archlinux-latest.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/docker-image-clear-linux-os-latest.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/docker-image-debian-11.2.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/gcp-archlinux-latest.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/gcp-image-debian-11-bullseye-v20211209.yaml
  daisy_workflows/image_import/inspection/tests/test-data/images/gcp-image-sles-15-sp3-sap-v20211113.yaml
  proto/go/pb/inspect.pb.go
  proto/go/pb/output_info.pb.go
  proto/inspect.proto
  proto/py/compute_image_tools_proto/inspect_pb2.py
  proto/py/compute_image_tools_proto/inspect_pb2.pyi
  proto/py/compute_image_tools_proto/output_info_pb2.py
  proto/py/compute_image_tools_proto/output_info_pb2.pyi
  proto/updatepb.sh
Labels: size/L, needs-ok-to-test, lgtm, approved

#1823 Image_Import_inspection: update_archlinux_and_clearlinux_distros_IDs
  proto/go/pb/inspect.pb.go
  proto/inspect.proto
  proto/py/compute_image_tools_proto/inspect_pb2.py
  proto/py/compute_image_tools_proto/inspect_pb2.pyi
Labels: size/L, needs-ok-to-test

#1824 RHUA node image build workflow
  daisy_workflows/build-publish/rhui/answers.yaml
  daisy_workflows/build-publish/rhui/depend-nfs.conf
  daisy_workflows/build-publish/rhui/fstab
  daisy_workflows/build-publish/rhui/install_rhua.sh
  daisy_workflows/build-publish/rhui/reponames.txt
  daisy_workflows/build-publish/rhui/rhua.wf.json
Labels: size/XL, approved
