Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-06, with the labels that each got.

#1649 Add -byol string to avoid building SPLA image
  daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json
Labels: lgtm, needs-ok-to-test, size/XS

#1646 Always install EPEL for EL8 bare metal.
  daisy_workflows/image_build/bare_metal/bare_metal_image_preparer.sh
Labels: approved, size/S

#1647 Adding image rollout policy support to GCE_Image_Publish
  cli_tools/gce_image_publish/main.go
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_image_publish/publish/publish_test.go
  cli_tools/go.mod
  cli_tools/go.sum
Labels: approved, lgtm, size/XL

#1650 Updating DeprecationStatus in Daisy Alpha API
  daisy/step_deprecate_images.go
  daisy/step_deprecate_images_test.go
Labels: lgtm, size/S

#1651 Updating Daisy dependency for CLI tools
  cli_tools/go.mod
Labels: approved, lgtm, size/XS

#1652 Updating publish files to use Alpha API Endpoint
  daisy_workflows/build-publish/bare_metal/rhel_7.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_8.publish.json
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_10_worker.publish.json
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/debian/debian_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
  daisy_workflows/build-publish/linux_dev/debian_staging.publish.json
  daisy_workflows/build-publish/linux_dev/rhel_7_metal_dev.publish.json
  daisy_workflows/build-publish/linux_dev/rhel_8_metal_dev.publish.json
  daisy_workflows/build-publish/partner/cos_81_lts.publish.json
  daisy_workflows/build-publish/partner/cos_85_lts.publish.json
  daisy_workflows/build-publish/partner/cos_89_lts.publish.json
  daisy_workflows/build-publish/partner/cos_dev.publish.json
  daisy_workflows/build-publish/partner/fedora_33.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_next.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_stable.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_testing.publish.json
  daisy_workflows/build-publish/partner/freebsd_11.publish.json
  daisy_workflows/build-publish/partner/freebsd_12.publish.json
  daisy_workflows/build-publish/partner/freebsd_13.publish.json
  daisy_workflows/build-publish/partner/opensuse_leap_15.publish.json
  daisy_workflows/build-publish/partner/sles_12.publish.json
  daisy_workflows/build-publish/partner/sles_15.publish.json
  daisy_workflows/build-publish/partner/ubuntu_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_2004.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1604.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_2004.publish.json
Labels: approved, lgtm, size/L

#1653 OVF import: Apply user-provided tags to final instance
  cli_tools/gce_ovf_import/domain/ovf_import_params.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/M

#1654 add firewall in step_delete_resource step
  daisy/step_delete_resources.go
  daisy/step_delete_resources_test.go
Labels: approved, size/M

#1656 Fix endpoint var.
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_10_worker.publish.json
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/debian/debian_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
Labels: approved, lgtm, size/M

#1661 Fix RHEL metal dev build/publish.
  daisy_workflows/build-publish/bare_metal/rhel_7_metal.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_7_metal.wf.json
  daisy_workflows/build-publish/bare_metal/rhel_7_metal_dev.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_7_metal_dev.wf.json
  daisy_workflows/build-publish/bare_metal/rhel_8_metal.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_8_metal.wf.json
  daisy_workflows/build-publish/bare_metal/rhel_8_metal_dev.publish.json
  daisy_workflows/build-publish/bare_metal/rhel_8_metal_dev.wf.json
Labels: approved, lgtm, size/S

#1660 Revert "Add GVNIC flag to supported OS's. (#1658)"
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
Labels: approved, lgtm, size/S

#1659 Run image export E2E tests in a couple of different regions
  cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
Labels: approved, lgtm, size/M

#1655 Improve error message when detected OS doesn't match specified OS.
  cli_tools/common/distro/distro.go
  cli_tools/common/distro/distro_test.go
  cli_tools/common/image/importer/bootable_disk_processor.go
  cli_tools/common/image/importer/bootable_disk_processor_test.go
  cli_tools/common/image/importer/errors.go
  cli_tools/common/image/importer/errors_test.go
  cli_tools/common/image/importer/process_planner.go
  cli_tools/common/image/importer/process_planner_test.go
  cli_tools/common/image/importer/processor.go
  daisy_workflows/linux_common/utils/diskutils.py
Labels: approved, lgtm, size/L

#1657 cleanerupper: point to official osconfig client libraries
  test-infra/prowjobs/cleanerupper/go.mod
  test-infra/prowjobs/cleanerupper/go.sum
  test-infra/prowjobs/cleanerupper/main.go
Labels: approved, lgtm, size/L

#1662 OVF import E2E test to run in different zones.
  cli_tools/go.sum
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
  cli_tools_tests/go.sum
Labels: approved, lgtm, size/L

#1666 Image export: Improve error message when source image not found
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
Labels: approved, lgtm, size/M

#1667 Move regionalized OVF import E2E tests that were running in asia-east1 to asia-east2 due to stockouts.
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/XS

#1669 Image import E2E test to run in different zones.
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Labels: approved, lgtm, size/L

#1668 Image export: Only validate non-URI images
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
Labels: approved, lgtm, size/S

#1670 Image export and OVF import regional E2E tests to use asia-northeast1
  cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/S

#1671 Add 4 new regions to build import/export wrappers to.
  cli_tools_cloudbuild.yaml
Labels: approved, lgtm, size/M

#1672 Adding Windows Server and Container build and publish workflows for Concourse
  daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows_export.wf.json
  daisy_workflows/build-publish/windows_container/windows-2019-core-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-2019-core-for-containers-uefi.wf.json
  daisy_workflows/build-publish/windows_container/windows-2019-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-2019-for-containers-uefi.wf.json
Labels: approved, lgtm, size/XXL

#1675 Fix staging endpoint and use worker project we can write to.
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/debian/debian_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
  daisy_workflows/build-publish/partner/cos_81_lts.publish.json
  daisy_workflows/build-publish/partner/cos_85_lts.publish.json
  daisy_workflows/build-publish/partner/cos_89_lts.publish.json
  daisy_workflows/build-publish/partner/cos_dev.publish.json
  daisy_workflows/build-publish/partner/fedora_33.publish.json
  daisy_workflows/build-publish/partner/fedora_34.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_next.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_stable.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_testing.publish.json
  daisy_workflows/build-publish/partner/freebsd_11.publish.json
  daisy_workflows/build-publish/partner/freebsd_12.publish.json
  daisy_workflows/build-publish/partner/freebsd_13.publish.json
  daisy_workflows/build-publish/partner/opensuse_leap_15.publish.json
  daisy_workflows/build-publish/partner/sles_12.publish.json
  daisy_workflows/build-publish/partner/sles_15.publish.json
  daisy_workflows/build-publish/partner/ubuntu_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_2004.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1604.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_2004.publish.json
Labels: approved, lgtm, size/L

#1676 Fix rocky linux template and staging licenses.
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/debian/debian_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
Labels: approved, lgtm, size/M

#1678 Fix staging license conditional statement.
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/debian/debian_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
Labels: approved, lgtm, size/M

#1679 avoid interleaved output
  cli_tools/common/image/importer/api_inflater.go
  daisy_workflows/export/export_disk.sh
  daisy_workflows/export/export_disk_ext.sh
  daisy_workflows/image_import/import_image.sh
Labels: approved, size/M

#1681 Fixing variable for cloud sdk
  daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.wf.json
Labels: approved, lgtm, size/S

#1682 Updating variables passed to workflows
  daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012r2-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.wf.json
Labels: approved, lgtm, size/M

#1683 Fixing variable in windows_export.wf
  daisy_workflows/build-publish/windows/windows_export.wf.json
Labels: approved, lgtm, size/XS

#1684 Fixing destination variable case
  daisy_workflows/build-publish/windows/windows_export.wf.json
Labels: approved, lgtm, size/XS

#1680 Modify scratch bucket creation name to not use "."
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
Labels: approved, lgtm, size/XS

#1685 Disable root login for sshd on Debian fai builds.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/scripts/12-sshd
Labels: approved, lgtm, size/XS

#1686 Add missing source file.
  daisy_workflows/image_build/debian/debian_fai.wf.json
Labels: approved, lgtm, size/XS
