Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-08, with the labels that each got.

#1707 CLI tools: Accept legacy apiary URL styles for resources
  cli_tools/common/utils/paramhelper/resources.go
  cli_tools/common/utils/paramhelper/resources_test.go
Labels: approved, lgtm, size/S

#1706 CLI Tools: Populate region prior to network
  cli_tools/common/utils/param/populator.go
  cli_tools/common/utils/param/populator_test.go
Labels: approved, lgtm, size/S

#1705 Daisy Refactor: Remove validation hooks from bootable disk processor
  cli_tools/common/image/importer/bootable_disk_processor.go
  cli_tools/common/image/importer/bootable_disk_processor_test.go
  cli_tools/common/image/importer/processor_test.go
Labels: approved, size/L

#1703 [cli-tools] fix buffered writer err log prefix so it can be picked up by 'waitForInstanceSignals'
  cli_tools/common/utils/storage/buffered_writer.go
  cli_tools/common/utils/storage/buffered_writer_test.go
  cli_tools/gce_export/main.go
  cli_tools/gce_onestep_image_import/onestep_importer/aws_importer.go
Labels: approved, size/L

#1709 Image import: Don't re-zero PDs
  daisy_workflows/image_import/import_image.sh
Labels: approved, size/S

#1711 Revert "Image import: Don't re-zero PDs (#1709)"
  daisy_workflows/image_import/import_image.sh
Labels: approved, lgtm, size/S

#1710 EL Import: Don't require yum
  daisy_workflows/image_import/enterprise_linux/translate.py
Labels: approved, lgtm, size/M

#1713 Make OVF import temporary bucket name safe for projects with the "google.com:" prefix
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
Labels: size/XS, lgtm, approved

#1714 OVF import: fix project IDs validation by supporting "google.com:" prefix
  cli_tools/common/utils/validation/validation_utils.go
  cli_tools/common/utils/validation/validation_utils_test.go
Labels: size/XS, lgtm, approved

#1715 correct selinux labels in chroot
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/S, lgtm, approved

#1708 CLI Tools: Remove race condition in gcsfuse test
  cli_tools/common/imagefile/inspector_test.go
Labels: size/S, lgtm, approved

#1716 Fix flag names in gce_vm_image_import README (underscore vs dash)
  cli_tools/gce_vm_image_import/README.md
Labels: size/S, lgtm, approved

#1712 Image Export: Add logging for snapshot export
  cli_tools/common/utils/logging/service/log_entry.go
  cli_tools/gce_vm_image_export/main.go
Labels: size/XS, lgtm, approved

#1718 Daisy: Remove disk.IsWindows
  cli_tools/test_data/test_import_ovf_to_instance.wf.json
  cli_tools/test_data/test_import_ovf_to_machine_image.wf.json
  daisy/disk.go
  daisy/disk_test.go
  daisy_workflows/image_import/import_and_translate.wf.json
  daisy_workflows/image_import/import_from_image.wf.json
  daisy_workflows/image_import/inflate_file.wf.json
  daisy_workflows/ovf_import/import_ovf_to_instance.wf.json
  daisy_workflows/ovf_import/import_ovf_to_machine_image.wf.json
Labels: size/M, lgtm, approved

#1717 Remove workflow.RunWithModifiers
  cli_tools/common/image/importer/bootable_disk_processor.go
  cli_tools/daisycommon/daisy_worker.go
  cli_tools/daisycommon/daisy_worker_test.go
  cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go
  cli_tools/gce_ovf_export/exporter/steps.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  daisy/workflow.go
Labels: size/L, lgtm, approved

#1719 [daisy] fix output breakage for waitForInstanceSignal
  daisy/step_wait_for_instances_signal.go
  daisy/step_wait_for_instances_signal_test.go
Labels: size/M, lgtm, approved

#1720 Daisy:support guestattrs in WaitForInstancesSignal
  daisy/compute/compute.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/step_wait_for_instances_signal.go
  daisy/step_wait_for_instances_signal_test.go
  daisy_integration_tests/step_wait_for_instance_signal.wf.json
Labels: size/L, approved

#1723 enable guest attrs in wait integ test
  daisy_integration_tests/step_wait_for_instance_signal.wf.json
Labels: size/XS, lgtm, approved

#1725 fix test: add \n for serial output
  cli_tools/gce_ovf_export/exporter/instance_disks_exporter_test.go
  cli_tools/mocks/mock_compute_client.go
Labels: size/XL, lgtm, approved

#1721 Fix Debian apt updates in builds.
  daisy_workflows/image_build/debian/debian_10_worker.sh
  daisy_workflows/linux_common/bootstrap.sh
  daisy_workflows/linux_common/utils/common.py
Labels: size/S, approved

#1726 CLI Tools: Use deb10 worker for EL8 import and inspection
  daisy_workflows/image_import/enterprise_linux/translate_centos_8.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json
  daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
  daisy_workflows/image_import/inspection/boot-inspect.wf.json
Labels: size/XS, lgtm, approved

#1727 Daisy: Remove e2e tests for SUSE import
  daisy_integration_tests/daisy_e2e.test.gotmpl
  daisy_integration_tests/opensuse_15_1.wf.json
  daisy_integration_tests/sles_12_4_byol.wf.json
  daisy_integration_tests/sles_12_5_byol.wf.json
  daisy_integration_tests/sles_15_1_byol.wf.json
  daisy_integration_tests/sles_sap_12_4_byol.wf.json
Labels: size/L, lgtm, approved

#1729 update docs for guest attrs feature
  docs/daisy-workflow-config-spec.md
Labels: size/S, lgtm, approved

#1664 Adding ability to export fixed-sized VHDs
  cli_tools/gce_vm_image_export/README.md
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  cli_tools/gce_vm_image_export/main.go
  daisy_workflows/export/export_disk_ext.sh
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/M, lgtm, approved

#1731 Revert "Adding ability to export fixed-sized VHDs"
  cli_tools/gce_vm_image_export/README.md
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
  cli_tools/gce_vm_image_export/main.go
  daisy_workflows/export/export_disk_ext.sh
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/M, lgtm, approved

#1730 apt update: use --allow-releaseinfo-change
  daisy_workflows/image_build/debian/debian_10_worker.sh
  daisy_workflows/linux_common/bootstrap.sh
  daisy_workflows/linux_common/utils/common.py
Labels: size/S, lgtm, approved

#1722 CLI Tools: Prepare daisy worker for wider usage
  cli_tools/common/disk/inspect.go
  cli_tools/common/distro/distro_test.go
  cli_tools/common/image/importer/api_inflater.go
  cli_tools/common/image/importer/bootable_disk_processor.go
  cli_tools/common/image/importer/bootable_disk_processor_test.go
  cli_tools/common/image/importer/daisy_inflater.go
  cli_tools/common/image/importer/metadata_processor.go
  cli_tools/common/image/importer/process_planner.go
  cli_tools/common/image/importer/request.go
  cli_tools/common/image/importer/request_test.go
  cli_tools/common/image/importer/source.go
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/common/utils/daisyutils/daisy_utils_test.go
  cli_tools/common/utils/daisyutils/daisy_worker.go
  cli_tools/common/utils/daisyutils/daisy_worker_test.go
  cli_tools/common/utils/daisyutils/io.go
  cli_tools/common/utils/daisyutils/io_test.go
  cli_tools/common/utils/daisyutils/resource_labeler.go
  cli_tools/common/utils/daisyutils/resource_labeler_test.go
  cli_tools/common/utils/daisyutils/test_data/test.wf.json
  cli_tools/common/utils/daisyutils/workflow_modifier.go
  cli_tools/common/utils/daisyutils/workflow_modifier_logging.go
  cli_tools/common/utils/daisyutils/workflow_modifier_logging_test.go
  cli_tools/common/utils/daisyutils/workflow_modifier_no_external_ip.go
  cli_tools/common/utils/daisyutils/workflow_modifier_no_external_ip_test.go
  cli_tools/common/utils/daisyutils/workflow_modifier_workflow_properties.go
  cli_tools/common/utils/daisyutils/workflow_modifier_workflow_properties_test.go
  cli_tools/common/utils/daisyutils/workflow_modifier_workflow_vars.go
  cli_tools/common/utils/daisyutils/workflow_modifier_workflow_vars_test.go
  cli_tools/common/utils/logging/service/logger.go
  cli_tools/daisycommon/daisy_utils.go
  cli_tools/daisycommon/daisy_utils_test.go
  cli_tools/daisycommon/daisy_worker_test.go
  cli_tools/gce_onestep_image_import/onestep_importer/importer.go
  cli_tools/gce_ovf_export/domain/args.go
  cli_tools/gce_ovf_export/domain/args_test.go
  cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go
  cli_tools/gce_ovf_export/exporter/instance_export_cleaner.go
  cli_tools/gce_ovf_export/exporter/instance_export_preparer.go
  cli_tools/gce_ovf_export/exporter/steps.go
  cli_tools/gce_ovf_import/main.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_import/cli/args.go
  cli_tools/gce_windows_upgrade/upgrader/test_common_test.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  cli_tools/gce_windows_upgrade/upgrader/validators.go
  cli_tools/gce_windows_upgrade/upgrader/validators_test.go
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
  cli_tools/gce_windows_upgrade/upgrader/workflows_test.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/import_precheck/check_osversion.go
  cli_tools/mocks/mock_daisy_logger.go
  cli_tools/mocks/mock_daisy_worker.go
  cli_tools/mocks/mock_workflow_modifier.go
  cli_tools_tests/module/diskinspect/disk_inspect_test.go
Labels: size/XXL, lgtm, approved

#1732 Revert "apt update: use --allow-releaseinfo-change (#1730)"
  daisy_workflows/image_build/debian/debian_10_worker.sh
  daisy_workflows/linux_common/bootstrap.sh
  daisy_workflows/linux_common/utils/common.py
Labels: size/S, lgtm, approved

#1735 Image import: Support Debian 11
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_workflows/image_import/debian/translate.py
  daisy_workflows/image_import/debian/translate_debian_11.wf.json
Labels: size/M, lgtm, approved
