Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2021-04, with the labels that each got.

#1590 OVF import E2E test changes
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/M

#1592 Image import: Install OS Config agent in Ubuntu
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  daisy_integration_tests/ubuntu_1604_vmware_translate.wf.json
  daisy_integration_tests/ubuntu_1804_aws.wf.json
  daisy_integration_tests/ubuntu_1804_azure.wf.json
  daisy_integration_tests/ubuntu_1804_vmware.wf.json
  daisy_workflows/image_import/ubuntu/translate.py
Labels: approved, lgtm, size/M

#1593 OVF import fixes to support Oracle provided Oracle Linux OVAs
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go
  cli_tools/gce_ovf_import/ovf_utils/ovf_utils_test.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/export/image_export_test_suite.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
Labels: approved, lgtm, size/L

#1594 Update GPG key for gcsfuse
  gcsfuse-apt-key.gpg
Labels: approved, lgtm, size/XS

#1595 OVF export e2e test: use latest wrapper when re-importing OVF
  cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
Labels: approved, lgtm, size/XS

#1596 add optional var development
  daisy_workflows/build-publish/linux_dev/development.wf.json
Labels: approved, lgtm, size/XS

#1597 Publish our images for oslogin staging tests.
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/debian/debian_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
Labels: approved, lgtm, size/M

#1598 Add partner workflows for export and publish to oslogin staging.
  daisy_workflows/build-publish/partner/cos.publish.json
  daisy_workflows/build-publish/partner/cos_77_lts_export.wf.json
  daisy_workflows/build-publish/partner/cos_81_lts_export.wf.json
  daisy_workflows/build-publish/partner/cos_85_lts_export.wf.json
  daisy_workflows/build-publish/partner/cos_89_lts_export.wf.json
  daisy_workflows/build-publish/partner/cos_dev_export.wf.json
  daisy_workflows/build-publish/partner/fedora.publish.json
  daisy_workflows/build-publish/partner/fedora_33_export.wf.json
  daisy_workflows/build-publish/partner/fedora_coreos.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_next_export.wf.json
  daisy_workflows/build-publish/partner/fedora_coreos_stable_export.wf.json
  daisy_workflows/build-publish/partner/fedora_coreos_testing_export.wf.json
  daisy_workflows/build-publish/partner/freebsd.publish.json
  daisy_workflows/build-publish/partner/freebsd_11_export.wf.json
  daisy_workflows/build-publish/partner/freebsd_12_export.wf.json
  daisy_workflows/build-publish/partner/freebsd_13_export.wf.json
  daisy_workflows/build-publish/partner/opensuse.publish.json
  daisy_workflows/build-publish/partner/opensuse_leap_15_export.wf.json
  daisy_workflows/build-publish/partner/sles.publish.json
  daisy_workflows/build-publish/partner/sles_12_export.wf.json
  daisy_workflows/build-publish/partner/sles_15_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu.publish.json
  daisy_workflows/build-publish/partner/ubuntu_1604_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_1804_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_2004_export.wf.json
Labels: approved, lgtm, size/XL

#1600 Update osconfig test configs
  test-infra/prow/config.yaml
Labels: approved, lgtm, size/M

#1601 OS Login staging updates
  daisy_workflows/build-publish/partner/cos.publish.json
  daisy_workflows/build-publish/partner/cos_81_lts.publish.json
  daisy_workflows/build-publish/partner/cos_85_lts.publish.json
  daisy_workflows/build-publish/partner/cos_89_lts.publish.json
  daisy_workflows/build-publish/partner/cos_dev.publish.json
  daisy_workflows/build-publish/partner/fedora_33.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_next.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_stable.publish.json
  daisy_workflows/build-publish/partner/fedora_coreos_testing.publish.json
  daisy_workflows/build-publish/partner/freebsd.publish.json
  daisy_workflows/build-publish/partner/freebsd_11.publish.json
  daisy_workflows/build-publish/partner/freebsd_12.publish.json
  daisy_workflows/build-publish/partner/freebsd_13.publish.json
  daisy_workflows/build-publish/partner/opensuse_leap_15.publish.json
  daisy_workflows/build-publish/partner/sles.publish.json
  daisy_workflows/build-publish/partner/sles_12.publish.json
  daisy_workflows/build-publish/partner/sles_15.publish.json
  daisy_workflows/build-publish/partner/ubuntu.publish.json
  daisy_workflows/build-publish/partner/ubuntu_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_2004.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1604.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1604_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1804.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_1804_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_pro_2004.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_2004_export.wf.json
Labels: approved, do-not-merge/hold, lgtm, size/XL

#1602 Fix freebsd 13 family.
  daisy_workflows/build-publish/partner/freebsd_13_export.wf.json
Labels: approved, lgtm, size/XS

#1603 add timeout
  daisy_workflows/export_metadata/export_metadata.wf.json
  daisy_workflows/export_metadata/export_metadata_windows.wf.json
Labels: approved, lgtm, size/XS

#1585 Adding Alpha API support in Daisy for CreateImage/GetImage/DeprecateImage
  daisy/compute/compute.go
  daisy/compute/compute_test.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/go.mod
  daisy/go.sum
  daisy/image.go
  daisy/image_test.go
  daisy/step_copy_gcs_objects_test.go
  daisy/step_create_images.go
  daisy/step_create_images_test.go
  daisy/step_deprecate_images.go
  daisy/step_wait_for_instances_signal_test.go
  daisy/workflow_test.go
Labels: approved, lgtm, size/XL

#1604 add stderr in log
  daisy_workflows/export_metadata/export-metadata.py
Labels: approved, lgtm, size/S

#1608 Updated imageUsesAlphaFeatures and added tests
  daisy/step_create_images.go
  daisy/step_create_images_test.go
Labels: approved, lgtm, size/L

#1610 not log process stderr, log e.stderr
  daisy_workflows/export_metadata/export-metadata.py
Labels: approved, lgtm, size/XS

#1611 Rolling back Alpha API changes due to Daisy test failures
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools_tests/go.mod
  cli_tools_tests/go.sum
  daisy/compute/compute.go
  daisy/compute/compute_test.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/go.mod
  daisy/go.sum
  daisy/image.go
  daisy/image_test.go
  daisy/step_copy_gcs_objects_test.go
  daisy/step_create_images.go
  daisy/step_create_images_test.go
  daisy/step_deprecate_images.go
  daisy/step_wait_for_instances_signal_test.go
  daisy/workflow_test.go
Labels: approved, lgtm, size/XXL

#1612 error handling in metadata exporter
  daisy_workflows/export_metadata/export-metadata.py
Labels: approved, lgtm, size/S

#1614 publish empty metadata
  daisy_workflows/export_metadata/export-metadata.py
  daisy_workflows/export_metadata/export_metadata.wf.json
Labels: approved, lgtm, size/M

#1616 Disabling CentOS image import tests
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
  daisy_integration_tests/daisy_e2e.test.gotmpl
Labels: approved, lgtm, size/XS

#1617 Replace 'google.com' with 'google_com' in bucket names.
  cli_tools/common/utils/storage/scratch_bucket_creator.go
  cli_tools/common/utils/storage/scratch_bucket_creator_test.go
Labels: approved, lgtm, needs-ok-to-test, size/S
