Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-04, with the labels that each got.

#1897 RHUI: add create-dirs.conf to pulp services; add ops-agent
  daisy_workflows/build-publish/rhui/install_cds.sh
  daisy_workflows/build-publish/rhui/install_rhua.sh
  daisy_workflows/build-publish/rhui/rhua_artifacts/create-dirs.conf
Labels: size/S, lgtm, approved

#1898 add rhui publish workflows
  daisy_workflows/build-publish/rhui/cds.publish.json
  daisy_workflows/build-publish/rhui/rhua.publish.json
Labels: size/M, lgtm, approved

#1901 Import_Precheck: Update_cloudbuild_pipeline_to_Add_binaries_for_32-bit Operating Systems
  cli_tools/import_precheck/README.md
  cli_tools_cloudbuild.yaml
Labels: size/S, lgtm, approved

#1902 rhua: 4.1 updates
  daisy_workflows/build-publish/rhui/install_rhua.sh
  daisy_workflows/build-publish/rhui/rhua_artifacts/answers.yaml
Labels: size/XS, lgtm, approved

#1906 Update cds ansible template
  daisy_workflows/build-publish/rhui/cds_artifacts/cds.patch
  daisy_workflows/build-publish/rhui/install_cds.sh
Labels: size/M, lgtm, approved

#1907 add test env for rhui image publish
  daisy_workflows/build-publish/rhui/cds.publish.json
  daisy_workflows/build-publish/rhui/rhua.publish.json
Labels: size/M, lgtm, approved

#1904 rhui client rpms
  daisy_workflows/build-publish/rhui/rpms/README.md
  daisy_workflows/build-publish/rhui/rpms/build.sh
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7-extensions.txt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7-sap-extensions.txt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7-sap.crt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7-sap.csr
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7-sap.repo
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7.crt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7.csr
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel7.repo
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel79-sap-extensions.txt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel79-sap.crt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel79-sap.csr
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel79-sap.repo
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8-extensions.txt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8-sap-extensions.txt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8-sap.crt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8-sap.csr
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8-sap.repo
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8.crt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8.csr
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel8.repo
  daisy_workflows/build-publish/rhui/rpms/rh-client-config.spec
  daisy_workflows/build-publish/rhui/rpms/rhui-set-release
Labels: size/XXL, lgtm, approved

#1908 add rocky linux optimized for gcp
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_optimized_gcp_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_optimized_gcp_8.wf.json
  daisy_workflows/build-publish/rhui/cds.publish.json
  daisy_workflows/build-publish/rhui/rhua.publish.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky-linux-optimized-gcp-8-options.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
  daisy_workflows/image_build/enterprise_linux/rocky_linux_optimized_gcp_8.wf.json
Labels: size/L, lgtm, approved

#1905 Update RHUI health checks
  OWNERS
  daisy_workflows/build-publish/rhui/health_check.py
Labels: size/L, lgtm, approved

#1909 rhui health check service change
  daisy_workflows/build-publish/rhui/cds_artifacts/rhui-health-check.service
  daisy_workflows/build-publish/rhui/health_check.py
  daisy_workflows/build-publish/rhui/rhua_artifacts/rhui-health-check.service
Labels: size/XS, lgtm, approved

#1911 fix rocky include ref
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_optimized_gcp_8.wf.json
Labels: size/XS, lgtm, approved

#1912 Adding Karn to the owners file
  OWNERS
Labels: size/XS, lgtm, approved

#1913 Configuring power to High performance for SQL Server Image
  daisy_workflows/image_build/sqlserver/sql_install.ps1
Labels: size/S, lgtm, approved

#1914 Remove cloudbuild targets for import/export tools
  cli_tools_cloudbuild.yaml
  gce_image_import_export_tests.Dockerfile
  gce_onestep_image_import.Dockerfile
  gce_ovf_export.Dockerfile
  gce_ovf_export_tests.Dockerfile
  gce_ovf_import.Dockerfile
  gce_ovf_import_tests.Dockerfile
  gce_vm_image_export.Dockerfile
  gce_vm_image_import.Dockerfile
  gcsfuse-apt-key.gpg
  prowjobs_cloudbuild.yaml
  rollout/cli_tools_cloudbuild_build.yaml
  rollout/cli_tools_cloudbuild_release_workflow.yaml
Labels: size/XL, lgtm, approved

#1916 Refresh docs to reflect current tools
  README.md
  cli_tools_tests/e2e/README.md
  daisy_workflows/README.md
  daisy_workflows/import_userguide.md
Labels: size/L, lgtm, approved
