Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-07, with the labels that each got.

#1956 remove EricEdens from OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#1959 Update image name in Windows 10 21h2 publish file
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json
Labels: size/XS, lgtm, approved

#1961 add sdk to el9 build
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_arm64.cfg
Labels: size/S, lgtm, approved

#1962 Update licenses attached to staging images (Windows Enterprise)
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Labels: size/XS, lgtm, approved

#1963 Change Rocky Cloud Kernel repos.
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
Labels: size/S, lgtm, approved

#1964 Update windows client publish workflows
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Labels: size/S, lgtm, approved

#1965 Set the Cloud Kernel repo priority.
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
Labels: size/XS, lgtm, approved

#1967 Fix description string for Rocky Linux 8 Optimized.
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json
Labels: size/XS, lgtm, approved

#1969 Update windows client publish file environment logic
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Labels: size/XS, lgtm, approved

#1954 Rocky Linux 8 Optimized for GCP ARM64.
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
Labels: size/L, lgtm, approved

#1971 Revert "Add workflow status messages so that the Daisy workflow corre…
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/S, lgtm, approved

#1972 Debian 11 worker image build.
  daisy_workflows/build-publish/debian/debian_11_worker.publish.json
  daisy_workflows/build-publish/debian/debian_11_worker.wf.json
  daisy_workflows/image_build/debian/debian_11_worker.wf.json
Labels: size/L, lgtm, approved

#1973 Fix typo.
  daisy_workflows/build-publish/debian/debian_11_worker.publish.json
Labels: size/XS, lgtm, approved

#1974 Fix typo.
  daisy_workflows/build-publish/debian/debian_11_worker.wf.json
Labels: size/XS, lgtm, approved

#1975 One more typo.
  daisy_workflows/build-publish/debian/debian_11_worker.wf.json
  daisy_workflows/image_build/debian/debian_11_worker.wf.json
Labels: size/XS, lgtm, approved

#1977 Fix rocky-linux string match.
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/XS, lgtm, approved

#1978 emit errors in installpackage
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/XS, lgtm, approved

#1979 Update image family for Windows 11 21h2
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json
Labels: size/XS, lgtm, approved

#1980 installpackage.py: relabel whole fs
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/S, lgtm, approved

#1981 Rocky Linux 9 build workflows.
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
Labels: size/XXL, lgtm, approved

#1982 Fix sshd password auth setting.
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
Labels: size/XS, lgtm, approved

#1984 Disable root login by default in Rocky 9.
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
Labels: size/XS, lgtm, approved

#1985 Support windows MTU 1500
  cli_tools/diagnostics/rdp_status.ps1
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
  image_test/configuration/windows/test_config.ps1
Labels: size/S, lgtm, approved

#1986 add arm64 partner exports
  daisy_workflows/build-publish/partner/opensuse_leap_15_arm64.publish.json
  daisy_workflows/build-publish/partner/opensuse_leap_15_arm64_export.wf.json
  daisy_workflows/build-publish/partner/sles_15_arm64.publish.json
  daisy_workflows/build-publish/partner/sles_15_arm64_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_1804_arm64.publish.json
  daisy_workflows/build-publish/partner/ubuntu_1804_arm64_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_2004_arm64.publish.json
  daisy_workflows/build-publish/partner/ubuntu_2004_arm64_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_2204.publish.json
  daisy_workflows/build-publish/partner/ubuntu_2204_arm64.publish.json
  daisy_workflows/build-publish/partner/ubuntu_2204_arm64_export.wf.json
  daisy_workflows/build-publish/partner/ubuntu_2204_export.wf.json
Labels: size/L, lgtm, approved

#1987 fix typo in partner publish wf
  daisy_workflows/build-publish/partner/opensuse_leap_15_arm64.publish.json
Labels: size/XS, lgtm, approved

#1988 fix more typos in partner workflows
  daisy_workflows/build-publish/partner/freebsd_11.publish.json
  daisy_workflows/build-publish/partner/freebsd_12.publish.json
  daisy_workflows/build-publish/partner/freebsd_13.publish.json
  daisy_workflows/build-publish/partner/opensuse_leap_15.publish.json
  daisy_workflows/build-publish/partner/opensuse_leap_15_arm64.publish.json
Labels: size/S, lgtm, approved

#1989 add ubuntu pro 2204 export workflows
  daisy_workflows/build-publish/partner/ubuntu_pro_2204.publish.json
  daisy_workflows/build-publish/partner/ubuntu_pro_2204_export.wf.json
Labels: size/M, lgtm, approved

#1888 Migrate "build and publish" setup for windows-install-media to compute-image-tools
  cli_tools/gce_windows_upgrade/upgrade_script_2008r2_to_2012r2.ps1
  daisy_workflows/build-publish/windows/windows-install-media.publish.json
  daisy_workflows/build-publish/windows/windows-install-media.wf.json
  daisy_workflows/image_build/windows/windows_install_media/components/2012_R2_64Bit/install_unattend.xml
  daisy_workflows/image_build/windows/windows_install_media/components/2012_R2_64Bit/unattend/upgrade_unattend.xml
  daisy_workflows/image_build/windows/windows_install_media/components/2012_R2_64Bit/unattend/upgrade_unattend_core.xml
  daisy_workflows/image_build/windows/windows_install_media/components/2012_R2_64Bit/upgrade.ps1
  daisy_workflows/image_build/windows/windows_install_media/components/2016_64Bit/upgrade.ps1
  daisy_workflows/image_build/windows/windows_install_media/components/2019_64Bit/upgrade.ps1
  daisy_workflows/image_build/windows/windows_install_media/components/2022_64Bit/upgrade.ps1
  daisy_workflows/image_build/windows/windows_install_media/components/common/config.psm1
  daisy_workflows/image_build/windows/windows_install_media/components/common/logging.psm1
  daisy_workflows/image_build/windows/windows_install_media/components/common/setup-logger.ps1
  daisy_workflows/image_build/windows/windows_install_media/prepare_install_media.ps1
Labels: size/XXL, lgtm, approved

#1991 RHEL 8.6 for SAP build.
  daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_6_sap.cfg
  daisy_workflows/image_build/enterprise_linux/rhel_8_6_sap.wf.json
Labels: size/L, lgtm, approved

#1990 Add config, build, and publish files for SQL Server 2022 Preview
  daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/configs/sql_server_2022.ini
  daisy_workflows/image_build/sqlserver/sql-2022-preview-windows-2022-dc.wf.json
Labels: size/L, lgtm, approved

#1992 AlmaLinux 9 image build.
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json
  daisy_workflows/image_build/enterprise_linux/almalinux_9.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9.cfg
Labels: size/L, lgtm, approved
