Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-01, with the labels that each got.

#1829 Adding Lawrence and myself to the owners file
  OWNERS
Labels: size/XS, lgtm, approved

#1828 Moving install_disk_size and drivers_bucket to variables.
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012r2-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-sac-1909-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-sac-2004-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-sac-20h2-dc-core-uefi-payg.wf.json
Labels: size/XL, lgtm, approved

#1811 Optional pass image publish template content in CreatePublish
  cli_tools/gce_image_publish/publish/publish.go
  cli_tools/gce_image_publish/publish/publish_test.go
Labels: size/M, lgtm, approved

#1830 Update Windows Server 2022 Export time to 60 min
  daisy_workflows/build-publish/windows/windows_export.wf.json
Labels: size/XS, lgtm, approved

#1826 RHUA build: use patched Ansible playbook
  daisy_workflows/build-publish/rhui/answers.yaml
  daisy_workflows/build-publish/rhui/fstab
  daisy_workflows/build-publish/rhui/install_rhua.sh
  daisy_workflows/build-publish/rhui/rhua.wf.json
  daisy_workflows/build-publish/rhui/rhua_artifacts/answers.yaml
  daisy_workflows/build-publish/rhui/rhua_artifacts/depend-nfs.conf
  daisy_workflows/build-publish/rhui/rhua_artifacts/reponames.txt
  daisy_workflows/build-publish/rhui/rhua_artifacts/rhua.patch
Labels: size/L, lgtm, approved

#1831 Change the group added to ASSYSADMINACCOUNTS
  daisy_workflows/image_build/sqlserver/configs/sql_server_2012.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2012_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2014.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2014_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2016.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2016_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2017.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2017_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2019.ini
Labels: size/L, lgtm, approved

#1832 Add GVNIC guestOS feature tag to supported images.
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
Labels: size/S, approved

#1825 Validating image URI on image export and setting temporary disk to match the image size.
  cli_tools/common/utils/validation/validation_utils.go
  cli_tools/common/utils/validation/validation_utils_test.go
  cli_tools/gce_vm_image_export/exporter/exporter.go
  cli_tools/gce_vm_image_export/exporter/exporter_test.go
Labels: size/L, lgtm, approved

#1827 CDS build workflow
  daisy_workflows/build-publish/rhui/cds.wf.json
  daisy_workflows/build-publish/rhui/cds_artifacts/answers.yaml
  daisy_workflows/build-publish/rhui/cds_artifacts/cds.patch
  daisy_workflows/build-publish/rhui/cds_artifacts/rhui-tools.conf
  daisy_workflows/build-publish/rhui/install_cds.sh
Labels: size/L, lgtm, approved

#1835 remove han from owners
  OWNERS
Labels: size/XS, lgtm, approved

#1836 Add GVNIC feature flag for CentOS 7.
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
Labels: size/XS, lgtm, approved

#1838 Import e2e: OS config is not supported for Windows 10
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Labels: size/XS, lgtm, approved

#1820 Add sql servers on Windows server 2022 build workflows
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2022-dc-uefi.publish
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2022-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2022-dc-uefi.publish
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2022-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2022-dc-uefi.publish
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2022-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2022-dc-uefi.publish
  daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2022-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2022-dc-uefi.publish
  daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2022-dc.wf.json
  daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2022-dc-uefi.publish
  daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-enterprise-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-web-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-enterprise-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-standard-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2019-web-windows-2022-dc.wf.json
Labels: size/XXL, lgtm

#1837 resolve TODO from tzz: remove out-of-date TODO or create trackers for them
  cli_tools/common/image/importer/inflater.go
  cli_tools/common/image/importer/inflater_test.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools_tests/e2e/gce_image_import_export/test_suites/import/cli_tests.go
Labels: size/S, lgtm, approved
