Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-11, with the labels that each got.

#2025 Add SEV_CAPABLE guestOSFeature to Rocky Linux.
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.publish.json
Labels: size/XS, lgtm, approved

#2026 add testing env to RHUI publish
  daisy_workflows/build-publish/rhui/cds.publish.json
  daisy_workflows/build-publish/rhui/rhua.publish.json
Labels: size/S, lgtm, approved

#2027 Fix typo in install_rhua.sh
  daisy_workflows/build-publish/rhui/install_rhua.sh
Labels: size/XS, lgtm, approved

#2028 correct RHUI publish prefix
  daisy_workflows/build-publish/rhui/cds.publish.json
  daisy_workflows/build-publish/rhui/rhua.publish.json
Labels: lgtm, approved

#2029 fix publish typos
  daisy_workflows/build-publish/rhui/cds.publish.json
  daisy_workflows/build-publish/rhui/rhua.publish.json
Labels: size/XS, lgtm, approved

#2021 Remove LEGACY security config for EL9.
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
Labels: size/M, lgtm, approved

#2030 Windows Server
  daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.wf copy.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-uefi.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-uefi-payg.wf.json
Labels: size/XXL, lgtm, approved

#2033 Windows Server build fixes based on concourse failures
  daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-uefi.wf.json
  daisy_workflows/build-publish/windows_container/windows-2019-core-for-containers-uefi.wf.json
  daisy_workflows/build-publish/windows_container/windows-2019-for-containers-uefi.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2016.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2019.wf.json
  daisy_workflows/image_build/sqlserver/sql-2017-standard-windows-2022.wf.json
Labels: size/S, lgtm, approved

#2034 Update sql2022 install parameters
  daisy_workflows/image_build/sqlserver/configs/sql_server_2022.ini
Labels: size/XS, lgtm, approved

#2004 Kernel Commit Queries
  daisy_workflows/kernel_commit_query/debian.sh
  daisy_workflows/kernel_commit_query/kcq.py
  daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json
  daisy_workflows/kernel_commit_query/rhel.sh
  daisy_workflows/kernel_commit_query/rocky.sh
  daisy_workflows/kernel_commit_query/suse.sh
  daisy_workflows/kernel_commit_query/ubuntu.sh
  daisy_workflows/linux_common/utils/common.py
Labels: size/XL, lgtm, approved

#2037 Add daisy workflows for SQL Server 2022 release versions
  daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2019.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-enterprise-windows-2022.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2019.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-standard-windows-2022.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2019-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2019.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2022-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2022-web-windows-2022.wf.json
Labels: size/XL, lgtm, approved
