Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-06, with the labels that each got.

#1932 Add internal env and associated licenses to windows daisy builds
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
Labels: size/M, lgtm, approved

#1937 make google-rhui-client-rhel9 noarch
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-extensions.txt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9.crt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9.csr
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9.repo
Labels: size/XL, lgtm, approved

#1938 Fix syntax in publish file for core images
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
Labels: size/S, lgtm, approved

#1939 Add in correct repo spec for the Cloud SIG.
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_optimized_gcp_8.cfg
Labels: size/S, lgtm, approved

#1940 split ha repos from el9 rhui config
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-ha.repo
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-ha.spec
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9.repo
Labels: size/L, lgtm, approved

#1942 RHEL9 for ARM64
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/rhel_9_arm64.wf.json
Labels: size/L, lgtm, approved

#1941 Fix RHEL sap workflow references.
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json
Labels: size/S, lgtm, approved

#1943 rhel 9 arm64 build: correct image ref
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.wf.json
Labels: size/XS, lgtm, approved

#1944 install osconfig on arm
  daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
Labels: size/XS, lgtm, approved

#1945 Update URIs to publish project for internal
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
Labels: size/S, lgtm, approved

#1949 CDS: Collect nginx metrics and logs
  daisy_workflows/build-publish/rhui/cds.wf.json
  daisy_workflows/build-publish/rhui/cds_artifacts/config.opsagent.yaml
  daisy_workflows/build-publish/rhui/health_check.nginx.conf
  daisy_workflows/build-publish/rhui/install_cds.sh
  daisy_workflows/build-publish/rhui/install_rhua.sh
  daisy_workflows/build-publish/rhui/rhua.wf.json
  daisy_workflows/build-publish/rhui/rhua_artifacts/config.opsagent.yaml
  daisy_workflows/build-publish/rhui/status.nginx.conf
Labels: size/M, lgtm, approved

#1951 Fix Rocky Linux optimized name/family.
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json
Labels: size/M, lgtm, approved

#1947 Also import the Cloud SIG GPG key.
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
Labels: size/XS, lgtm, approved

#1950 correct health check status
  daisy_workflows/build-publish/rhui/health_check.py
Labels: size/XS, lgtm, approved

#1955 gce_image_publish test fix
  cli_tools/gce_image_publish/publish/publish_test.go
Labels: size/XS, lgtm, approved

#1952 Add daisy workflows for Win8.1 and 10
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-10-21h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-81-ent-x64-uefi.wf.json
Labels: size/L, lgtm, approved

#1953 Add publish files for Win8.1 and 10
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
Labels: size/M, lgtm, approved
