Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-08, with the labels that each got.

#1993 Renaming SSMS variable in SQL 22 publish file
  daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc.wf.json
Labels: size/XS, lgtm, approved

#1994 Revert "Renaming SSMS variable in SQL 22 publish file"
  daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc.wf.json
Labels: size/XS, lgtm, approved

#1995 adjust publish API endpoint for windows-install-media
  daisy_workflows/build-publish/windows/windows-install-media.publish.json
Labels: size/XS, lgtm, approved

#1996 RHEL 9 BYOS image build.
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_byos.cfg
  daisy_workflows/image_build/enterprise_linux/rhel_9_byos.wf.json
Labels: size/L, lgtm, approved

#1997 Change windows staging publish.
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2004-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-20h2-dc-core-uefi.publish.json
Labels: size/M, lgtm, approved

#1998 RHEL 9 for SAP RHUI certs.
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-sap-extensions.txt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-sap.crt
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-sap.csr
  daisy_workflows/build-publish/rhui/rpms/google-rhui-client-rhel9-sap.repo
Labels: size/L, lgtm, approved

#2000 kokoro build workflow
  daisy_workflows/build-publish/kokoro/build.sh
  daisy_workflows/build-publish/kokoro/kokoro.wf.json
Labels: size/L, lgtm, approved

#2001 Fix logic in environment conditional
  daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc-uefi.publish.json
Labels: size/XS, lgtm, approved

#2002 add rpm-sign to kokoro build
  daisy_workflows/build-publish/kokoro/build.sh
Labels: size/XS, lgtm, approved

#1892 [windows upgrade e2e] refactor to support upgrading for more new versions
  cli_tools/gce_windows_upgrade/main.go
  cli_tools/gce_windows_upgrade/upgrade_script.ps1
  cli_tools/gce_windows_upgrade/upgrade_script_2008r2_to_2012r2.ps1
  cli_tools/gce_windows_upgrade/upgrader/test_common_test.go
  cli_tools/gce_windows_upgrade/upgrader/upgrade_paths.go
  cli_tools/gce_windows_upgrade/upgrader/upgrade_paths_test.go
  cli_tools/gce_windows_upgrade/upgrader/upgrader.go
  cli_tools/gce_windows_upgrade/upgrader/utils.go
  cli_tools/gce_windows_upgrade/upgrader/validators.go
  cli_tools/gce_windows_upgrade/upgrader/validators_test.go
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
  cli_tools/gce_windows_upgrade/upgrader/workflows_test.go
  cli_tools/go.mod
  cli_tools_tests/go.sum
  common/go.sum
Labels: size/XL, lgtm, approved
