Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-09, with the labels that each got.

#2003 Revert "Support windows MTU 1500"
  cli_tools/diagnostics/rdp_status.ps1
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
  image_test/configuration/windows/test_config.ps1
Labels: size/S, lgtm, approved

#2005 Fix dockerfile for build failure
  gce_windows_upgrade.Dockerfile
  gce_windows_upgrade_tests.Dockerfile
Labels: size/XS, lgtm, approved

#2006 Add gvnic support to SQL Server Images
  daisy_workflows/build-publish/sqlserver/sql-2012-enterprise-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2012-standard-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2012-web-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2014-standard-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2014-web-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2016-web-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-enterprise-windows-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2012-r2-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-express-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-standard-windows-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2017-web-windows-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2019-enterprise-windows-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2019-standard-windows-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2019-web-windows-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/sqlserver/sql-2022-preview-windows-2022-dc-uefi.publish.json
Labels: size/M, lgtm, approved

#2010 Update timeouts on Server 2016 builds
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
Labels: size/XS, lgtm, approved

#2009 pin rhui package versions
  daisy_workflows/build-publish/rhui/install_cds.sh
  daisy_workflows/build-publish/rhui/install_rhua.sh
Labels: size/XS, lgtm, approved

#2011 RHUI: also pin CDS packages
  daisy_workflows/build-publish/rhui/cds_artifacts/answers.yaml
Labels: size/XS, lgtm, approved

#2007 e2e test for staging windows install media 2008 through 2022
  cli_tools/gce_windows_upgrade/upgrader/upgrade_paths.go
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
  cli_tools_tests/e2e/gce_windows_upgrade/test_suites/windows_upgrade/windows_upgrade_test_suite.go
Labels: size/L, lgtm, approved

#2012 Update post_install.ps1 to skip KB5007651
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2013 windows upgrade test image simplification
  e2e_test_base.Dockerfile
  gce_windows_upgrade_tests.Dockerfile
  prowjobs_cloudbuild.yaml
Labels: size/M, lgtm, approved

#2014 test image build: move global volumes to local
  prowjobs_cloudbuild.yaml
Labels: size/XS, lgtm, approved
