Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-02, with the labels that each got.

#1839 Fix go.mod: each 'replace' needs a corresponding 'require latest'
  cli_tools/go.mod
  common/go.mod
Labels: size/XS, lgtm, approved

#1841 [build] update the dependency verison for cli_tools->common to consume the new common build file
  cli_tools/go.mod
Labels: size/XS, lgtm, approved

#1840 OVF Import: Delete images when instance creation fails
  cli_tools/common/domain/interfaces.go
  cli_tools/common/image/deleter.go
  cli_tools/common/image/deleter_test.go
  cli_tools/common/image/image.go
  cli_tools/common/image/image_test.go
  cli_tools/gce_ovf_import/domain/interfaces.go
  cli_tools/gce_ovf_import/domain/mocks/mock_interfaces.go
  cli_tools/gce_ovf_import/multi_image_importer/multi_image_importer.go
  cli_tools/gce_ovf_import/multi_image_importer/request_executor.go
  cli_tools/gce_ovf_import/multi_image_importer/request_executor_test.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer.go
  cli_tools/gce_ovf_import/ovf_importer/ovf_importer_test.go
  cli_tools/mocks/mock_image_deleter.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go
  cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
Labels: size/XL, approved

#1842 CentOS Stream 9 build
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.wf.json
  daisy_workflows/image_build/enterprise_linux/build_installer.py
  daisy_workflows/image_build/enterprise_linux/centos_stream_9.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/centos-stream-9-options.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el9-packages.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/el9-post.cfg
  daisy_workflows/image_build/enterprise_linux/ks_helpers.py
Labels: size/L, lgtm, approved

#1844 refactor FAI builds
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_10_fai.wf.json
  daisy_workflows/image_build/debian/debian_11_fai.wf.json
  daisy_workflows/image_build/debian/debian_fai.wf.json
  daisy_workflows/image_build/debian/fai_config/files/etc/apt/sources.list.d/google-cloud.list/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/scripts/GCE_CLEAN/10-gce-clean
  daisy_workflows/image_build/debian/fai_config/scripts/GCE_SPECIFIC/12-sshd
  daisy_workflows/image_build/debian/fai_config/sources/GCE_STAGING
  daisy_workflows/image_build/debian/fai_config/sources/GCE_UNSTABLE
  daisy_workflows/image_build/debian/fai_config/sources/file_modes
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_STAGING
  daisy_workflows/image_build/debian/fai_config/sources/repository.GCE_UNSTABLE
Labels: size/L, lgtm, approved

#1846 Users --> BUILTIN\ADMINISTRATORS
  daisy_workflows/image_build/sqlserver/configs/sql_server_2012.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2012_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2014.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2014_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2016.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2016_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2017.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2017_core.ini
  daisy_workflows/image_build/sqlserver/configs/sql_server_2019.ini
Labels: size/S, lgtm, approved

#1848 Add CRB repo to CentOS Stream 9 build.
  daisy_workflows/image_build/enterprise_linux/kickstart/centos-stream-9-options.cfg
Labels: size/XS, lgtm, approved

#1847 Linux import: Improve reliability of e2e tests
  cli_tools_tests/e2e/gce_ovf_import/scripts/ovf_import_test_3_disks.sh
  daisy_integration_tests/scripts/post_translate_test.sh
Labels: size/L, lgtm, approved

#1853 [build] grant permission after build
  rollout/cli_tools_cloudbuild_build.yaml
Labels: size/XS, lgtm, approved

#1852 Daisy: CreateImages: don't validate objects in $OUTS
  daisy/go.mod
  daisy/image.go
Labels: size/XS, lgtm, approved

#1854 chmod +x fai scripts
  daisy_workflows/image_build/debian/build_fai.py
Labels: size/XS, approved

#1856 [os-upgrade] machine image dependency: move from Beta to GA
  cli_tools/gce_windows_upgrade/upgrader/workflows.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/mocks/mock_compute_client.go
  cli_tools_tests/go.mod
  cli_tools_tests/go.sum
  common/gcp/instance.go
  common/go.mod
  common/go.sum
  daisy/compute/compute.go
  daisy/compute/compute_test.go
  daisy/compute/test_client.go
  daisy/compute/test_client_test.go
  daisy/go.mod
  daisy/go.sum
  daisy/instance.go
  daisy/machineimage.go
  daisy/machineimage_test.go
  daisy/step_create_machine_images_test.go
  daisy/test_common_test.go
  daisy/workflow_test.go
Labels: size/XL, lgtm, approved

#1859 Debian builds: force GNU format tarball
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_11_arm.wf.json
  daisy_workflows/image_build/debian/repack.py
Labels: size/L, lgtm, approved

#1860 Rename arm->arm64
  daisy_workflows/build-publish/debian/debian_11_arm64.publish.json
  daisy_workflows/build-publish/debian/debian_11_arm64.wf.json
  daisy_workflows/image_build/debian/debian_11_arm64.wf.json
Labels: size/XS, lgtm, approved

#1862 ARM64 renames
  daisy_workflows/build-publish/debian/debian_11_arm64.publish.json
  daisy_workflows/build-publish/debian/debian_11_arm64.wf.json
  daisy_workflows/image_build/debian/debian_11_arm64.wf.json
Labels: size/S, lgtm, approved

#1861 [gce_image_import_export] fix e2e test build
  cli_tools_tests/go.sum
Labels: size/XS, lgtm, approved

#1867 add new vals to rhua answers
  daisy_workflows/build-publish/rhui/rhua_artifacts/answers.yaml
Labels: size/XS, lgtm, approved
