Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2022-12, with the labels that each got.

#2035 Almalinux sbom changes and test
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
  daisy_workflows/export/export_sbom.sh
  image_test/sbom/README.md
  image_test/sbom/enterprise_sbom_test.wf.json
  image_test/sbom/test_sbom_export.sh
Labels: size/L, lgtm, approved

#2042 Revert the debian worker image for disk_export due to a potential race
  daisy_workflows/export/disk_export.wf.json
Labels: size/XS, lgtm, approved

#2043 remove run_sbom_bool, avoid sbom generation on EL9 until debian worke…
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
  image_test/sbom/enterprise_sbom_test.wf.json
Labels: size/M, lgtm, approved

#2044 Add Anthony to owners
  OWNERS
Labels: size/XS, lgtm, approved

#2046 Use disk export subworkflow in Debian 10
  daisy_workflows/build-publish/debian/debian_10.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.wf.json
Labels: size/S, lgtm, approved

#2047 export-metadata: regex and case sensitive match Version Source
  daisy_workflows/export_metadata/export-metadata.ps1
Labels: size/XS, lgtm, approved

#2049 kcq: don't export upstream kernel patches for Changelog analysis
  daisy_workflows/kernel_commit_query/kcq.py
Labels: size/XS, lgtm, approved

#2051 Correcting family name
  daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.publish.json
Labels: size/XS, lgtm, approved

#2052 sbom generation for a few more Enterprise Linux workflows
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.wf.json
Labels: size/M, lgtm, approved

#2048 SBOM and disk export changes to debian 11
  daisy_workflows/build-publish/debian/debian_11.wf.json
  daisy_workflows/build-publish/debian/debian_11_arm64.wf.json
Labels: size/M, lgtm, approved

#2053 rhel SBOM generation excluding rhel9
  daisy_workflows/build-publish/enterprise_linux/rhel_7_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
Labels: size/M, lgtm, approved

#2055 Fixing Windows Container build typo
  daisy_workflows/build-publish/windows_container/windows-2019-dc-core-for-containers-uefi.wf.json
  daisy_workflows/build-publish/windows_container/windows-2019-dc-for-containers-uefi.wf.json
Labels: size/XS, lgtm, approved

#2056 kernel commit query: fix workflow json file
  daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json
Labels: size/XS, lgtm, approved

#2050 Add Cloud Metrics for RHUA sync status.
  daisy_workflows/build-publish/rhui/install_rhua.sh
  daisy_workflows/build-publish/rhui/rhua_artifacts/rhua-sync-status.service
  daisy_workflows/build-publish/rhui/rhua_artifacts/rhua-sync-status.timer
  daisy_workflows/build-publish/rhui/rhua_sync_status.py
Labels: size/L, lgtm, approved

#2058 Update timeout threshold for Win11 builds
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-11-21h2-ent-x64-uefi.wf.json
Labels: size/XS, lgtm, approved

#2057 RHUA use single enrollment cert
  daisy_workflows/build-publish/rhui/install_cds.sh
  daisy_workflows/build-publish/rhui/install_rhua.sh
Labels: size/S, lgtm, approved

#2059 add script to rhua_artifacts
  daisy_workflows/build-publish/rhui/rhua_artifacts/rhua_sync_status.py
Labels: size/XS, lgtm, approved

#2060 Kernel Commit Query: add machine_type workflow argument
  daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json
Labels: size/XS, lgtm, approved

#2061 Kernel Commit Query: fix kcq.py invocation from debian wrapper
  daisy_workflows/kernel_commit_query/debian.sh
Labels: size/XS, lgtm, approved

#2062 Add WorkProject vars to RHUI publish workflows.
  daisy_workflows/build-publish/rhui/cds.publish.json
  daisy_workflows/build-publish/rhui/rhua.publish.json
Labels: size/XS, lgtm, approved

#2063 Kernel Commit Query: extend time out to 40m
  daisy_workflows/kernel_commit_query/kernel_commit_query.wf.json
Labels: size/XS, lgtm, approved
