Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2023-11, with the labels that each got.

#2239 Update owners.
  OWNERS
Labels: size/XS, lgtm, approved

#2240 RHEL BYOS change to include RHUI and subscription manager.
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_2_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_4_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_6_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_8_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_0_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_2_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_byos_arm64.cfg
Labels: size/M, lgtm, approved

#2242 Use /kaniko as a build dir for windows upgrade image
  gce_windows_upgrade_tests.Dockerfile
Labels: size/XS, lgtm, approved

#2244 Update golang and deps for cli_tools
  cli_tools/common/disk/mocks/mock_inspect.go
  cli_tools/common/domain/interfaces.go
  cli_tools/common/mount/inspector.go
  cli_tools/common/utils/daisyutils/daisy_utils.go
  cli_tools/common/utils/daisyutils/workflow_hook_no_external_ip.go
  cli_tools/common/utils/daisyutils/workflow_hook_resource_labeler.go
  cli_tools/common/utils/daisyutils/workflow_hook_workflow_vars.go
  cli_tools/common/utils/logging/logger.go
  cli_tools/common/utils/param/network_resolver.go
  cli_tools/common/utils/storage/buffered_writer_test.go
  cli_tools/common/utils/storage/storage_client_test.go
  cli_tools/common/utils/test/test_utils.go
  cli_tools/common/utils/validation/validation_utils.go
  cli_tools/go.mod
  cli_tools/go.sum
  cli_tools/mocks/mock_bucket_iterator.go
  cli_tools/mocks/mock_logger.go
  cli_tools_tests/go.mod
  cli_tools_tests/go.sum
  common/runtime/config.go
  proto/go/pb/inspect.pb.go
  proto/go/pbtesting/gomock_matcher.go
Labels: size/XXL, lgtm, approved
