Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2023-06, with the labels that each got.

#2164 add windows sbom gen on ps1 uefi script
  daisy_workflows/build-publish/sqlserver/sql-2014-enterprise-windows-2012-r2.wf.json
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/sqlserver/sql-2014-enterprise-windows-2012-r2.wf.json
  daisy_workflows/image_build/sqlserver/sqlserver.wf.json
  daisy_workflows/image_build/windows/windows-10-21h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-build-uefi.wf.json
Labels: size/M, lgtm, approved

#2165 Fix gspath
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/XS, lgtm, approved

#2166 Remove backslash on windows path
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/XS, lgtm, approved

#2167 Use sbomutil.exe instead of sbomutil on windows
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/XS, lgtm, approved

#2168 Pass in component name for windows sboms
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/XS, lgtm, approved

#2169 Revert our netplan config in favor of the fixed upstream one.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/files/etc/netplan/90-default.yaml/BOOKWORM
Labels: size/S, lgtm, approved

#2170 Pass in sbom variables to windows templates
  daisy_workflows/image_build/windows/windows-10-20h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-11-21h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-81-ent-x64-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2012-r2-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2016-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2019-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2022-uefi-payg.wf.json
Labels: size/L, lgtm, approved

#2173 remove multithreading for single file upload on gsutil
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/XS, lgtm, approved

#2177 Add correct variable for sbom root
  daisy_workflows/build-publish/sqlserver/sql-2016-enterprise-windows-2019-dc.wf.json
Labels: size/XS, lgtm, approved

#2171 Add skeleton for sql sbom generation
  daisy_workflows/image_build/sqlserver/sql_install.ps1
  daisy_workflows/image_build/sqlserver/sqlserver.wf.json
Labels: size/M, lgtm, approved

#2178 Don't use basearch or releasever variables.
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_8.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
Labels: size/L, lgtm, approved

#2179 2016 sql server sbom generation
  daisy_workflows/build-publish/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
  daisy_workflows/image_build/sqlserver/sql_install.ps1
  daisy_workflows/image_build/sqlserver/sqlserver.wf.json
Labels: size/M, lgtm, approved

#2176 Do not replace windows sbom with empty sbom
  daisy_workflows/build-publish/windows/windows_export.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
Labels: size/S, lgtm, approved

#2180 Add SIG Cloud Kernel source repo configs for Rocky Linux
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
Labels: size/M, lgtm, approved

#2182 Don't delete the old RHEL 7.9 for SAP images.
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.publish.json
Labels: size/XS, lgtm, approved

#2183 Add workaround to .Net install issue June 2023
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2184 Add dollar sign
  daisy_workflows/image_build/sqlserver/sql-2016-standard-windows-2016-dc.wf.json
Labels: size/XS, lgtm, approved

#2175 Generate windows sboms
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-uefi.wf.json
Labels: size/L, lgtm, approved

#2185 Revert "Do not replace windows sbom with empty sbom"
  daisy_workflows/build-publish/windows/windows_export.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
Labels: size/S, lgtm, approved

#2186 Correctly reference driver directory
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/XS, lgtm, approved

#2187 Do not overwrite windows sboms at the end
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows_export.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
Labels: size/M, lgtm, approved

#2188 Pass in existing file name for robust sbom naming
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-81-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2016-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2019-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2022-uefi.wf.json
Labels: size/M, lgtm, approved

#2192 Fix bug with sbom destination name
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2012-r2-dc-uefi.wf.json
Labels: size/XS, lgtm, approved

#2193 download extra content for sql server sboms
  daisy_workflows/image_build/sqlserver/sql_install.ps1
Labels: size/S, lgtm, approved

#2194 Move windows iso and other files to sbom folder
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/S, lgtm, approved

#2195 Rename sbomcontents to sbomcomponents for consistency with windows
  daisy_workflows/image_build/sqlserver/sql_install.ps1
Labels: size/XS, lgtm, approved

#2196 Update README.md for sbom testing
  daisy_workflows/sbom_validation/README.md
Labels: size/XS, lgtm, approved

#2197 Update README.md for sbom generation
  daisy_workflows/image_build/windows/README.md
Labels: size/XS, lgtm, approved

#2199 Allow image export to generate sboms
  daisy_workflows/export/image_export.wf.json
Labels: size/S, lgtm, approved

#2198 Update README.md with sbom variables
  daisy_workflows/image_build/sqlserver/README.md
Labels: size/XS, lgtm, approved

#2200 Update README.md with sbom variables for export
  daisy_workflows/export/README.md
Labels: size/S, lgtm, approved

#2202 Do not add sbomutil.exe to the sbom
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/XS, lgtm, approved

#2201 Add "autopush" environment to all debian and enterprise linux publish workflows
  daisy_workflows/build-publish/debian/debian_10.publish.json
  daisy_workflows/build-publish/debian/debian_11.publish.json
  daisy_workflows/build-publish/debian/debian_11_arm64.publish.json
  daisy_workflows/build-publish/debian/debian_12.publish.json
  daisy_workflows/build-publish/debian/debian_12_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.publish.json
Labels: size/L, lgtm, approved
