Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2023-05, with the labels that each got.

#2126 AlmaLinux 9 for ARM64
  daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/almalinux_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9_arm64.cfg
Labels: size/L, lgtm, approved, ok-to-test

#2128 Update licenses in Windows Container build workflows
  daisy_workflows/build-publish/windows_container/windows-server-2019-core-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-ce-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-ce-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-for-containers-uefi.publish.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-ce-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-ce-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers.wf.json
Labels: size/L, lgtm, approved

#2127 Update AlmaLinux guest_features to match RHEL
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.publish.json
Labels: size/XS, lgtm, approved, ok-to-test

#2130 Add image families to Docker CE workflows
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-core-for-containers-ce-uefi.publish.json
  daisy_workflows/build-publish/windows_container/windows-server-2019-dc-for-containers-ce-uefi.publish.json
Labels: size/XS, lgtm, approved

#2129 Update Docker install scripts for Container images
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
  daisy_workflows/image_build/windows_for_containers/container_image_install_ce.ps1
Labels: size/L, lgtm, approved

#2131 Fix container_install.ps1
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
Labels: size/M, lgtm, approved

#2132 Update sql_install.ps1 to fix SSMS and Engine install
  daisy_workflows/image_build/sqlserver/sql_install.ps1
Labels: size/XS, lgtm, approved

#2133 Don't install the backports kernel for Debian 10.
  daisy_workflows/image_build/debian/build_fai.py
Labels: size/XS, lgtm, approved

#2134 Update container build workflows and script for Mirantis license
  daisy_workflows/image_build/windows_for_containers/container_image_install.ps1
  daisy_workflows/image_build/windows_for_containers/windows-2019-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-for-containers-uefi.wf.json
Labels: size/M, lgtm, approved

#2135 Add Google Cloud SAP agent to RHEL for SAP builds.
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_7_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_9_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_1_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_2_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_4_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_6_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_0_sap.cfg
Labels: size/M, lgtm, approved

#2136 Updating build-publish workflow to pass the docker_license_file variable
  daisy_workflows/build-publish/windows_container/windows-2019-dc-core-for-containers-uefi.wf.json
  daisy_workflows/build-publish/windows_container/windows-2019-dc-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json
Labels: size/S, lgtm, approved

#2137 Adding source file and removing metadata entry
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-core-for-containers-uefi.wf.json
  daisy_workflows/image_build/windows_for_containers/windows-2019-dc-for-containers-uefi.wf.json
Labels: size/S, lgtm, approved

#2140 Make sure we reference the right partitions for all debian images
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/XS, lgtm, approved

#2139 Add skeleton for sbom-util SBOM generation path
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
  daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
Labels: size/M, lgtm, approved

#2143 Fix empty sbom bug
  daisy_workflows/export/export_disk.sh
Labels: size/XS, lgtm, approved

#2142 Bookworm fixes
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/files/etc/hostname/BOOKWORM
  daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
Labels: size/S, lgtm, approved

#2144 Add logging for sbomutil export
  daisy_workflows/export/export_disk.sh
Labels: size/XS, lgtm, approved

#2145 Add log for sbom util root
  daisy_workflows/export/export_disk.sh
Labels: size/XS, lgtm, approved

#2146 Debug gsutil ls
  daisy_workflows/export/export_disk.sh
Labels: size/XS, lgtm, approved

#2147 Echo the list repositories command input
  daisy_workflows/export/export_disk.sh
Labels: size/XS, lgtm, approved

#2150 remove unnecessary echo
  daisy_workflows/export/export_disk.sh
Labels: size/XS, lgtm, approved

#2149 Use chrony for ntp (as before).
  daisy_workflows/image_build/debian/build_fai.py
Labels: size/XS, lgtm, approved

#2152 Remove syft sbom generation mode, deprecated
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/export/export_disk.sh
Labels: size/M, lgtm, approved

#2151 sbom: add required code to generate sboms for windows
  daisy_workflows/image_build/windows/bootstrap_install.ps1
Labels: size/M, lgtm, approved

#2153 Remove syft source from build publish workflows
  daisy_workflows/build-publish/debian/debian_10.wf.json
  daisy_workflows/build-publish/debian/debian_11.wf.json
  daisy_workflows/build-publish/debian/debian_11_arm64.wf.json
  daisy_workflows/build-publish/debian/debian_12.wf.json
  daisy_workflows/build-publish/debian/debian_12_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_8_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_0_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/sbom_validation/README.md
Labels: size/L, lgtm, approved

#2155 Debian build fixes for Bookworm
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/files/etc/hostname/BOOKWORM
  daisy_workflows/image_build/debian/fai_config/files/etc/netplan/90-default.yaml/BOOKWORM
  daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/scripts/BOOKWORM/10-clean
  daisy_workflows/image_build/debian/fai_config/scripts/GCE_CLEAN/10-gce-clean
Labels: size/M, lgtm, approved

#2156 Make the bookworm cleanup script executable.
  daisy_workflows/image_build/debian/build_fai.py
Labels: size/XS, lgtm, approved

#2157 Include dhclient in the Debian builds.
  daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
Labels: size/XS, lgtm, approved

#2160 Add SEV_CAPABLE to Debian 11.
  daisy_workflows/build-publish/debian/debian_11.publish.json
Labels: size/XS, lgtm, approved

#2162 Remove unnecessary variable from presubmit
  daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
Labels: size/XS, lgtm, approved
