Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2023-08, with the labels that each got.

#2215 Adding workflows for Win10 32-bit (22h2)
  daisy_workflows/image_build/windows/post_install.ps1
  daisy_workflows/image_build/windows/windows-10-21h2-ent-x86-bios.wf.json
  daisy_workflows/image_build/windows/windows-10-22h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-10-22h2-ent-x86-bios.wf.json
  daisy_workflows/image_build/windows/windows-build-bios.wf.json
Labels: size/L, lgtm, approved

#2216 Remove bginfo from Windows builds
  daisy_workflows/image_build/windows/post_install.ps1
  daisy_workflows/image_build/windows/windows-build-bios.wf.json
  daisy_workflows/image_build/windows/windows-build-uefi.wf.json
Labels: size/M, lgtm, approved

#2217 Create publish workflows for W10 22h2 and 21h2
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x86-bios.publish.json
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x86-bios.wf.json
  daisy_workflows/build-publish/windows/windows-10-22h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-10-22h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-10-22h2-ent-x86-bios.publish.json
  daisy_workflows/build-publish/windows/windows-10-22h2-ent-x86-bios.wf.json
Labels: size/L, lgtm, approved

#2218 Switch debian 12+sid to systemd-timesyncd
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/files/etc/chrony/chrony.conf/GCE_SPECIFIC
  daisy_workflows/image_build/debian/fai_config/files/etc/systemd/timesyncd.conf.d/01_debian_cloud.conf/GCE_SPECIFIC
Labels: size/M, lgtm, approved

#2219 Update owners.
  OWNERS
Labels: size/XS, lgtm, approved

#2221 Remove install_disk var from enterprise linux workflows
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_8_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_0_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
Labels: size/S, lgtm, approved

#2222 Update source disk for enterprise build-publish workflows
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_7.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_7_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_9_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_7_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_1_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_4_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_8_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_0_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_2_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
Labels: size/M, lgtm, approved

#2223 Remove reference to acrate-dev-build bucket
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.wf.json
Labels: size/XS, lgtm, approved

#2225 Reference installer disk by id in rhel kickstart config
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_4_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_6_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_7_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_9_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_7_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_1_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_2_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_4_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_6_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_8_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_0_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_2_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_byos.cfg
Labels: size/M, lgtm, approved
