Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2024-01, with the labels that each got.

#2250 Tag images that contain kernel commit 43955a1a2 with SEV_LIVE_MIGRATABLE_V2
  daisy_workflows/build-publish/enterprise_linux/rhel_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json
  daisy_workflows/image_build/enterprise_linux/rhel_8.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9.wf.json
Labels: size/S, lgtm, approved

#2252 Add an image build workflow for centos 7 with predictable NIC names
  daisy_workflows/image_build/enterprise_linux/centos_7_predictable_nic.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_7_predictable_nic.cfg
Labels: size/L, lgtm, approved

#2253 Add image publish workflow for centos-7-predictable-nic
  daisy_workflows/build-publish/enterprise_linux/centos_7_predictable_nic.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_7_predictable_nic.wf.json
Labels: size/L, lgtm, approved

#2255 Fix centos-7-predictable-nic publish template name
  daisy_workflows/build-publish/enterprise_linux/centos_7_predictable_nic.publish.json
Labels: size/XS, lgtm, approved

#2254 Migrating all netsh commands to PowerShell for win10/2016 and above
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/M, lgtm, approved

#2256 Fixing copy/pasta error between scripts
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2258 Install python38 on rocky 8 optimized gcp arm64
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
Labels: size/XS, lgtm, approved

#2259 Update timeout for W10 21H2
  daisy_workflows/build-publish/windows/windows-10-21h2-ent-x64-uefi.wf.json
Labels: size/XS, lgtm, approved

#2260 Exclude KB5034439 from Server 2022 builds
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2261 Tag rocky 8/9 optimized with SEV_LIVE_MIGRATABLE_V2
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp.publish.json
Labels: size/XS, lgtm, approved

#2263 Revert "Install python38 on rocky 8 optimized gcp arm64 (#2258)"
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
Labels: size/XS, lgtm, approved

#2265 Remove quintonamore from OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#2266 Update CentOS Stream 9 guest os features.
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json
Labels: size/XS, lgtm, approved
