Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2024-04, with the labels that each got.

#2293 Adding MicrosoftEdgeUpdateTaskMachineUA task trigger
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2295 Disabling hibernate to prevent Hybrid Sleep
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2297 Updating windows builds to run on n2 for Windows 11 CPU support
  daisy_workflows/image_build/windows/windows-build-uefi.wf.json
Labels: size/XS, lgtm, approved

#2298 Move Debian 10 backports repo to archive.debian.org
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/hooks/repository.BUSTER
  daisy_workflows/image_build/debian/fai_config/hooks/repository.GCE_SPECIFIC
Labels: size/XS, lgtm, approved

#2299 Debian 12 worker image build.
  daisy_workflows/build-publish/debian/debian_12_worker.publish.json
  daisy_workflows/build-publish/debian/debian_12_worker.wf.json
  daisy_workflows/build-publish/debian/debian_12_worker_arm64.publish.json
  daisy_workflows/build-publish/debian/debian_12_worker_arm64.wf.json
  daisy_workflows/image_build/debian/debian_12_worker.wf.json
  daisy_workflows/image_build/debian/debian_12_worker_arm64.wf.json
  daisy_workflows/image_build/debian/debian_worker.sh
Labels: size/L, lgtm, approved

#2300 Remove buster backports.
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/fai_config/files/etc/apt/sources.list/BUSTER
  daisy_workflows/image_build/debian/fai_config/hooks/repository.BUSTER
Labels: size/S, lgtm, approved

#2296 Check in guest agent replacement scripts for COS images under /install_packages
  daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
  daisy_workflows/image_build/install_package/cos/package_replacement/dev_cloudbuild.yaml
  daisy_workflows/image_build/install_package/cos/package_replacement/disable_readonly_rootfs.sh
  daisy_workflows/image_build/install_package/cos/package_replacement/enable_readonly_rootfs.sh
  daisy_workflows/image_build/install_package/cos/package_replacement/install_go.sh
  daisy_workflows/image_build/install_package/cos/package_replacement/preload.sh
Labels: size/L, lgtm, approved, ok-to-test
