Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2024-07, with the labels that each got.

#2335 Use 20 GB so windows image copy has enough space
  daisy_workflows/export/disk_export.wf.json
Labels: size/XS, lgtm, approved

#2336 Use 40 GB daisy instance
  daisy_workflows/export/disk_export.wf.json
Labels: size/XS, lgtm, approved

#2337 Update almalinux-8 & rocky-linux-9 to add IDPF
  daisy_workflows/build-publish/enterprise_linux/almalinux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9.publish.json
Labels: size/XS, lgtm, approved

#2338 Update Edge update logic to wait until it finds a newer version
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/M, lgtm, approved

#2339 Pass worker image in as an arg
  daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json
Labels: size/XS, lgtm, approved, ok-to-test

#2340 Add a -date_version option that sets the publish version to vYYYYMMDD
  cli_tools/gce_image_publish/main.go
Labels: size/XS, lgtm, approved

#2341 Revert "Drop SEV_SNP_CAPABLE from centos-stream-9 images (#2325)"
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json
Labels: size/XS, lgtm, approved

#2342 Drop SEV_CAPABLE from Debian 11
  daisy_workflows/build-publish/debian/debian_11.publish.json
Labels: size/XS, lgtm, approved
