Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2024-02, with the labels that each got.

#2267 Windows Server 2025 image build workflows
  daisy_workflows/image_build/windows/windows-server-2025-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-uefi-payg.wf.json
Labels: size/XXL, lgtm, approved

#2268 Server 2025 Build Publish
  daisy_workflows/build-publish/windows/windows-server-2025-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2025-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-uefi.wf.json
Labels: size/XL, lgtm, approved

#2269 Change enterprise linux serial console to 115200
  daisy_workflows/image_build/enterprise_linux/build_installer.py
Labels: size/XS, lgtm, approved

#2270 Workaround for PS Module Path
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2272 RHEL9 for C3M
  daisy_workflows/build-publish/enterprise_linux/rhel_9_c3m.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_c3m.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_c3m.cfg
  daisy_workflows/image_build/enterprise_linux/rhel_9_c3m.wf.json
Labels: size/L, lgtm, approved

#2273 Moving to install drivers first
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2274 Revert "Moving to install drivers first"
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/S, lgtm, approved

#2275 Tag debian 12 with SEV_SNP_CAPABLE and SEV_LIVE_MIGRATABLE_V2
  daisy_workflows/build-publish/debian/debian_12.publish.json
Labels: size/XS, lgtm, approved

#2276 Updating windows build timeouts to 7 hours
  daisy_workflows/build-publish/windows/windows-11-21h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-11-22h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-11-23h2-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-11-preview-ent-x64-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2025-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-core-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-2025-uefi.wf.json
  daisy_workflows/build-publish/windows/windows-server-next-dc-uefi.wf.json
  daisy_workflows/image_build/windows/windows-11-21h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-11-22h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-11-23h2-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-11-preview-ent-x64-uefi.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-core-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-preview-dc-uefi-payg.wf.json
Labels: size/M, lgtm, approved

#2277 Add c3 baremetal preview daisy workflows for ubuntu and centos stream 9
  daisy_workflows/build-publish/bare_metal/ubuntu2004_c3metal.publish.json
  daisy_workflows/build-publish/bare_metal/ubuntu2004_c3metal.wf.json
  daisy_workflows/build-publish/bare_metal/ubuntu2204_c3metal.publish.json
  daisy_workflows/build-publish/bare_metal/ubuntu2204_c3metal.wf.json
  daisy_workflows/image_build/bare_metal/build_installer.py
  daisy_workflows/image_build/bare_metal/c3metal-centos_stream_9.wf.json
  daisy_workflows/image_build/bare_metal/c3metal-ubuntu.wf.json
  daisy_workflows/image_build/bare_metal/c3metal-ubuntu_preparer.sh
  daisy_workflows/image_build/bare_metal/enterprise_linux.wf.json
  daisy_workflows/image_build/bare_metal/kickstart/centos_stream_9.cfg
Labels: size/XL, lgtm, approved

#2278 remove unused rhel 9 c3metal daisy workflows
  daisy_workflows/build-publish/enterprise_linux/rhel_9_c3m.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_c3m.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_c3m.cfg
  daisy_workflows/image_build/enterprise_linux/rhel_9_c3m.wf.json
Labels: size/L, lgtm, approved

#2279 Splitting the driver/app package installations
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/M, lgtm, approved
