Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2024-11, with the labels that each got.

#2390 Fix RHEL 8.4 for SAP build (doesn't build correctly with nvme).
  daisy_workflows/image_build/enterprise_linux/rhel_8_4_sap.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_4_sap_byos.wf.json
Labels: size/XS, lgtm, approved

#2391 Remove IPv4 hard coded config from dnf.
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_8.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/almalinux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_10_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_10_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_4_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_4_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_6_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_6_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_8_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_8_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_byos_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_0_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_0_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_2_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_2_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_4_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_4_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_byos.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_byos_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_arm64.cfg
Labels: size/L, lgtm, approved

#2392 Accelerators: move rocky builds under EL Linux; Remove ubuntu
  daisy_workflows/build-publish/accelerator_images/ubuntu_2204_with_nvidia_550.publish.json
  daisy_workflows/build-publish/accelerator_images/ubuntu_2204_with_nvidia_550.wf.json
  daisy_workflows/build-publish/accelerator_images/ubuntu_2404_with_nvidia_550.publish.json
  daisy_workflows/build-publish/accelerator_images/ubuntu_2404_with_nvidia_550.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_550.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_550.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_with_nvidia_550.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_with_nvidia_550.wf.json
  daisy_workflows/image_build/accelerator_images/ubuntu_2204_with_nvidia_550.wf.json
  daisy_workflows/image_build/accelerator_images/ubuntu_2404_with_nvidia_550.wf.json
  daisy_workflows/image_build/enterprise_linux/build_rocky_linux_8_optimized_gcp_accelerated.sh
  daisy_workflows/image_build/enterprise_linux/build_rocky_linux_9_optimized_gcp_accelerated.sh
  daisy_workflows/image_build/enterprise_linux/rocky_accelerated.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_550.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_with_nvidia_550.wf.json
Labels: size/L, lgtm, approved

#2393 Go back to using e2 machine types for x86_64 EL builds.
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
Labels: size/XS, lgtm, approved

#2394 Set the worker image to the correct architecture.
  daisy_workflows/image_build/enterprise_linux/almalinux_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_stream_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_byos_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
Labels: size/M, lgtm, approved

#2395 Updating build to install gvnic dq on 2016
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2396 Updating to Install GVNIC DQ on 2016/2025, for 2019/2022 install GQ.
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2398 Fork accelerator builds to use the EL + kickstart build
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator.cfg
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_550.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.wf.json
Labels: size/L, lgtm, approved

#2399 Updating to debian-12-worker
  daisy_workflows/export/image_export_ext.wf.json
Labels: size/XS, lgtm, approved

#2400 Fix image family in rocky EL build
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.wf.json
Labels: size/XS, lgtm, approved

#2401 Fix rocky 8 accelerated image family
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.wf.json
Labels: size/XS, lgtm, approved

#2403 sleep after netkvm and gvnic install
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2406 Use persistent NIC names for accelerator images
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_accelerator.cfg
Labels: size/XS, lgtm, approved

#2407 Fix rocky 8/9 accelerator publish workflow and template locations
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_with_nvidia_latest.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_with_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_with_nvidia_latest.wf.json
Labels: size/XS, lgtm, approved

#2408 Fix rocky accelerator package names
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_accelerator.cfg
Labels: size/XS, lgtm, approved

#2334 Fix shell script variable syntax
  daisy_workflows/export/export_disk.sh
Labels: size/XS, lgtm, approved

#2410 Drop with in accelerator filenames
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.wf.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.wf.json
Labels: size/XS, lgtm, approved

#2411 Updating publish workflows for 2025
  daisy_workflows/build-publish/windows/windows-server-2025-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-core-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-uefi.publish.json
  daisy_workflows/image_build/windows/post_install.ps1
  daisy_workflows/image_build/windows/windows-server-2025-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-core-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-dc-uefi-payg.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-uefi-byol.wf.json
  daisy_workflows/image_build/windows/windows-server-2025-uefi-payg.wf.json
Labels: size/S, lgtm, approved

#2412 Use packages for repo configuration instead of writing it manually
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_accelerator.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp_accelerator.cfg
Labels: size/M, lgtm, approved

#2414 Disable APT Daily on Debian worker image to avoid APT lock contention
  daisy_workflows/image_build/debian/debian_worker.sh
Labels: size/XS, lgtm, approved

#2415 Update Rocky accelerators with prod publish configuration
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
Labels: size/S, lgtm, approved

#2416 Disable the eclipse module for RHEL 8 aarch64 to avoid warnings from dnf.
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_8_arm64.cfg
Labels: size/XS, lgtm, approved
