Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2024-10, with the labels that each got.

#2372 Update windows-11-24h2-ent-x64-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-11-24h2-ent-x64-uefi.publish.json
Labels: size/XS, lgtm, approved

#2373 Fix kernel source path in accelerator scripts
  daisy_workflows/image_build/accelerator_images/build_rocky_linux_8_optimized_gcp_accelerated.sh
  daisy_workflows/image_build/accelerator_images/build_rocky_linux_9_optimized_gcp_accelerated.sh
Labels: size/S, lgtm, approved

#2374 Use open drivers and modules-extra metapackages on ubuntu accelerators
  daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh
  daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
Labels: size/XS, lgtm, approved

#2376 Fix misspelling of linux-modules-extra-gcp
  daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
Labels: size/XS, lgtm, approved

#2375 Scripts to do offline remediation of Windows instances.
  gce_recovery_scripts/README.md
  gce_recovery_scripts/recover_windows_instance.sh
  gce_recovery_scripts/reinstall-gvnic-gq.ps1
Labels: size/L, lgtm, approved

#2378 Adding Windows BYOL publish files
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2019-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2022-dc-uefi.publish.json
  daisy_workflows/build-publish/windows/windows-server-2025-dc-uefi.publish.json
Labels: size/M, lgtm, approved

#2379 Resolve dependencies when building derivative images with installpackage
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/S, lgtm, approved

#2380 Switch to debian 12 worker
  daisy_workflows/export/disk_export.wf.json
  daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
  daisy_workflows/sbom_validation/windows_sbom_validation.wf.json
Labels: size/XS, lgtm, approved

#2381 Update image_export.wf.json to use the debian 12 worker
  daisy_workflows/export/image_export.wf.json
Labels: size/XS, lgtm, approved

#2382 Use the debian 12 worker instead of debian 10 or 9
  cli_tools/common/utils/daisyutils/daisy_utils_test.go
  daisy_workflows/export/disk_export_ext.wf.json
  daisy_workflows/export_metadata/export_metadata.wf.json
  daisy_workflows/image_build/README.md
  daisy_workflows/image_build/enterprise_linux/README.md
Labels: size/S, lgtm, approved

#2383 Updating metadata.google.internal to 169.254.169.254
  daisy_workflows/image_build/windows/bootstrap_install.ps1
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2384 Removing the custom prefix as it's used in the gcs path
  daisy_workflows/build-publish/windows/windows-server-2016-dc-uefi.publish.json
Labels: size/XS, lgtm, approved

#2377 Build Ubuntu preview images from official Canonical images
  daisy_workflows/image_build/accelerator_images/build_ubuntu_2204_accelerated.sh
  daisy_workflows/image_build/accelerator_images/build_ubuntu_2404_accelerated.sh
  daisy_workflows/image_build/accelerator_images/ubuntu_2204_with_nvidia_550.wf.json
  daisy_workflows/image_build/accelerator_images/ubuntu_2404_with_nvidia_550.wf.json
  daisy_workflows/image_build/accelerator_images/ubuntu_accelerated.wf.json
Labels: size/L, lgtm, approved

#2388 Fix typo.
  daisy_workflows/image_build/enterprise_linux/enterprise_linux.wf.json
Labels: size/XS, lgtm, approved
