Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2024-06, with the labels that each got.

#2320 Add Server 2025 to VSS allowlist
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2321 Enable logging so 'finished-test' can be written
  daisy_workflows/image_build/install_package/cos/package_replacement/preload.sh
Labels: size/XS, lgtm, approved, ok-to-test

#2303 Tag rhel 8.8 with SEV_LIVE_MIGRATABLE_V2
  daisy_workflows/build-publish/enterprise_linux/rhel_8_8_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_8_sap_byos.publish.json
Labels: size/XS, lgtm, approved

#2323 Add support for other COS milestones (+109, +105) and also ARM images
  daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json
  daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
  daisy_workflows/image_build/install_package/cos/package_replacement/dev_cloudbuild.yaml
  daisy_workflows/image_build/install_package/cos/package_replacement/disable_auto_updates.sh
  daisy_workflows/image_build/install_package/cos/package_replacement/disable_readonly_rootfs.sh
  daisy_workflows/image_build/install_package/cos/replacepackage.sh
Labels: size/M, lgtm, approved, ok-to-test

#2325 Drop SEV_SNP_CAPABLE from centos-stream-9 images
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9.publish.json
Labels: size/XS, lgtm, approved

#2326 Fix Debian 12 DNS resolution issues
  daisy_workflows/image_build/debian/fai_config/package_config/GCE_SPECIFIC
Labels: size/S, lgtm, approved

#2330 Add IDPF flags to Rocky Linux 8 images which will include IDPF.
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp.publish.json
Labels: size/XS, lgtm, approved

#2331 Use new images after EOL
  daisy_workflows/sbom_validation/enterprise_sbom_test.wf.json
Labels: size/XS, lgtm, approved

#2333 Add ARM support for COS preloading
  daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json
  daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
  daisy_workflows/image_build/install_package/cos/package_replacement/dev_cloudbuild.yaml
  daisy_workflows/image_build/install_package/cos/package_replacement/preload.sh
  daisy_workflows/image_build/install_package/cos/replacepackage.sh
  daisy_workflows/image_build/install_package/install_package.wf.json
Labels: size/M, lgtm, approved, ok-to-test
