Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2025-03, with the labels that each got.

#2437 Move to GVNIC DQ for all windows images
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2439 Revert "Move to GVNIC DQ for all windows images"
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2440 Revert "Revert "Move to GVNIC DQ for all windows images""
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2441 Cleanup OWNERS file
  OWNERS
Labels: size/XS, lgtm, approved

#2443 Add licenses to base build workflows
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.wf.json
Labels: size/S, lgtm, approved

#2444 Update licenses on Daisy build workflows
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.wf.json
Labels: size/S, lgtm, approved

#2445 Update golang dependency
  daisy_workflows/image_build/install_package/cos/package_replacement/install_go.sh
Labels: size/XS, lgtm, approved

#2446 Rollback to installing GVNIC GQ in all Windows OS Versions
  daisy_workflows/image_build/windows/post_install.ps1
Labels: size/XS, lgtm, approved

#2447 IPU to Windows 2025
  daisy_workflows/build-publish/windows/windows-install-media.wf.json
  daisy_workflows/image_build/windows/windows_install_media/components/2025_64-bit/upgrade.ps1
  daisy_workflows/image_build/windows/windows_install_media/components/common/config.psm1
Labels: size/L, lgtm, approved
