Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2025-07, with the labels that each got.

#2499 clean before installing guest packages to try to avoid checksum problems
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_x86.cfg
Labels: size/XS, lgtm, approved

#2500 temporarily add centos stream 9 repos to stream 10 kickstart to bridge el9-based guest package dependency gaps
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_x86.cfg
Labels: size/S, lgtm, approved

#2502 Fix kickstart file syntax
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_x86.cfg
Labels: size/S, lgtm, approved

#2505 Update rocky_linux_8_optimized_gcp_arm64.cfg to use python 39 instead…
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_8_optimized_gcp_arm64.cfg
Labels: size/XS, lgtm, approved

#2508 Introduce workflow for deriving windows images for package testing
  daisy_workflows/image_build/install_package/windows/install_package.wf.json
  daisy_workflows/image_build/install_package/windows/installpackage.ps1
Labels: size/L, lgtm, approved

#2506 remove x86 from naming for el10-related build files
  daisy_workflows/build-publish/enterprise_linux/centos_stream_10.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_10.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_10.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_10.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_stream_10.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10.cfg
  daisy_workflows/image_build/enterprise_linux/rhel_10.wf.json
Labels: size/XS, lgtm, approved

#2511 remove x86 reference in image build for centos stream 10
  daisy_workflows/image_build/enterprise_linux/centos_stream_10.wf.json
Labels: size/XS, lgtm, approved

#2516 try to redirect default console logging for centos stream 10 images in kickstart
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/S, lgtm, approved

#2518 use access token for curl for centos stream 10 kickstarts
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2521 attempt to install gcloud and gsutil from tarball for centos stream 10 kickstart
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/S, lgtm, approved

#2522 source google cloud sdk command line tools for centos stream 10 kickstarts
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2525 configure /etc/profile.d for centos stream 10 kickstart to ensure google cloud sdk binaries are in the path as well
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/S, lgtm, approved

#2526 add additional path export to bashrc for centos stream 10 kickstart files
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2527 Add sources.list to fai configs for Debian 11
  daisy_workflows/image_build/debian/fai_config/files/etc/apt/sources.list/BULLSEYE
Labels: size/XS, lgtm, approved
