Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2025-09, with the labels that each got.

#2557 Add IDPF tag to EL ARM images.
  daisy_workflows/build-publish/enterprise_linux/almalinux_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_10_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/centos_stream_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_10_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_10_byos_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_8_byos_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_byos_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_arm64.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.publish.json
  daisy_workflows/image_build/enterprise_linux/almalinux_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_stream_10_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/centos_stream_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_10_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_10_byos_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_8_byos_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_byos_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_8_optimized_gcp_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rocky_linux_9_optimized_gcp_arm64.wf.json
Labels: size/M, lgtm, approved

#2563 Add support for EL10 package derived image builds
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/S, lgtm, approved

#2560 cos: update build script to install plugin manager
  daisy_workflows/image_build/install_package/cos/install_package_cos.wf.json
  daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
Labels: size/S, needs-ok-to-test, lgtm, approved

#2567 set disk type to hyperdisk-balanced for rhel arm images and use c4a
  daisy_workflows/image_build/enterprise_linux/rhel_10_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_10_byos_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_arm64.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_byos_arm64.wf.json
Labels: size/S, lgtm, approved
