Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2025-04, with the labels that each got.

#2449 Update "latest" Rocky Accel Descriptions
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
Labels: size/XS, lgtm, approved

#2455 allow overriding disk type instead of hardcoding
  daisy_workflows/image_build/install_package/install_package.wf.json
Labels: size/XS, lgtm, approved

#2452 Update build files for Debian 13
  daisy_workflows/image_build/debian/build_fai.py
  daisy_workflows/image_build/debian/debian_13_fai.wf.json
Labels: size/M, lgtm, approved

#2456 Update short descriptions for Accelerator images
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_550.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_570.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_8_optimized_gcp_nvidia_latest.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_550.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_570.publish.json
  daisy_workflows/build-publish/enterprise_linux/rocky_linux_9_optimized_gcp_nvidia_latest.publish.json
Labels: size/S, lgtm, approved
