Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2025-08, with the labels that each got.

#2528 use el10 packages for rhel 10 and centos stream 10 image builds
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_arm64.cfg
Labels: size/L, lgtm, approved

#2534 RHEL 9.6 for SAP build configs
  daisy_workflows/build-publish/enterprise_linux/rhel_9_6_sap.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_6_sap.wf.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_6_sap_byos.publish.json
  daisy_workflows/build-publish/enterprise_linux/rhel_9_6_sap_byos.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_6_sap.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_9_6_sap_byos.cfg
  daisy_workflows/image_build/enterprise_linux/rhel_9_6_sap.wf.json
  daisy_workflows/image_build/enterprise_linux/rhel_9_6_sap_byos.wf.json
Labels: size/XL, lgtm, approved

#2543 Exclude conflicting firmware packages for x86 and arm builds for centos stream 10
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2544 Exclude more conflicting firmware packages for x86 and arm builds for centos stream 10
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2547 Exclude more conflicting firmware packages for x86 and arm builds for centos stream 10
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2545 Enable debug logging on test images
  daisy_workflows/image_build/install_package/installpackage.py
  daisy_workflows/image_build/install_package/windows/installpackage.ps1
Labels: size/S, lgtm, approved

#2549 Fix patch didn't apply issue for COS image
  daisy_workflows/image_build/install_package/cos/package_replacement/compile_debian_package.sh
Labels: size/XS, lgtm, approved, ok-to-test

#2552 Remove conflicting files
  daisy_workflows/image_build/debian/build_fai.py
Labels: size/XS, lgtm, approved
