Repository GoogleCloudPlatform/compute-image-tools, pull requests merged in 2025-06, with the labels that each got.

#2469 remove iburst flag for timesource for rhel 10 kickstart
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_x86.cfg
Labels: size/XS, lgtm, approved

#2478 remove dhcp-client and related code from rhel-10 kickstart
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_x86.cfg
Labels: size/S, lgtm, approved

#2480 Update installpackage resolv.conf check
  daisy_workflows/image_build/install_package/installpackage.py
Labels: size/S, lgtm, approved

#2484 remove logic disabling rhui and force releasever to 9 temporarily
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/rhel_10_x86.cfg
Labels: size/S, lgtm, approved

#2486 Fix GPG Key URL path for Rocky 9
  daisy_workflows/image_build/enterprise_linux/kickstart/rocky_linux_9_optimized_gcp.cfg
Labels: size/XS, lgtm, approved

#2490 rename centos 10 files to include x86 architecture
  daisy_workflows/image_build/enterprise_linux/centos_stream_10_x86.wf.json
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_x86.cfg
Labels: size/XS, lgtm, approved

#2493 fix typo with centos stream 10 x86 license name
  daisy_workflows/build-publish/enterprise_linux/centos_stream_10_x86.publish.json
Labels: size/XS, lgtm, approved

#2494 try to fix issue with the software selection and timezone for centos stream 10
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_x86.cfg
Labels: size/M, lgtm, approved

#2496 remove dhcp-client from centos-stream-10 arm kickstart
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2497 remove dhcp client config from centos stream 10 arm kickstart
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
Labels: size/XS, lgtm, approved

#2498 move package installation steps for centos stream 10 kickstart to one block and enable crb to try to fix the failure related to find all necessary dependencies
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_arm64.cfg
  daisy_workflows/image_build/enterprise_linux/kickstart/centos_stream_10_x86.cfg
Labels: size/M, lgtm, approved
